dragonflyoss/nydus

.travis.yml
Makefile

Add travis config

---

README.md
docs/tutorial.md

- add a tutorial for beginners;
- add the tutorial link in README.md;

doc: add a tutorial for beginners

---

contrib/nydusify/remote/remote.go
rafs/src/metadata/cached.rs
rafs/src/metadata/direct.rs
rafs/src/metadata/layout.rs
rafs/src/metadata/mod.rs
rafs/src/storage/backend/oss.rs
rafs/src/storage/backend/registry.rs
rafs/src/storage/cache/blobcache.rs
rafs/src/storage/cache/mod.rs
src/bin/nydus-image/builder.rs
src/bin/nydus-image/node.rs
src/bin/nydus-image/stargz.rs
src/bin/nydus-image/tree.rs

This PR includes a pile of patches enhancing Stargz feature together with some bugfixes.

Stargz enhancement and bugfix

---

contrib/nydusify/Makefile
docs/nydusify.md

Signed-off-by: Dominic Yin <yindongchao@inspur.com>

update nydusify.md and add GO111MODULE flags for nydusify build

---

.travis.yml
misc/smoke/Dockerfile
rafs/src/metadata/layout.rs
rafs/src/storage/backend/oss.rs
rafs/src/storage/backend/registry.rs
rafs/src/storage/backend/request.rs
src/bin/nydus-image/builder.rs
src/bin/nydus-image/stargz.rs
src/bin/nydus-image/validator.rs
src/bin/nydusd/main.rs

rust v1.49.0 has stricter constraint, causing Nydus code
compiling failed. This PR will sovle it.
Fixes: #39
Signed-off-by: LiYa'nan <oliverliyn@gmail.com>

bugfix: fix code compiling failed with rust-1.49.0

---

Cargo.lock
api/Cargo.toml
rafs/src/fs.rs
src/bin/nydusd/api_server_glue.rs
src/bin/nydusd/daemon.rs
src/bin/nydusd/main.rs

2 of the 3 patches aim at cleaning code up.
There is also a small fix for io-stats to catch more accurate metrics of rafs.

A couple of fixes and cleanup 

---

Cargo.lock
Cargo.toml
api/src/http.rs
api/src/http_endpoint.rs
rafs/Cargo.toml
src/bin/nydusd/api_server_glue.rs
src/bin/nydusd/daemon.rs
src/bin/nydusd/fusedev.rs
src/bin/nydusd/virtiofs.rs
utils/Cargo.toml

Fuse-rs crate has enhanced its API. Therefore, we firstly adapt to those APIs to catch more metrics and make nydus error handling more convenient.

Adapt to new fuse-rs APIs

---

rafs/src/fs.rs
rafs/src/io_stats.rs
src/bin/nydusd/daemon.rs

This will make the trimming code more elegant.

Define a macro as a helper to trim rafs configuration when export

---

rafs/src/storage/compress/lz4_standard.rs
src/bin/nydus-image/builder.rs
src/bin/nydus-image/main.rs
src/bin/nydus-image/node.rs
src/bin/nydus-image/trace.rs
src/bin/nydus-image/tree.rs

This tracer will help us to analyze what the is being built and find out the bottleneck of nydus-image.

Add process tracer for nydus-image tool

---

src/bin/nydus-image/node.rs

When rafs report its file disk usage, it should also include the space xattr is occupying.

rafs: xattrs size should also be reflected thru i_blocks

---

api/openapi/nydus-rs.yaml
api/src/http.rs
api/src/http_endpoint.rs
rafs/src/io_stats.rs

Nydus api server has evolved a lot. Therefore add more objects to open-api yaml

Enrich open-api yaml

---

contrib/nydusify/cmd/nydusify.go
contrib/nydusify/examples/converter/main.go
contrib/nydusify/pkg/build/workflow.go
contrib/nydusify/pkg/converter/converter.go
contrib/nydusify/pkg/converter/layer.go
contrib/nydusify/pkg/converter/manifest.go
contrib/nydusify/pkg/converter/provider/remote.go
contrib/nydusify/pkg/converter/provider/source.go
contrib/nydusify/pkg/utils/utils.go
contrib/nydusify/tests/nydusify.go

- Nydusify: add some comments for mount
- Nydusify: allow leaving auth empty if no authorization be required
- Nydusify: make source provider as slice
- Nydusify: improve Mount method in SourceProvider interface
- Nydusify: retry for layer pull and push

Nydusify: some improvements for package interface

---

contrib/nydus-snapshotter/Makefile
contrib/nydus-snapshotter/go.mod
contrib/nydus-snapshotter/go.sum
contrib/nydus-snapshotter/pkg/store/database_test.go

Snapshotter `go test` goes insane. Try to cure it.

Fix snapshotter test

---

Cargo.lock
Cargo.toml
api/Cargo.toml
rafs/Cargo.toml
utils/Cargo.toml

Bump nydus-rs version to v1.0.0

---

docs/nydusd.md

We have changed the API but forgot to update the example.

docs: update nydusd curl example

---

Cargo.lock
Cargo.toml
api/src/http_endpoint.rs
contrib/nydus-snapshotter/snapshot/snapshot.go
rafs/src/fs.rs
rafs/src/io_stats.rs
rafs/src/lib.rs
src/bin/nydusd/api_server_glue.rs
src/bin/nydusd/daemon.rs
src/bin/nydusd/main.rs
utils/src/lib.rs

Fix a problem happened during rafs prefetch with rate limiter enabled.
This problem happened accidentally  causing by a misuse of unsafe File object conversion.

Picking fix fd leakage

---

README.md

Also this patch formatted Readme.md by a formatter.

Readme: update slack url to one that never expires

---

contrib/nydus-snapshotter/README.md
docs/containerd-env-setup.md
docs/nydus-image.md
docs/nydusd.md
docs/nydusify.md
docs/tutorial.md

With the new release of Nydus, the doc is somewhat stagnant, this
patch fixes some minor mistakes.

Doc: fix out of date docs

---

contrib/nydusify/pkg/converter/layer.go

Push blob layer to cache image failed because the blob was deleted earlier:
```
Failed push layer to cache image: Open blob file: open tmp/blobs/x:
no such file or directory
```

Nydusify: fix blob push issue when enabling build cache

---

contrib/nydusify/cmd/nydusify.go
contrib/nydusify/examples/converter/main.go
contrib/nydusify/pkg/checker/checker.go
contrib/nydusify/pkg/checker/rule/manifest.go
contrib/nydusify/pkg/converter/converter.go
contrib/nydusify/pkg/converter/manifest.go
contrib/nydusify/pkg/converter/provider/source.go
contrib/nydusify/pkg/parser/parser.go
contrib/nydusify/pkg/utils/utils.go
contrib/nydusify/tests/nydusify.go

Now nydusify can convert image of arm64 image from on x86_64 host.

Nydusify supports multi-platform conversion

---

Cargo.lock
rafs/src/metadata/layout.rs
storage/src/backend/registry.rs
storage/src/cache/blobcache.rs
storage/src/cache/chunkmap/indexed.rs

Try to make clippy happy when moving to a higher version

Fix a couple of clippy warnings

---

.gitignore
misc/musl-static/Dockerfile
misc/nydus-smoke/Dockerfile
rafs/src/fs.rs
rafs/src/metadata/layout.rs
rafs/src/metadata/mod.rs
src/bin/nydus-image/builder/stargz.rs
src/bin/nydus-image/core/blob.rs
src/bin/nydus-image/core/bootstrap.rs
src/bin/nydus-image/core/node.rs
src/bin/nydus-image/inspect.rs
src/bin/nydusd/daemon.rs
src/bin/nydusd/main.rs
storage/src/backend/localfs.rs
utils/Cargo.toml
utils/build.rs
utils/src/digest.rs
utils/src/exec.rs
utils/src/fuse.rs
utils/src/inode_bitmap.rs
utils/src/lib.rs
utils/src/logger.rs
utils/src/metrics.rs
utils/src/signal.rs
utils/src/types.rs

1) upgrade tool-chain to  1.52.1
2) fix a bug in single inflight handling
3) refine some implementation of nydus-utils
4) split nydus-utils into three crates to speed up build

Split nydus-utils into three crates

---

Cargo.lock
Cargo.toml
app/Cargo.toml
error/Cargo.toml
rafs/Cargo.toml
storage/Cargo.toml
utils/Cargo.toml

Publish nydus-error and nydus-app crates to crates.io.

nydus-error/app: publish to crates.io

---

contrib/nydus-snapshotter/Makefile

The Makefile lost go command, so it cannot build
Signed-off-by: yuhongqi <yuhongqi@bytedance.com>

Makefile: fix Makefile error

---

src/bin/nydus-image/inspect.rs
tests/smoke.rs

Thus to show permission bits and human-readable flags

Enhance rafs inspector

---

Makefile

Makefile: refine Makefile reducing duplicated code

---

.github/workflows/ci.yml
Makefile

This patch will reduce GitHub/Action running time quite considerably.

Fix cargo build artifacts and docker layers are not cached

---

contrib/nydusify/pkg/converter/converter.go
contrib/nydusify/pkg/metrics/metrics.go

Nydusify already records other metrics like total conversion times.  Now we are going to add an extra  one so as to calculate success ratio

Record failures count for nydusify

---

Makefile

Currently, golang components like snapshotter, ctr-remote, nydusify are
built within containers which bind-mount host GOPATH. When user is root
insides container, it will change files' owner in GOPATH to root. So
other users work on the same host can not access those files in GOPATH anymore.
In addition, current golang build will cause dind(docker in docker) if customers'
software build system is on top of container.

makefile: a option to build golang components without docker

---

rafs/src/fs.rs

Make sure all root inode mode is 0755.

rafs: fix up access API root mode

---

README.md
docs/containerd-env-setup.md
docs/tutorial.md

Fix some typo and style issues.
Also add instructions on how to use nerdctl with containerd and nydus-snapshotter.

docs: approach to start container by nerdctl and refine docs

---

Cargo.lock
Cargo.toml
rafs/Cargo.toml
src/bin/nydusd/fusedev.rs
src/bin/nydusd/main.rs
storage/Cargo.toml
utils/Cargo.toml

So that we can mount fusedev in rw mode as well.

nydusd: add fusedev writable cmd argument

---

storage/src/cache/blobcache.rs

It previously uses the default runtime builder which creates
a thread for each cpu core. Nydusd on a server equipped many
cpu sockets and cores will start many threads most of which are
idle.
In addition, use `spawn_blocking` instead which is more reasonable
within blobcache scenario

cache: set the number of worker threads of tokio threads pool

---

.github/workflows/ci.yml
Makefile
contrib/ctr-remote/Makefile
contrib/ctr-remote/go.mod
contrib/ctr-remote/go.sum
contrib/docker-nydus-graphdriver/Makefile
contrib/nydus-overlayfs/Makefile
contrib/nydus-snapshotter/Makefile
contrib/nydusify/Makefile

We missed testing contrib code in CI and ended up being broken by the dependabot LOL.

fix ctr remote build and add CI

---

README.md

readme: refine the description of #community

---

contrib/docker-nydus-graphdriver/.golangci.yml
contrib/docker-nydus-graphdriver/Makefile
contrib/docker-nydus-graphdriver/plugin/nydus/glue.go
contrib/docker-nydus-graphdriver/plugin/nydus/nydus.go

Utilize golangci-lint to do static for docker-graphdriver and perform it during smoke test.

Add golangci lint graphdriver

---

.github/workflows/convert.yml

Need to specify the minutes as well.

workflow: fix up cron time

---

rafs/src/lib.rs
src/bin/nydus-image/core/bootstrap.rs

Issue: if we enable v6 build by specifying these option group:
`--rafs-version=6`, `--source-type=diff` and `--diff-bootstrap-dir`
There is no have bootstrap output in bootstrap directory, this
causes that failed to build v6 image in harbor-acceld or buildkit.
Fix: call release() method after all bootstrap write operations.

Builder: fix no bootstrap output in v6 diff build

---

utils/src/metrics.rs

Thus to make it more suggestive

metrics: rename metric read_latency_hits_dist

---

contrib/nydusify/examples/manifest/cache_manifest.json
contrib/nydusify/examples/manifest/manifest.json
contrib/nydusify/pkg/cache/cache.go
contrib/nydusify/pkg/checker/rule/manifest.go
contrib/nydusify/pkg/checker/tool/inspector.go
contrib/nydusify/pkg/converter/cache.go
contrib/nydusify/pkg/converter/chunk_dict.go
contrib/nydusify/pkg/converter/converter.go
contrib/nydusify/pkg/converter/layer.go
contrib/nydusify/pkg/converter/manifest.go
contrib/nydusify/pkg/utils/constant.go
contrib/nydusify/tests/e2e_test.go
contrib/nydusify/tests/image_test.go
contrib/nydusify/tests/nydusify.go
contrib/nydusify/tests/texture/chunk-dict-1/Dockerfile
contrib/nydusify/tests/texture/chunk-dict-2/Dockerfile

Most of which are a couple of fixes to chunk-dict for chunk data de-duplicating along with some tests added

Improve chunk-dict processing of nydusify 

---

Cargo.lock
Cargo.toml

Bump version to 1.1.2

---

.github/workflows/release.yml

Enable release workflow for RC version

---

rafs/src/metadata/layout/v6.rs
src/bin/nydus-image/core/bootstrap.rs
src/bin/nydus-image/core/node.rs

Fix functionality regression and add tests.
Also fix malfunctioning when building v6 image

A couple of fixes for Rafs v6 disk layout

---

rafs/src/fs.rs
rafs/src/lib.rs
rafs/src/metadata/cached_v5.rs
rafs/src/metadata/direct_v5.rs
rafs/src/metadata/direct_v6.rs
rafs/src/metadata/layout/v6.rs
rafs/src/metadata/md_v6.rs
rafs/src/metadata/mod.rs
rafs/src/metadata/noop.rs
rafs/src/mock/mock_inode.rs
rafs/src/mock/mock_super.rs
src/bin/nydus-image/core/bootstrap.rs
src/bin/nydus-image/core/context.rs
src/bin/nydus-image/core/node.rs
src/bin/nydus-image/core/tree.rs
src/bin/nydusd/fusedev.rs
src/bin/nydusd/main.rs
storage/src/cache/dummycache.rs
storage/src/cache/filecache/cache_entry.rs
storage/src/cache/mod.rs
storage/src/device.rs
storage/src/meta/mod.rs
tests/nydusd.rs
utils/src/metrics.rs

This patch empowers nydusd with capability to work on Rafs version 6 a subset part of EROFS.

Implement Rafs v6 for nydusd

---

docs/containerd-env-setup.md

add containerd configuration version 2 setting
in containerd-env.setup.md
Signed-off-by: luodaowen.backend <luodaowen.backend@bytedance.com>

docs: containerd configuration version 2 setting

---

Cargo.lock
app/Cargo.toml
error/Cargo.toml
utils/Cargo.toml

nydus-error v0.2
nydus-app v0.2
nydus-utils v0.1

Prepare for publishing nydus-utils crate

---

contrib/nydusify/cmd/nydusify.go
contrib/nydusify/pkg/build/builder.go
contrib/nydusify/pkg/compactor/compactor.go
contrib/nydusify/pkg/packer/packer.go
contrib/nydusify/pkg/packer/pusher.go

Signed-off-by: henry.hj <henry.hj@antgroup.com>

nydusify: support compact blob before pack

---

.github/workflows/ci.yml
README.md

Run daily CI and show its status.

readme: add ci status badget

---

Cargo.lock
Cargo.toml
rafs/src/metadata/direct_v6.rs
rafs/src/metadata/layout/mod.rs
rafs/src/metadata/layout/v6.rs
rafs/src/metadata/md_v6.rs
rafs/src/metadata/mod.rs
src/bin/nydus-image/builder/diff.rs
src/bin/nydus-image/builder/directory.rs
src/bin/nydus-image/builder/stargz.rs
src/bin/nydus-image/core/blob.rs
src/bin/nydus-image/core/blob_compact.rs
src/bin/nydus-image/core/bootstrap.rs
src/bin/nydus-image/core/chunk_dict.rs
src/bin/nydus-image/core/context.rs
src/bin/nydus-image/core/layout.rs
src/bin/nydus-image/core/node.rs
src/bin/nydus-image/core/tree.rs
src/bin/nydus-image/main.rs
src/bin/nydus-image/stat.rs
tests/diff.rs

Add a series of commits to support importing chunk-dict bootstrap in diff build to implement global chunk deduplication.

Builder: support chunk dict in diff build

---

README.md

Doc: add nydus ecosystem list

---

Makefile
README.md
docs/containerd-env-setup.md
docs/tutorial.md

- add `make clean` target.
- update docs for running nydus manually according to tutorials.

Fix some doc and add `make clean` target.

---

Makefile
docs/nydus-design.md
rafs/src/fs.rs
rafs/src/lib.rs
rafs/src/metadata/direct_v6.rs
rafs/src/metadata/layout/v6.rs
rafs/src/metadata/mod.rs

- e83bcd2c0c965bac1db97348e2ac62fcdf90fbd5 rafs: fix some comments
- ab40948e9137cc861288962158ef12f9f4e3d303 rafs: use RafsMode::from_str to set mode
- 0861e759fc915b2ad70c932119b234e40d417866 docs: fix some markdown format
- 8ccab6294834673547b3d76878f331a8abef548a Makefile: clean standard target for make clean

Some minor fixes

---

storage/src/meta/mod.rs

Lz4 does not support concurrent decompression of the same data into
the same piece of memory. There will be multiple containers mmap the
same file, causing the buffer to be shared between different
processes. This will cause data errors due to race issues when
decompressing with lz4. We solve this problem by creating a temporary
memory to hold the decompressed data.
Because this process will only be executed when the blob.meta file is
created for the first time, which means that a machine will only
execute the process once when the blob.meta is created for the first
time, the memory consumption and performance impact are relatively
small.
Signed-off-by: gexuyang <gexuyang@linux.alibaba.com>

bugfix: storage: Fix the race problem when decompressing with lz4

---

app/src/lib.rs
rafs/src/lib.rs
src/bin/nydus-image/builder/diff.rs
src/bin/nydus-image/core/context.rs
storage/src/lib.rs

Fix some comments that crashes cargo doc command.

doc: fix cargo doc issues

---

rafs/src/metadata/direct_v6.rs

With this, v6 prefetch with a dynamic prefetch file list is able to work as expected.

fix v6 panic due to a trace!

---

src/bin/nydusd/main.rs

Refine nydusd commandline parsing code to prepare for fscache.

Refine nydusd commandline parsing code

---

storage/src/cache/cachedfile.rs
storage/src/cache/fscache/mod.rs
storage/src/meta/mod.rs

Enhance storage/filecache to enable read amplify, this is also a candidate for 2.0

Enhance storage/filecache to enable read amplification

---

README.md
docs/nydus_with_macos.md

Signed-off-by: killagu <killa123@126.com>

doc: add macos doc

---

src/bin/nydusd/service_controller.rs
storage/src/meta/mod.rs

Fix testcase break due to read amplification

Fix testcase break due to read amplification

---

docs/nydus-fscache.md

add nydus fscache document

---

src/bin/nydusd/fs_cache.rs

Add support for fscache protocol v9

---

docs/nydus-fscache.md

doc: add fscache usage with snapshotter

---

Cargo.lock
docs/nydus-design.md
rafs/src/metadata/layout/v5.rs
rafs/src/metadata/layout/v6.rs
rafs/src/metadata/mod.rs
src/bin/nydus-image/main.rs
storage/src/device.rs
storage/src/meta/mod.rs
utils/Cargo.toml
utils/src/compress/lz4_standard.rs
utils/src/compress/mod.rs
utils/src/compress/zstd_standard.rs

… be tested.
Signed-off-by: Qi Wang <mpiglet@outlook.com>

Add support for zstd compression algorithm for blob file.

---

docs/nydus-fscache.md

doc: refine fscache user guide with containerd runtime

---

.github/workflows/convert.yml
.github/workflows/release.yml

* workflow: only do new release upon push event
* workflow: fix convert.yml release download URL

Fix convert and release workflow issues

---

Cargo.lock

References: crossbeam-rs/crossbeam#781

Cargo: update crossbeam-utils dependency

---

docs/nydus-design.md

Let's give some hints about Rafs v6.

docs: update brief summary about rafs filesystem

---

.github/workflows/ci.yml
Cargo.lock
Cargo.toml
api/Cargo.toml
storage/Cargo.toml

To bring fixup https://github.com/dragonflyoss/image-service/pull/447
CI: https://github.com/imeoer/image-service/actions/runs/2394255593

release: prepare for v2.0.1

---

.github/workflows/ci.yml

action: allow run CI for pr wants merge to any branch

---

Cargo.lock
app/CHANGELOG.md
app/Cargo.toml
blobfs/Cargo.toml
utils/CHANGELOG.md
utils/Cargo.toml

Prepare for publishing nydus-app v0.2 and nydus-utils v0.2

Prepare for publishing nydus-app v0.2 and nydus-utils v0.2

---

storage/src/cache/cachedfile.rs
storage/src/cache/fscache/mod.rs

storage: fix clippy warnings

---

src/bin/nydusd/fs_service.rs
src/bin/nydusd/fusedev.rs
src/bin/nydusd/service_controller.rs

Clean up some clippy warnings in nydusd.

nydusd: clean up clippy warnings

---

docs/nydus-fscache.md

- Fix up links;
- Drop _frequently updated_ warning, etc.

doc: update outdated information

---

Cargo.lock
Cargo.toml
rafs/src/fs.rs
utils/Cargo.toml
utils/src/metrics.rs

Refine metrics related code by
- rename GlobalIoStats to FsIoStats
- rename IOS_SET to FS_METRICS
- rename global_update to fop_update
- rename export_global_stats to export_fs_stats
- add some docs

Refine utils/metrics related code

---

docs/nydus-fscache.md

doc: nydus-fscache.md: fix up referenced RAFS v6 images

---

src/bin/nydus-image/core/node.rs

Signed-off-by: zhaoshang <zhaoshangsjtu@linux.alibaba.com>

Add some comments

---

README.md

doc: fix broken dingtalk invitation url and others

---

Cargo.lock
Cargo.toml
src/bin/nydusd/main.rs

Prepare for publishing nydus-2.1.0-alpha1.

Prepare for publishing nydus-2.1.0-alpha1

---

Cargo.lock
api/Cargo.toml

Prepare for publishing v0.1.1 to update dependency.

api: prepare for publishing v0.1.1

---

.github/workflows/convert.yml
misc/top_images/fsck.patch

Add top images v6 format conversion and check in the nightly
top images conversion test.

github action: add top images v6 format conversion and check

---

Cargo.lock
Cargo.toml
api/Cargo.toml
app/Cargo.toml
blobfs/Cargo.toml
rafs/Cargo.toml
storage/Cargo.toml

Prepare for publishing v2.1.0-alpha2 to fix a bug in alpha, and relax
dependency constraints.

Prepare for publishing v2.1.0-alpha2

---

docs/nydus-fscache.md

Add command hint `make menuconfig` to help users who are not familiar with linux kernel build.

use precise command in nydus-fscache doc

---

.github/workflows/release.yml
Cargo.lock
Makefile
src/bin/nydus-cached/main.rs
src/bin/nydus-image/builder/diff.rs
src/bin/nydus-image/builder/stargz.rs
src/bin/nydus-image/core/bootstrap.rs
src/bin/nydus-image/core/node.rs
tests/builder.rs
utils/Cargo.toml
utils/src/compact.rs
utils/src/lib.rs

nydus-image nydus-cached: builds on macos

---

rafs/src/metadata/layout/v6.rs
src/bin/nydus-image/core/bootstrap.rs

Sorry, this PR doesn't have any test case, I just tested it manually, and for the next PR I'll introduce `fssum` to test.

nydus-image: nydus v6 support explicit uid and gid

---

README.md

doc: add description about estargz and nerdctl support

---

README.md

README.md: fix up leftovers of stargz for fscache

---

.gitignore
contrib/nydus-test/framework/distributor.py
contrib/nydus-test/framework/rafs.py
contrib/nydus-test/functional-test/test_nydus.py
contrib/nydus-test/functional-test/test_nydusify.py
contrib/nydus-test/functional-test/test_snapshotter.py
contrib/nydus-test/nydus_test_config.py
storage/src/cache/dummycache.rs
storage/src/meta/mod.rs

No logic changed. Just a few spelling mistakes fixes

Fix spelling mistakes

---

docs/nydus-fscache.md

Add a recording for fscache lazy pulling

---

contrib/nydusify/cmd/nydusify.go
contrib/nydusify/pkg/packer/packer.go

nydusify: Add fs-version args for pack subcommand

---

.github/workflows/it.yml
contrib/nydus-test/framework/rafs.py
contrib/nydus-test/functional-test/test_layered_image.py

Let's perform  both API test suite and layered image conversion test suite during IT workflow

Add layered image conversion to IT workflow and replace storage backend with BACKEND_PROXY

---

docs/nydusd.md

Add a link for nydus-image.md as a reference.

Update nydusd doc for bootstrap creation

---

rafs/src/fs.rs

Rafs v6's root inode number is not 1. So call its
method to get the root inode as the root to scan files
that will be prefetched.

rafs: use real fs root ino to trigger prefetch

---

src/bin/nydus-image/unpack/pax.rs

To make the unpacked tar consistent with the OCI-formatted tar before the pack,
we need to backfill the username and groupname in the tar header, which may
break the repeatable build when unpacking in different hosts, but actually has
little effect.

unpack: fix empty username and groupname

---

README.md

Also complete erofs over fscache presentation video.

README.md: add description about community meeting

---

Cargo.lock
Cargo.toml

Prepare for releasing v2.1.0-rc1.

nydus: prepare for releasing v2.1.0-rc1

---

storage/src/cache/cachedfile.rs
storage/src/cache/mod.rs
storage/src/device.rs
storage/src/meta/mod.rs

Thus not converting chunk types everywhere. Only use BlobChunkInfo when processing backend IO. BlobIoChunk is
only used to pass backend IO requests from Rafs layer.

storage: use dyn BlobChunkInfo in storage layer

---

storage/src/cache/state/blob_state_map.rs

storage: clear some dead code

---

storage/src/cache/worker.rs

Running in debug mode, prefetch workers are always paniced.
torage_worker_1' panicked at 'Cannot drop a runtime in a context where blocking is not allowed. This happens when a runtime is dropped from within an asynchronous context.': /home/gechangwei/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-4f7dbcce21e258a2/tokio-1.20.0/src/runtime/blocking/shutdown.rs:51
0: <backtrace::capture::Backtrace as core::default::Default>::default
at /home/gechangwei/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-4f7dbcce21e258a2/backtrace-0.3.66/src/capture.rs:410:9
1: log_panics::Config::install_panic_hook::{{closure}}
at /home/gechangwei/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-4f7dbcce21e258a2/log-panics-2.1.0/src/lib.rs:115:29
2: std::panicking::rust_panic_with_hook
at …

storage: don't drop tokio runtime to non-blocking context

---

Cargo.toml

release: prepare for v2.1.0-rc.2

---

Cargo.lock

release: update Cargo.lock to v2.1.0-rc.2

---

contrib/nydus-test/conftest.py
contrib/nydus-test/framework/erofs.py
contrib/nydus-test/framework/nydus_anchor.py
contrib/nydus-test/framework/rafs.py
contrib/nydus-test/functional-test/test_api.py
contrib/nydus-test/functional-test/test_erofs.py
contrib/nydus-test/functional-test/test_fault.py
contrib/nydus-test/functional-test/test_image_compatibility.py
contrib/nydus-test/functional-test/test_layered_image.py
contrib/nydus-test/functional-test/test_nydus.py
contrib/nydus-test/functional-test/test_nydusify.py
contrib/nydus-test/functional-test/test_stargz.py
contrib/nydus-test/functional-test/test_stress.py
contrib/nydus-test/nydusd_client.py

1. Improve current framework to support start nydusd as fscache daemon
2. add test case for nydusd as fscache daemon

nydus-test framework supports fscache mode

---

contrib/nydus-test/README.md

nydus-test: clean up readme as a simple usage guide

---

src/bin/nydusctl/commands.rs

sudo nydusctl --sock api_sock info
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/bin/nydusctl/commands.rs:369:68
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted

nydusctl: fix panic when query nydusd as fscache daemon

---

storage/src/meta/mod.rs

this pr will fix https://github.com/dragonflyoss/image-service/issues/693

storage: fix blob batch read error

---

src/bin/nydusd/main.rs

increase the default fscache threads to 4.

nydusd: increase default fscache threads

---

contrib/nydus-test/framework/rafs.py
contrib/nydus-test/framework/workload_gen.py
contrib/nydus-test/functional-test/test_erofs.py
contrib/nydus-test/functional-test/test_nydusify.py

1. also validate symlink contents
2. add test case for erofs with prefetch enabled
3. add a test target OCI image openjdk

add cases and enhance framework symlink verifier 

---

src/bin/nydusctl/client.rs
src/bin/nydusctl/commands.rs
src/bin/nydusctl/main.rs

Refine commandline help message for nydusctl.

nydusctl: refine commandline help message

---

Makefile

This reverts commit 88311730ac3681d6227358e0e3bcce40fb62eff5.

Revert "makefile: fix a minor bug in Makefile"

---

src/bin/nydusd/main.rs

The `nydusd singleton` subcommand will create a global shared daemon, make it work in that way.

nydusd: fix a bug in handling singleton subcommand

---

Cargo.lock
Cargo.toml

Sorry for missing updating the version in `Cargo.toml` at the last release.

release: prepare for v2.1.0-rc.3.1

---

.github/workflows/it.yml

We need to validate fuse + rafsv5 as well.

action: enable fuse + rafsv5 integration test

---

contrib/nydusify/cmd/nydusify.go
contrib/nydusify/pkg/checker/tool/nydusd.go
contrib/nydusify/pkg/converter/converter.go
contrib/nydusify/pkg/viewer/viewer.go

Improve help message for view, check and build subcommands, also fix several panic issues.

Improve help message for view, check and build subcommands

---

.github/workflows/ci.yml
.github/workflows/convert.yml
.github/workflows/it.yml
.github/workflows/release.yml
contrib/nydus-test/framework/rafs.py
contrib/nydus-test/functional-test/test_nydus.py
contrib/nydus-test/functional-test/test_nydusify.py

1. do not hard code fs_version
2. fix up build target dir
ref: https://github.com/dragonflyoss/image-service/actions/runs/3124571758

tests: fix up integration tests

---

api/src/http.rs
docs/nydusd.md
storage/src/backend/connection.rs

This PR is addressing the legacy issues of #736 

fix mirror's legacy issues

---

rafs/src/fs.rs
rafs/src/lib.rs
rafs/src/metadata/cached_v5.rs
rafs/src/metadata/layout/mod.rs
rafs/src/metadata/layout/v5.rs
rafs/src/metadata/layout/v6.rs
rafs/src/metadata/md_v6.rs
src/bin/nydus-image/builder/stargz.rs
src/bin/nydus-image/core/bootstrap.rs
src/bin/nydus-image/core/chunk_dict.rs
src/bin/nydus-image/core/node.rs
src/bin/nydus-image/core/tree.rs
src/bin/nydusd/blob_cache.rs
tests/smoke.rs

Enhancements to rafs v6 implementation with:
1) correctly handle endian
2) better handle of xattr
3) strict validation of data structures

Enhancements to rafs v6 implemntation (for 2.2)

---

rafs/src/fs.rs
rafs/src/metadata/cached_v5.rs
rafs/src/metadata/direct_v5.rs
rafs/src/metadata/direct_v6.rs
rafs/src/metadata/layout/v5.rs
rafs/src/metadata/layout/v6.rs
rafs/src/metadata/md_v5.rs
rafs/src/metadata/mod.rs
rafs/src/mock/mock_inode.rs
src/bin/nydus-image/inspect.rs

Syntax only changes to refine documentation and consts.

rafs: refine doc and consts

---

README.md

Add "Introduction to Nydus Image Service on In-kernel EROFS" to README.md.

README.md: add OSSEU22 meterials

---

contrib/nydusify/pkg/backend/oss.go
contrib/nydusify/pkg/packer/packer.go
contrib/nydusify/pkg/packer/pusher.go
contrib/nydusify/pkg/packer/pusher_test.go

[ISSUE](https://github.com/dragonflyoss/image-service/issues/608)

refact: use specified object prefix and meta prefix directly

---

rafs/src/metadata/cached_v5.rs
rafs/src/metadata/direct_v5.rs

Enforce stricter inode validation rules for v5 by: 1) ensure ino is not zero
2) inode is less than max_inodes
3) i_name is not empty
4) parent inode is not zero
5) n_link is not zero
6) parent inode is less than current inode for non-hard-link inodes 7) i_blocks is correct
8) child inode is bigger than parent
9) child count is corrent

rafs: enforce stricter inode validation rules for v5

---

src/bin/nydus-image/inspect.rs

Because rafs v6 doesn't support get_parent, the prefetch and icheck command of inspect will cause error. We fixed it by handling get_file_name get_file_name and path_from_ino for rafs v6 files separately. 
For hardlink, we will get all the paths of file:
This PR is addressing #768 

nydus-image: fix inspect to get correct path of rafs v6 file

---

api/src/http.rs
contrib/nydusify/pkg/checker/rule/filesystem.go
contrib/nydusify/pkg/checker/tool/image.go
docs/nydusd.md
storage/src/backend/connection.rs
storage/src/backend/oss.rs
storage/src/backend/registry.rs
storage/src/cache/cachedfile.rs

They were clear cherry-pick
Bin Tang (1):
fix mirror's performance issue
Xin Yin (1):
storage: retry timeout chunks for fscache ondemand path
Yan Song (1):
nydusify: fix overlay error for image with single layer

Backport some patches for stable/v2.1

---

.github/workflows/release.yml

action: update release notes for download mirror

---

Cargo.lock
Cargo.toml
src/bin/nydus-image/main.rs
src/bin/nydusctl/main.rs
src/bin/nydusd/main.rs
src/bin/nydusd/service_controller.rs
src/bin/nydusd/upgrade.rs

In order to use derive API to refactor, we upgrade clap firstly.
Signed-off-by: Wenyu Huang <huangwenyuu@outlook.com>

upgrade clap to 4.0

---

README.md
docs/containerd-env-setup.md

docs: update nerdctl description

---

src/bin/nydus-image/main.rs

Change requires_if to required_if_eq_any
Signed-off-by: Wenyu Huang <huangwenyuu@outlook.com>

nydus-image: fix clap

---

Cargo.lock
api/Cargo.toml
app/Cargo.toml
blobfs/Cargo.toml
error/Cargo.toml
rafs/Cargo.toml
storage/Cargo.toml
utils/Cargo.toml

Prepare for publishing to crates.io.

prepare for publishing to crates.io

---

storage/src/backend/registry.rs

There is no need to change 'grant_type' for refreshing registry tokens. Because we use the URL with cached 'grant_type'(e.g. `password`) can get token as well.
Related to https://github.com/dragonflyoss/image-service/pull/800

storage: remove unused code for refreshing registry tokens

---

rafs/src/metadata/direct_v5.rs
rafs/src/metadata/direct_v6.rs
rafs/src/metadata/layout/v6.rs
rafs/src/metadata/md_v6.rs
src/bin/nydus-image/core/bootstrap.rs
src/bin/nydus-image/core/node.rs

Enhance RAFS v6:
1) enforce stricter validation rules
2) refine direct_v6

Enhance RAFS v6 

---

src/bin/nydus-image/main.rs
src/bin/nydusd/main.rs

Refine nydus-image/nydusd commandline options

Refine nydus-image/nydusd commandline options

---

contrib/nydus-test/functional-test/test_nydus.py

nydus-image can't move directly blobs to a specified dir anymore. So adapt it.

nydus-test: don't test nydus-image for localfs backend

---

contrib/nydus-test/functional-test/test_api.py
contrib/nydus-test/functional-test/test_nydus.py
contrib/nydus-test/nydusd_client.py

- Also validate two root directories should not have the same inode number and verify file contents in pseudo fs dirs
- Refine how HTTP error responses are printed.

Enhance pseudo fs e2e test and refine nydusd client error message

---

contrib/nydusify/pkg/backend/oss.go

This PR fixes a potential concurrency error when push image blob layer to oss backend.
When push a image blob layer to oss backend, [the crc64 value of the blob layer will be computed, and it will be assigned to a local variable `crc64` in a goroutine](https://github.com/dragonflyoss/image-service/blob/master/contrib/nydusify/pkg/backend/oss.go#L128-L135). But when [use the local variable `crc64` to build the `multipartStatus`](https://github.com/dragonflyoss/image-service/blob/master/contrib/nydusify/pkg/backend/oss.go#L180), the goroutine may not be over yet and the local variable `crc64` may remain value `0`, which may cause an exceptional error when [validate blob object integrity in `Finalize`](https://github.com/dragonflyoss/image-service/blob/master/contrib/nydusify/pkg/backend/oss. …

nydusify: fix the concurrency error when push image blob layer to oss backend

---

storage/src/backend/registry.rs

storage: fix registry to avoid print bearer auth

---

contrib/nydusify/Makefile
contrib/nydusify/cmd/nydusify.go

nydusify: fix a typo in its version message

---

contrib/nydusify/Makefile
contrib/nydusify/cmd/nydusify.go

This is clean cherry-pick from master branch

nydusify: beautify version print message of nydusify

---

contrib/nydusify/cmd/nydusify.go
contrib/nydusify/pkg/build/builder.go
contrib/nydusify/pkg/build/workflow.go
contrib/nydusify/pkg/converter/converter.go

Clearly port some patches to stable v2.1
Changwei Ge (2):
nydusify: add CLI parameter --compressor to control nydus-image
nydusify: add a parameter to change chunk size

2.1 port nydusify

---

src/bin/nydusd/fs_service.rs
src/bin/nydusd/fusedev.rs
src/bin/nydusd/virtiofs.rs

To be used by the upgrade manager.

nydusd: allow to get fusedev fsservice from fusedev daemon

---

src/bin/nydus-image/main.rs

Refine help message for create subcommand.

nydus-image: refine help message for create subcommand

---

rafs/src/metadata/layout/v6.rs
src/bin/nydus-image/builder/directory.rs
src/bin/nydus-image/builder/mod.rs
src/bin/nydus-image/builder/stargz.rs
src/bin/nydus-image/builder/tarball.rs
src/bin/nydus-image/core/blob.rs
src/bin/nydus-image/core/blob_compact.rs
src/bin/nydus-image/core/bootstrap.rs
src/bin/nydus-image/core/context.rs
src/bin/nydus-image/core/feature.rs
src/bin/nydus-image/core/node.rs
src/bin/nydus-image/main.rs
storage/src/device.rs
storage/src/meta/mod.rs

Refine code to generate image

---

README.md
contrib/nydusify/cmd/nydusify.go
contrib/nydusify/pkg/packer/backend.go
contrib/nydusify/pkg/packer/packer.go
contrib/nydusify/pkg/packer/pusher.go
contrib/nydusify/pkg/packer/pusher_test.go
docs/nydusify.md

This patch adds full support for s3 backend to all subcommands of nydusify and updates the relevant docs.
Signed-off-by: Nan Li <loheagn@icloud.com>

nydusify: full support for s3 backend

---

src/bin/nydusd/main.rs

Otherwise, it loses a window to gracefully exit
by umounting FUSE

nydusd: register signal hanlder earlier

---

contrib/nydus-test/functional-test/test_api.py

nydus-test: disable case of files iostats

---

README.md

docs: fix broken graphdriver link

---

contrib/nydus-test/framework/rafs.py
contrib/nydus-test/functional-test/test_nydus.py

nydus-test: drop a nydus-image flag backend-config

---

contrib/nydus-test/functional-test/test_nydusify.py

This partly reverts #566 to get back the chunk dict test.

nydus-test: restore chunk dict test

---

api/src/config.rs

Add unit test for configuration generated by snapshotter.

api: add unit test for configuration generated by snapshotter

---

docs/containerd-env-setup.md

docs: improve env setup doc

---

README.md
docs/nydus-zran.md

docs: add zran guide

---

rafs/src/metadata/direct_v6.rs

The directory for v6 is stored in the following way： ...name1name2
The first subdirectory we got here is ".".
When looking for some file whose ascii value is less than "." like "*", we need to move forward to the block index -1. This caused uszie's index "pirvot" to attempt to subtract with overflow and then panic.
Fixes: 50ca1a1 ("rafs: optimize entry search in rafs v6")
Signed-off-by: Huang Jianan <jnhuang@linux.alibaba.com>

rafs: fix overflow panic of rafs v6 lookup

---

Cargo.lock
api/src/config.rs
api/src/http.rs
rafs/Cargo.toml
rafs/src/metadata/layout/mod.rs
src/bin/nydus-image/builder/mod.rs
src/bin/nydus-image/core/blob.rs
src/bin/nydus-image/core/context.rs
src/bin/nydus-image/core/feature.rs
src/bin/nydus-image/main.rs
src/bin/nydusctl/commands.rs
src/bin/nydusd/fs_cache.rs
src/bin/nydusd/fs_service.rs
src/bin/nydusd/main.rs
src/bin/nydusd/service_controller.rs
src/blob_cache.rs
src/lib.rs
storage/Cargo.toml
storage/src/cache/filecache/mod.rs
storage/src/cache/fscache/mod.rs
storage/src/cache/mod.rs
storage/src/device.rs
storage/src/factory.rs
storage/src/meta/mod.rs
storage/src/meta/toc.rs

Misc code cleanup

---

contrib/nydusify/pkg/checker/checker.go
contrib/nydusify/pkg/converter/cache.go
contrib/nydusify/pkg/converter/converter.go

- nydusify: fix panic if only --target be specified
- nydusify: fix a http fallback case for build cache

nydusify: some minor fixups

---

contrib/nydusify/pkg/checker/checker.go
contrib/nydusify/pkg/converter/cache.go
contrib/nydusify/pkg/converter/converter.go

- nydusify: fix panic if only --target be specified
- nydusify: fix a http fallback case for build cache

[backport] nydusify: some minor fixups

---

storage/src/cache/cachedfile.rs

Fix a bug introduced by commit eac959f, which will cause data corruption under race conditions.
Fixes: https://github.com/dragonflyoss/image-service/issues/969

fscache: fix a bug introduced by commit eac959f

---

rafs/src/metadata/layout/v6.rs
src/bin/nydus-image/builder/mod.rs
src/bin/nydus-image/core/blob.rs
src/bin/nydus-image/core/context.rs
storage/src/cache/cachedfile.rs
storage/src/cache/mod.rs
storage/src/meta/chunk_info_v1.rs
storage/src/meta/chunk_info_v2.rs
storage/src/meta/mod.rs
storage/src/meta/toc.rs
storage/src/meta/zran.rs

Update documentation for blob meta to reflect recent changes.

storage: update documentation for blob meta to reflect recent changes

---

api/src/config.rs
rafs/src/fs.rs
rafs/src/metadata/mod.rs
src/bin/nydus-image/core/bootstrap.rs
src/bin/nydus-image/core/chunk_dict.rs
src/bin/nydus-image/core/context.rs
src/bin/nydus-image/inspect.rs
src/bin/nydus-image/main.rs
src/bin/nydus-image/merge.rs
src/bin/nydus-image/stat.rs
src/bin/nydus-image/unpack/mod.rs
src/bin/nydus-image/validator.rs
src/blob_cache.rs

Enhance the way to handle `--bootstrap` option for nydus-image

Enhance the way to handle `--bootstrap` option for nydus-image

---

src/bin/nydusd/fs_cache.rs
src/bin/nydusd/main.rs
src/bin/nydusd/service_controller.rs
src/fs_cache.rs
src/lib.rs

Refine nydusd/fscache implementation by fixing some bugs.

Refine nydusd/fscache implementation 

---

utils/Cargo.toml

Tweek Cargo.toml for powerpc64le again.

utils: tweek Cargo.toml for powerpc64le again

---

storage/src/cache/mod.rs

For old images handled with DigestedChunkMap, chunk ready state is not persistent. So it tries to read data from cache file and validate chunk digest values. So do not generate digest mismatch error messages when try to load chunk from cache files.

storage: do not generate digest mismatch messages for old images

---

.github/CODEOWNERS
.gitignore

Signed-off-by: Gaius <gaius.qi@gmail.com>

chore: add CODEOWNERS to .github

---

.github/workflows/ci.yml

To match `master` and `stable/*` branches at least.

[backport] action: fix smoke test for branch pattern

---

rafs/src/fs.rs
rafs/src/metadata/cached_v5.rs
rafs/src/metadata/direct_v5.rs
rafs/src/metadata/direct_v6.rs
rafs/src/metadata/layout/v5.rs
rafs/src/metadata/md_v5.rs
rafs/src/metadata/md_v6.rs
rafs/src/metadata/mod.rs
rafs/src/mock/mock_inode.rs
storage/src/cache/cachedfile.rs
storage/src/cache/dummycache.rs
storage/src/cache/mod.rs
storage/src/device.rs

Backport the new implementation of BlobIoChunk from master.
Fixes: https://github.com/dragonflyoss/image-service/issues/1198

storage: refine the way to implement BlobIoChunk
