rafs/src/metadata/layout.rs
rafs/src/storage/backend/localfs.rs

Using sort_unstable instead of sort for primitive type will get better performance.

Fix clippy error of using sort_unstable instead of sort

---

README.md
docs/nydusd.md

* fix `compactible` typo
* add qemu and virtio-fs links
* mention cloud-hypervisor support

docs: a few improvements

---

docs/nydusd.md

- Keep `backend` and `cache` fields in `device`, move other fields to outside;
- Fix incorrect JSON syntax rendering for Github markdown;

Fix: incorrect nydusd config

---

contrib/nydusify/remote/remote.go

If the image includes an empty platform manifest, nydusify will panic on
conversion, check this situation to avoid.

nydusify: fix conversion for the image included empty platform

---

.travis.yml

As travis reports, it is deprecated and has no effects.

travis: drop sudo tag

---

utils/src/fuse.rs

With cargo 1.48.0 (65cbdd2dc 2020-10-14) and rustc 1.48.0 (7eac88abb 2020-11-16):
--> utils/src/fuse.rs:269:9
|
269 |         fstype.push_str(".");
|         ^^^^^^^^^^^^^^^^^^^^ help: consider using `push` with a character literal: `fstype.push('.')`
|
= note: `-D clippy::single-char-push-str` implied by `-D clippy::all`
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#single_char_push_str
Closes #27

utils: fix push_str clippy warnning

---

misc/smoke/Dockerfile

This changes to use crates.io to avoid any failure in CI.

build: use crates.io

---

src/bin/nydus-image/node.rs
src/bin/nydus-image/tree.rs

When compiling source code with lower version rust, failure may occur with error "u64::MAX associated item not found in u64".
Using full path std::u64::MAX will be OK.
Fixes: #26
Signed-off-by: LiYa'nan <oliverliyn@gmail.com>

nydus-image: fix rustlang backward compatibility issues

---

contrib/nydusify/cmd/nydusify.go
contrib/nydusify/converter/converter.go
contrib/nydusify/registry/registry.go

Add `--source-insecure` and `--target-insecure` options for Nydusify,
instead of getting HTTP scheme automatically according to url.

Nydusify: fix insecure registry endpoint access

---

Cargo.lock

To bring in bugfix and 3.10 kernel compatibility.

Cargo: update fuse-backend-rs dependency

---

.travis.yml

Use a fixed rust version in the CI environment to make testing stable,
we can move forward once decided to upgrade the rust version in project.
Fix CI issue on #36 

CI: use rust 1.47.0 environment

---

Cargo.lock
api/Cargo.toml

Mirco-http was forked into Cloud Hypersior. Nydus relies on mirco-http
to implement Api server. After the fork, it now supports more http methods.

cargo: change micro-http dependency to Cloud Hypervisor organization

---

docs/containerd-env-setup.md
misc/example/containerd-entrypoint.sh

`--shared-daemon` is not working due to API incompatibility.
Let's use standalone mode for now until that is fixed.
issue #44

example: use standalone nydusd mode

---

utils/src/fuse.rs

fuse-rs replies INIT with max write 1MB and 256 pages. We should honor
it when preparing fuse request buffer otherwise newer kernel would just
reject sys_read on /dev/fuse.
Fixes: #41

fuse: increase FUSE_KERN_BUF_SIZE

---

.github/workflows/ci.yml

So that we can move away from travis.
This works as can be seen at https://github.com/bergwolf/image-service/actions/runs/515353337

ci: add github action CI

---

contrib/nydus-snapshotter/cmd/containerd-nydus-grpc/app/snapshotter/main.go
contrib/nydus-snapshotter/cmd/containerd-nydus-grpc/app/snapshotter/validate.go
contrib/nydus-snapshotter/cmd/containerd-nydus-grpc/app/snapshotter/validate_test.go
contrib/nydus-snapshotter/cmd/containerd-nydus-grpc/main.go
contrib/nydus-snapshotter/go.mod
contrib/nydus-snapshotter/pkg/auth/keychain.go
contrib/nydus-snapshotter/pkg/auth/keychain_test.go
contrib/nydus-snapshotter/pkg/daemon/daemon.go
contrib/nydus-snapshotter/pkg/filesystem/nydus/config.go
contrib/nydus-snapshotter/pkg/filesystem/nydus/daemonconfig.go
contrib/nydus-snapshotter/pkg/filesystem/nydus/fs.go
contrib/nydus-snapshotter/pkg/filesystem/stargz/config.go
contrib/nydus-snapshotter/pkg/filesystem/stargz/fs.go
contrib/nydus-snapshotter/pkg/filesystem/stargz/fs_test.go
contrib/nydus-snapshotter/pkg/filesystem/stargz/resolver_test.go
contrib/nydus-snapshotter/pkg/nydussdk/client.go
contrib/nydus-snapshotter/pkg/nydussdk/client_test.go
contrib/nydus-snapshotter/pkg/process/manager.go
contrib/nydus-snapshotter/pkg/process/store.go
contrib/nydus-snapshotter/pkg/signature/signature.go
contrib/nydus-snapshotter/pkg/store/store.go
contrib/nydus-snapshotter/snapshot/snapshot.go

Shorten go module name to `contrib/nydus-snapshotter`, it's still compilable.

Snapshotter: shorten go module name

---

rafs/src/storage/backend/localfs.rs
rafs/src/storage/backend/mod.rs

This PR fixes two issues
- only use backends when the backend feature is on, otherwise build would fail due to un-imported crates.
- initialize localfs backend's metrics when blob file is specified in config as well

rafs: backend related fixes

---

api/src/http_endpoint.rs
rafs/src/fs.rs
rafs/src/metadata/cached.rs
rafs/src/metadata/direct.rs
rafs/src/metadata/mod.rs
rafs/src/storage/backend/oss.rs
rafs/src/storage/backend/registry.rs
rafs/src/storage/device.rs
src/bin/nydus-image/tree.rs

From 1.50, looks like clippy starts to complain about unnecessary Resuler wrapper.
For example:
error: this function's return value is unnecessarily wrapped by `Result`
--> rafs/src/metadata/cached.rs:105:5
|
105 | /     fn add_into_parent(&mut self, child_inode: Arc<CachedInode>) -> Result<()> {
106 | |         if let Ok(parent_inode) = self.get_node_mut(child_inode.parent()) {
107 | |             Arc::get_mut(parent_inode)
108 | |                 .unwrap()
...   |
111 | |         Ok(())
112 | |     }
| |_____^
|

nydus: silent clippy warnings against nightly-1.50

---

contrib/nydusify/nydus/builder.go
src/bin/nydus-image/builder.rs
src/bin/nydus-image/main.rs

Previously, when converting image, a prefetch list is input to
builder from stdin, which is later persisted to bootstrap prefetch
table.
During parsing the prefetch table, builder checks file's existance.
But for layered building, we can't guarantee that the source directory
of parent boostrap is located from local file system.
So builder no longger accecpts abosolute paths, but relative paths to
source rootfs.
It must start with "/"

rafs/prefetch: fix prfetch outage with layered image building

---

misc/smoke/Dockerfile

No need to replace crates.io source when perform smoke within github action. This will reduce smoke test duration.

docker: no need to replace crates.io source to tuna

---

src/bin/nydus-image/main.rs
src/bin/nydus-image/validator.rs

Add `--output-json` option for check subcommand, use it for Nydusify
image checker to get blob ids from bootstrap, and compare with the blob
ids recorded in Nydus image manifest, to ensure the image validity.

Builder: support --output-json for check subcommand

---

Cargo.lock
Cargo.toml
src/bin/nydus-image/main.rs
src/bin/nydusd/main.rs
tests/builder.rs
tests/nydusd.rs
tests/smoke.rs
utils/Cargo.toml
utils/src/lib.rs

Nydusd now can log both to standard error and specified logging file. Just specify the logging file by adding option `--log-file` when nydusd starts

Change logger from stderrlog to flexi_logger

---

rafs/src/io_stats.rs
rafs/src/storage/backend/oss.rs
rafs/src/storage/backend/registry.rs
rafs/src/storage/cache/blobcache.rs
rafs/src/storage/cache/mod.rs
src/bin/nydus-image/builder.rs
src/bin/nydus-image/main.rs
src/bin/nydus-image/node.rs
src/bin/nydus-image/tree.rs

Sometimes, chunks are better to put into blobcache with
4k aligned, which makes advanced usage more convenient.
When filling local blobcache file, chunks are arranged per
as to the `decompress offset` within chunk info. Therefore,
provide a new flag to image tool thus to align chunks in blob
with 4k size.

image: add a flag controlling chunk size's alignment

---

.github/workflows/release.yml
misc/musl-static/Dockerfile
misc/smoke/Dockerfile

To automatically build and upload static binaries upon release tag
push events.
When we push a new tag like `v10.10.10`, the action would build static binaries and create a new release like https://github.com/bergwolf/image-service/releases/tag/v10.10.10
Example run:
https://github.com/bergwolf/image-service/actions/runs/657438261

github: add github release action

---

contrib/nydus-snapshotter/cmd/containerd-nydus-grpc/app/snapshotter/main.go
contrib/nydus-snapshotter/export/snapshotter/snapshotter.go
contrib/nydus-snapshotter/go.mod
contrib/nydus-snapshotter/pkg/daemon/config.go
contrib/nydus-snapshotter/pkg/daemon/daemon.go
contrib/nydus-snapshotter/pkg/filesystem/nydus/config.go
contrib/nydus-snapshotter/pkg/filesystem/nydus/fs.go
contrib/nydus-snapshotter/pkg/filesystem/stargz/config.go
contrib/nydus-snapshotter/pkg/filesystem/stargz/fs.go
contrib/nydus-snapshotter/pkg/filesystem/stargz/fs_test.go
contrib/nydus-snapshotter/pkg/nydussdk/client.go
contrib/nydus-snapshotter/pkg/process/manager.go
contrib/nydus-snapshotter/pkg/process/store.go
contrib/nydus-snapshotter/pkg/store/database.go
contrib/nydus-snapshotter/pkg/store/database_test.go
contrib/nydus-snapshotter/pkg/store/store.go

This patch set includes fixes as below:
- persist daemon info in database, so that snapshotter can reconnect to running daemons;
- output daemon's log to daemon's own log file;
-  umount daemon with API when daemon in shared mode.
Signed-off-by: 慕陶 <jihui.xjh@antfin.com>
Signed-off-by: Eric Ren <renzhen@linux.alibaba.com>

Support snapshotter reconnect to already running daemons

---

Cargo.lock
api/Cargo.toml
api/src/http.rs
api/src/http_endpoint.rs
src/bin/nydusd/api_server_glue.rs

Returning http status code 404 to clients is more suggestive and friendly to users.

Return 404 if resource can't be found

---

contrib/nydus-snapshotter/cmd/containerd-nydus-grpc/app/snapshotter/main.go
contrib/nydus-snapshotter/cmd/containerd-nydus-grpc/main.go
contrib/nydus-snapshotter/cmd/containerd-nydus-grpc/pkg/command/flags.go
contrib/nydus-snapshotter/config/config.go
contrib/nydus-snapshotter/export/snapshotter/snapshotter.go
contrib/nydus-snapshotter/go.mod
contrib/nydus-snapshotter/pkg/auth/keychain.go
contrib/nydus-snapshotter/pkg/auth/keychain_test.go
contrib/nydus-snapshotter/pkg/daemon/daemon.go
contrib/nydus-snapshotter/pkg/filesystem/nydus/config.go
contrib/nydus-snapshotter/pkg/filesystem/nydus/daemonconfig.go
contrib/nydus-snapshotter/pkg/filesystem/nydus/fs.go
contrib/nydus-snapshotter/pkg/filesystem/stargz/config.go
contrib/nydus-snapshotter/pkg/filesystem/stargz/fs.go
contrib/nydus-snapshotter/pkg/filesystem/stargz/fs_test.go
contrib/nydus-snapshotter/pkg/filesystem/stargz/resolver_test.go
contrib/nydus-snapshotter/pkg/nydussdk/client.go
contrib/nydus-snapshotter/pkg/nydussdk/client_test.go
contrib/nydus-snapshotter/pkg/process/manager.go
contrib/nydus-snapshotter/pkg/process/store.go
contrib/nydus-snapshotter/pkg/signature/signature.go
contrib/nydus-snapshotter/pkg/store/database.go
contrib/nydus-snapshotter/pkg/store/store.go
contrib/nydus-snapshotter/snapshot/snapshot.go

Current snapshotter module name makes it hard to be imported to
other projects like containerd.
So rename it

snapshotter: rename snapshotter name to be easily imported

---

.github/workflows/release.yml

And make sure they have executable bits set. It seems that actions/upload-artifact
action drops the executable bits.

action: save all static binaries in top directory

---

contrib/nydusify/cmd/nydusify.go
contrib/nydusify/pkg/checker/checker.go
contrib/nydusify/pkg/checker/rule/manifest.go
contrib/nydusify/pkg/converter/converter.go
contrib/nydusify/pkg/converter/manifest.go
contrib/nydusify/pkg/converter/provider/source.go
contrib/nydusify/pkg/parser/parser.go
contrib/nydusify/pkg/utils/utils.go

**Nydusify: add default platform to existed oci manifest**
```
Add default platform "linux/amd64" to existed manifest in
remote registry if pushing Nydus image as a manifest index
(multi-platform enabled), so that docker/containerd can
distinguish OCI and Nydus image using the platform field
in the manifest index.
```
**Nydusify: support --multi-platform option for checker**
```
Ensure target image represents as a manifest list, and it consists
of OCI and Nydus manifest, if the "--multi-platform" option of checker
be specified.
```

Nydusify: add default platform to existed oci manifest

---

src/bin/nydusd/main.rs

So that we can start nydusd with an initial fs backend and still be able
to attach more fs backends to it later on.

nydusd: add virtual mountpoint commandline option

---

contrib/nydus-snapshotter/snapshot/snapshot.go

The image registry auth are included in the labels:
- containerd.io/snapshot/pullsecret:***
- containerd.io/snapshot/pullusername:***
Signed-off-by: Eric Ren <renzhen@linux.alibaba.com>

snapshotter: do not print snapshot labels

---

src/bin/nydus-image/builder.rs
src/bin/nydus-image/main.rs
src/bin/nydus-image/node.rs
src/bin/nydus-image/trace.rs
src/bin/nydus-image/tree.rs

Nydus-image builder tracer wrongly sets its initial value to  0 ending up with smaller counters recorded.
Moreover, add UT for image tracer.

Improve and fix nydus-image building tracer

---

contrib/nydus-snapshotter/cmd/containerd-nydus-grpc/pkg/command/flags.go
contrib/nydus-snapshotter/config/config.go
contrib/nydus-snapshotter/snapshot/snapshot.go

Defaults to disable stargz fs support so that we
can avoid some unnecessary checking.
Signed-off-by: Eric Ren <renzhen@linux.alibaba.com>

snapshotter: introduce enable stargz option

---

api/src/http_endpoint.rs
contrib/nydus-snapshotter/cmd/containerd-nydus-grpc/pkg/command/flags.go
contrib/nydus-snapshotter/config/config.go
contrib/nydus-snapshotter/config/daemonconfig.go
contrib/nydus-snapshotter/config/daemonconfig_test.go
contrib/nydus-snapshotter/pkg/daemon/config.go
contrib/nydus-snapshotter/pkg/daemon/daemon.go
contrib/nydus-snapshotter/pkg/filesystem/fs/fs.go
contrib/nydus-snapshotter/pkg/filesystem/nydus/config.go
contrib/nydus-snapshotter/pkg/filesystem/nydus/daemonconfig.go
contrib/nydus-snapshotter/pkg/filesystem/nydus/fs.go
contrib/nydus-snapshotter/pkg/filesystem/stargz/config.go
contrib/nydus-snapshotter/pkg/filesystem/stargz/fs.go
contrib/nydus-snapshotter/pkg/metric/exporter/export.go
contrib/nydus-snapshotter/pkg/metric/exporter/metrics.go
contrib/nydus-snapshotter/pkg/metric/exporter/registry.go
contrib/nydus-snapshotter/pkg/metric/exporter/types.go
contrib/nydus-snapshotter/pkg/metric/serve.go
contrib/nydus-snapshotter/pkg/process/manager.go
contrib/nydus-snapshotter/pkg/store/store.go
contrib/nydus-snapshotter/snapshot/snapshot.go
rafs/src/fs.rs
rafs/src/metadata/mod.rs
storage/src/factory.rs

This PR mainly brings the secure-container support to nydus-snapshotter, which introduces a new "none" instance mode, and snapshotter returns the rafs bootstrap file instead of a mounted rafs dir, so that secure-container such as kata-containers could parse the bootstrap file directly.

Introduce secure-container support to nydus-snapshotter and various bug fixes

---

contrib/nydus-snapshotter/pkg/process/manager.go

There are two process wait, when destroy daemon, if first wait function run first, the second wait function will fail and output error as below. It is happened occasionally.
1. https://github.com/dragonflyoss/image-service/blob/v0.1.0/contrib/nydus-snapshotter/pkg/process/manager.go#L124
2. https://github.com/dragonflyoss/image-service/blob/v0.1.0/contrib/nydus-snapshotter/pkg/process/manager.go#L188
The other question is here why not use p.Signal(syscall.SIGTERM) to gracefully exit?  p.Kill() will kill -9.
https://github.com/dragonflyoss/image-service/blob/v0.1.0/contrib/nydus-snapshotter/pkg/process/manager.go#L184

fix nydusd daemon process double wait and change p.Kill() to     p.Signal(syscall.SIGTERM) when destroy nydusd daemon process

---

contrib/nydus-snapshotter/pkg/filesystem/nydus/fs.go
contrib/nydus-snapshotter/pkg/process/manager.go
contrib/nydus-snapshotter/pkg/process/store.go
contrib/nydus-snapshotter/pkg/store/daemonstore.go
contrib/nydus-snapshotter/pkg/store/database.go
docs/containerd-env-setup.md

As boltdb is shared by daemon and snapshot/blob, so it is not
suitable for method name CleanupDatabase when cleanup daemons
Signed-off-by: luodaowen.backend <luodaowen.backend@bytedance.com>

snapshotter: change CleanupDatabase to CleanupDaemons

---

contrib/nydus-snapshotter/config/config.go

Otherwise containerd failed to start due to failure to create new cache
manager.
panic: non-positive interval for NewTicker
goroutine 138 [running]:
time.NewTicker(0x0, 0x0)
/home/eryu.gey/workspace/go/src/time/tick.go:23 +0x151
github.com/dragonflyoss/image-service/contrib/nydus-snapshotter/pkg/cache.(*Manager).runGC(0xc000419080)
/home/eryu.gey/workspace/src/go/src/github.com/containerd/containerd/vendor/github.com/dragonflyoss/image-service/contrib/nydus-snapshotter/pkg/cache/manager.go:54 +0x56
created by github.com/dragonflyoss/image-service/contrib/nydus-snapshotter/pkg/cache.NewManager
/home/eryu.gey/workspace/src/go/src/github.com/containerd/containerd/vendor/github.com/dragonflyoss/image-service/contrib/nydus-snapshotter/pkg/cache/manager.go:40 +0x171
Signed-off-by: Eryu Guan …

snapshotter: set default GCPeriod if not set in config

---

contrib/nydus-snapshotter/config/daemonconfig.go

Currently, nydus snapshotter assumes the backend is registry, as
NewDaemonConfig() doesn't check backend type and always set 'Host',
'Repo' and 'Auth' fields that are only useful for registry backend.
So add oss and localfs backend configs to Backend config as well, so
images with such backends could be used correctly.
Signed-off-by: Eryu Guan <eguan@linux.alibaba.com>

snapshotter: support oss and localfs backend as well

---

api/openapi/nydus-rs.yaml

Openapi code generator throw errors out as below:
Exception in thread "main" org.openapitools.codegen.SpecValidationException: There were issues with the specification. The option can be disabled via validateSpec (Maven/Gradle) or --skip-validate-spec (CLI).
| Error count: 3, Warning count: 2
Errors:
-attribute paths.'/metrics/files'(get).responses.200.content.'application/json'.schema.other is unexpected
-attribute paths.'/metrics/files'(get).parameters.[latest].desciption is unexpected
-attribute paths.'/metrics/files'(get).responses.200.content.'application/json'.schema.latest is unexpected
Warnings:
-attribute paths.'/metrics/files'(get).responses.200.content.'application/json'.schema.other is unexpected
-attribute paths.'/metrics/files'(get).parameters.[latest].desciption is …

openapi: fix openapi yaml grammer mistake

---

contrib/nydusify/cmd/nydusify.go
contrib/nydusify/pkg/backend/backend.go
contrib/nydusify/pkg/backend/oss.go
contrib/nydusify/pkg/backend/registry.go
contrib/nydusify/pkg/converter/converter.go
contrib/nydusify/pkg/converter/layer.go

The race happens when a single blob has a large size, when nydusify tries to upload blob to OSS in a manner of `multiparts`.
As `append` is not atomic in golang, the regression is introduced.
To fix existed images, add an option to nydusify to push blob forcefully, no matter it exists of not.

Close a race happening when nydusify pushes blob to OSS.

---

Cargo.lock
Cargo.toml
rafs/src/fs.rs
rafs/src/metadata/cached.rs
rafs/src/metadata/extended/blob_table.rs
rafs/src/metadata/layout.rs
rafs/src/metadata/mod.rs
src/bin/nydus-image/builder/directory.rs
src/bin/nydus-image/builder/stargz.rs
src/bin/nydus-image/core/blob.rs
src/bin/nydus-image/core/bootstrap.rs
src/bin/nydus-image/core/node.rs
src/bin/nydus-image/main.rs
src/bin/nydusd/api_server_glue.rs
storage/src/cache/blobcache.rs
storage/src/cache/chunkmap/digested.rs
storage/src/cache/chunkmap/indexed.rs
storage/src/cache/dummycache.rs
storage/src/cache/mod.rs
storage/src/device.rs
utils/src/digest.rs

As shared chunk bitmap file is already introduced, in which 1 bit of value 1 indicates that a chunk is successfully downloaded.
Rafs/prefetch no longer has to validate the whole chunk by calculating its sha256, but just to probe if the corresponding it is ever set. This will save unnecessary read from disk.
More over try to deduce locking contention to improve performance.

improve blobcache and rafs prefetch

---

contrib/nydusify/cmd/nydusify.go
contrib/nydusify/go.mod
contrib/nydusify/go.sum
contrib/nydusify/pkg/backend/oss.go
contrib/nydusify/pkg/build/workflow.go
contrib/nydusify/pkg/converter/build_info.go
contrib/nydusify/pkg/converter/converter.go
contrib/nydusify/pkg/converter/manifest.go
src/bin/nydus-image/main.rs
utils/src/lib.rs

It will be safer if we can verify the blob's crc64 returned from OSS after it is uploaded.

Verify blob's crc64 after it is uploaded

---

contrib/nydus-snapshotter/config/daemonconfig.go
contrib/nydus-snapshotter/pkg/cache/store.go

Two commits, actually:
**Snapshotter: remove chunkmap file in blob GC**
Nydusd now supports a bitmap-based chunk ready state sharing
capability called chunkmap, which should be deleted before
the blob file is deleted during the GC process.
**Snapshotter: add PrefetchAll config in DaemonConfig**
We introduced 'prefetch_all' option to control if nydus should prefetch
all blobs in background. So add this option to snapshotter, that we
could enable/disable it.

Snapshotter: remove chunkmap file in blob GC

---

rafs/src/fs.rs
rafs/src/metadata/cached.rs
rafs/src/metadata/direct.rs
rafs/src/metadata/layout.rs
rafs/src/metadata/mod.rs
src/bin/nydus-image/builder/stargz.rs
src/bin/nydus-image/core/node.rs
src/bin/nydus-image/inspect.rs

Two commits, actually:
**Prefetch: fix overlapped prefetch merge requests**
The left chunks whose size is smaller than 4MB will be fetched
after 4MB merge requests.
**Rafs: add ctime support**
Save ctime in inode and use it for ctime/mtime/atime.
There are applications that might check ctime/mtime so
we cannot just drop it and use runtime system time as ctime.

Prefetch: fix overlapped prefetch merge requests

---

contrib/nydus-snapshotter/Makefile
contrib/nydusify/Makefile

Enhance Makefiles to support GOPROXY, so we could use
make GOPROXY=xxxx

contrib: enhance Makefile to support GOPROXY

---

rafs/src/fs.rs
rafs/src/metadata/cached.rs
rafs/src/metadata/direct.rs
rafs/src/metadata/layout.rs
src/bin/nydus-image/builder/stargz.rs
src/bin/nydus-image/core/node.rs
src/bin/nydus-image/inspect.rs

The modified timestamp (mtime) signifies the last time the contents
of a file were modified. A program or process either edited or
manipulated the file. “Modified” means something inside the file was
amended or deleted, or new data was added.
The changed timestamps aren’t referring to changes made to the contents
of a file. Rather, it’s the time at which the metadata related to the
file was changed. File permission changes, for example, will update the
changed timestamp.
So the rafs metadata should record `mtime` instead of `ctime` because
`mtime` is often used to detect content change.

rafs: use mtime instead of ctime

---

contrib/nydus-snapshotter/config/daemonconfig.go
docs/nydusd.md
storage/src/backend/registry.rs

When using registry backend, blob data may be stored on other storages,
such as OSS, and registry will redirect download request to URL pointing
to such storage, so backend downloads blob file from there.
But this redirected link might not be optimal, e.g. we may want to use
OSS cache endpoint. So introduce a new 'blob_redirected_host' config
option in Registry backend config, and replace the redirected blob url
from registry with this user-defined host to have better performance.
Signed-off-by: Eryu Guan <eguan@linux.alibaba.com>

storage: add ability to use user-defined blob redirected host

---

contrib/nydus-snapshotter/config/config.go
contrib/nydus-snapshotter/pkg/daemon/config.go
contrib/nydus-snapshotter/pkg/daemon/daemon.go
contrib/nydus-snapshotter/pkg/filesystem/fs/fs.go
contrib/nydus-snapshotter/pkg/filesystem/nydus/config.go
contrib/nydus-snapshotter/pkg/filesystem/nydus/fs.go
contrib/nydus-snapshotter/pkg/process/manager.go
contrib/nydus-snapshotter/snapshot/snapshot.go

When using snapshotter "none" daemon mode, rafs will be mounted at
container start time, as there's no nydusd daemon and rafs couldn't be
mounted at snapshot creation time, so prefetch won't be started until
rafs is mounted. This slows down the prefetch performance.
So introduce a new "prefetch" daemon mode, which is almost the same as
"none" daemon mode, the only difference is "prefetch" mode will start a
nydusd in shared mode and mounts the rafs at snapshot creation time, so
that starts prefetch earlier.
Signed-off-by: Eryu Guan <eguan@linux.alibaba.com>

snapshotter: introduce "prefetch" daemon mode to do prefetch for none daemon mode

---

contrib/nydus-snapshotter/Makefile
contrib/nydus-snapshotter/cmd/containerd-nydus-grpc/pkg/command/flags.go
contrib/nydus-snapshotter/config/config.go
contrib/nydus-snapshotter/pkg/daemon/config.go
contrib/nydus-snapshotter/pkg/daemon/daemon.go
contrib/nydus-snapshotter/pkg/filesystem/nydus/config.go
contrib/nydus-snapshotter/pkg/filesystem/nydus/fs.go
contrib/nydus-snapshotter/pkg/filesystem/stargz/config.go
contrib/nydus-snapshotter/pkg/filesystem/stargz/fs.go
contrib/nydus-snapshotter/pkg/process/manager.go
contrib/nydus-snapshotter/snapshot/snapshot.go

pass corresponding log level to nydusd, so it will not always be info.
related issue https://github.com/dragonflyoss/image-service/issues/145
Signed-off-by: yuhongqi <yuhongqi@bytedance.com>

contrib: pass log level from snapshotter to nydusd

---

contrib/nydus-snapshotter/pkg/process/manager.go
contrib/nydus-snapshotter/pkg/process/store.go
contrib/nydus-snapshotter/pkg/store/daemonstore.go
contrib/nydus-snapshotter/pkg/store/database.go

So that the pid is not zero after snapshotter restarts.

snapshotter: save daemon pid after starting it

---

contrib/nydus-snapshotter/pkg/store/database.go

using updateObject not putObject which will cause error due to duplicate key.
related pr https://github.com/dragonflyoss/image-service/pull/154
Signed-off-by: yuhongqi <yuhongqi@bytedance.com>

Contrib: fix update daemon

---

storage/src/cache/blobcache.rs
storage/src/cache/chunkmap/digested.rs
storage/src/cache/chunkmap/indexed.rs
storage/src/cache/chunkmap/mod.rs
storage/src/lib.rs

If there is already a backend IO going fetching a chunk from remote storage. Blobcache does not have to issue another one for the same data chunk. Waiting is an ideal behavior saving backend width and reduce IO latency.
When there is several big files residing in Rafs, sequential read will gain performance profit.

Blobcache handles single inflight backend IO

---

src/bin/nydus-image/core/tree.rs
src/bin/nydus-image/inspect.rs
src/bin/nydus-image/main.rs

Now we can inspect rafs layout through tool `nydus-image inspect` more conveniently.
It can 
1. list all files that are sharing the same chunk
2. print more detailed information of a chunk
3. look up a file by its inode number

Enhance rafs inspector

---

Cargo.lock
storage/Cargo.toml
storage/src/cache/blobcache.rs
storage/src/cache/dummycache.rs
storage/src/cache/mod.rs

Let persisting chunk to blobcache file happen at the same time with responding to user IO request.
This will reduce read io latency when local disk is in a heavy workload.

Async blobcache persister

---

utils/src/fuse.rs

So that suid can take effect and programes like sudo and passwd can
still work on nydus rootfs.

fuse: drop MS_NOSUID

---

src/bin/nydus-image/core/blob.rs
src/bin/nydus-image/core/prefetch.rs

In rafs disk layout, we should enforce a rule that chunks
are dumped/written to blob file according to order of inode
number.
When prefetch files list is specified, e.g. "/", the specified
files will be dumped before dumping other files. But the `readahead_files`
collection is not sorted by its key - inode index.
So fix this by sorting it before consuming it.
This problem might affect prefetch merging possibility.

nydus-image: fix disorder of writing chunks to blob

---

storage/src/cache/blobcache.rs
storage/src/cache/dummycache.rs
storage/src/cache/mod.rs

For stargz blobcache, each member file is cacned as gzip reg/chunk.
Now, blobcache stores decompessed data into blobcache, which later
can't be decompressed.
Error message follows:
[2021-08-20 16:19:27.004643 +08:00] ERROR [storage/src/cache/mod.rs:195] failed to decompress chunk: invalid gzip header
[2021-08-20 16:19:27.079728 +08:00] ERROR [storage/src/cache/mod.rs:195] failed to decompress chunk: invalid gzip header
[2021-08-20 16:19:27.084288 +08:00] ERROR [storage/src/cache/mod.rs:195] failed to decompress chunk: invalid gzip header
[2021-08-20 16:19:27.088826 +08:00] ERROR [storage/src/cache/mod.rs:195] failed to decompress chunk: invalid gzip header
[2021-08-20 16:19:27.102827 +08:00] ERROR [storage/src/cache/mod.rs:195] failed to decompress chunk: invalid gzip header
[2021-08-20 …

blobcache/stargz: fix stargz gzip member can't be cached

---

contrib/nydusify/cmd/nydusify.go
contrib/nydusify/pkg/build/builder.go
contrib/nydusify/pkg/build/workflow.go
contrib/nydusify/pkg/converter/build_info.go
contrib/nydusify/pkg/converter/converter.go
contrib/nydusify/pkg/converter/layer.go
contrib/nydusify/pkg/parser/parser.go

Add a new option to produce 4096 aligned decompressed_offset in a converted nydus image bootstrap, so that when blobcache backend is in use, we can end up with a blob file in which the offset of chunks are aligned to 4K.
In the buildkit environment, the source manifest may be empty because the source image is built from a Dockerfile.
Parser parses manifest list by specified image reference, Prior to this patch, Parser would return immediately after parsing the OCI manifest, causing the checker to never find the Nydus manifest

Nydusify supports option --aligned and a couple of bugfixes

---

contrib/nydus-snapshotter/cmd/containerd-nydus-grpc/pkg/command/flags.go
contrib/nydus-snapshotter/config/config.go
contrib/nydus-snapshotter/pkg/daemon/config.go
contrib/nydus-snapshotter/pkg/daemon/daemon.go
contrib/nydus-snapshotter/pkg/filesystem/nydus/fs.go
contrib/nydus-snapshotter/pkg/filesystem/stargz/fs.go
contrib/nydus-snapshotter/snapshot/snapshot.go

In some cases we don't want cache manager to do blob cache gc for us,
so introduce a new 'disable_cache_manager' config to run snapshotter
without cache manager.

Snapshotter can be configured to  disable cache manager

---

contrib/nydus-snapshotter/pkg/filesystem/stargz/fs_test.go
contrib/nydus-snapshotter/pkg/store/database.go
contrib/nydus-snapshotter/pkg/store/database_test.go

Snapshotter's test went insane for a long time. It is majorly caused by redefine some structs. Fix it in the PR.

Snapshotter recover test

---

contrib/nydusify/go.mod
contrib/nydusify/pkg/utils/archive.go
rafs/src/fs.rs

When rafs root inode has permission bits of 0750, other user can 't list the root dir. It may cause container insane that it can't change user.
So give the root directory of permission 0755 when converting image.
Moreover, during runtime, let rafs return 0755 for access() so we don't have to re-convert images.

Fix rafs root permission wongely set to 0750

---

Cargo.toml
Makefile
misc/nydus-smoke/Dockerfile
tests/builder.rs
tests/nydusd.rs

Now makefile uses both gnu and musl targets and compile for virtiofs feature of static. This is not necessary.

Improve Makefile by trimming unnecessary steps and try to re-use same targets

---

Makefile
rafs/src/fs.rs
rafs/src/metadata/cached_v5.rs
rafs/src/metadata/direct_v5.rs
rafs/src/metadata/layout/v5.rs
rafs/src/metadata/mod.rs
storage/src/backend/localfs.rs
storage/src/backend/mod.rs
storage/src/cache/blobcache.rs
storage/src/cache/chunkmap/indexed.rs
storage/src/cache/chunkmap/mod.rs
storage/src/cache/dummycache.rs
storage/src/cache/mod.rs
storage/src/device.rs
storage/src/lib.rs
storage/src/utils.rs
utils/src/metrics.rs

Currently, rafs can only handle a bio/chunk down to blob layer. In case a target file range spans multiple chunks, it is clumsy and low efficiency.
Fetching data from backend for size smaller than 128KB takes similar time, so we introduce a feature to amplify user io to fetch more data from backend and store ti into blob cache to boost following rafs read.
From benchmark, with 1000 files of 8K size, read latency had decreased by 50%.

Multiple chunks based rafs read path and user io amplification

---

Cargo.lock
Cargo.toml

Upgrage dependent crates rust-fsm, reqwest to get rid of duplicated
crates: bytes, proc-macro2, quote, syn, httpdate.

Get rid of duplicated dependent crates

---

Cargo.lock
Cargo.toml
api/src/http.rs
rafs/src/fs.rs
src/bin/nydusctl/client.rs
src/bin/nydusctl/commands.rs
src/bin/nydusctl/main.rs
src/bin/nydusd/api_server_glue.rs
src/bin/nydusd/daemon.rs
src/bin/nydusd/main.rs
src/lib.rs

`nydusctl` is a newly added executive binary.
It communicates with `nydusd` via HTTP API over UDS. It can
- show nydusd work status
- export io metrics to user 
- configure nydusd dynamically.

Introduce nydusd - a tool to query nydusd working status

---

api/openapi/nydus-rs.yaml
api/src/http_endpoint.rs
src/bin/nydusctl/client.rs
src/bin/nydusctl/commands.rs
src/bin/nydusctl/main.rs
storage/src/cache/blobcache.rs
utils/src/metrics.rs

Let CLI tool `nydusctl` print more debug/trace information exported from nydusd
Trim unused metircs.
Fix a bug that error message from nydusd http response body can't be parsed.

Improve nydusctl CLI tool

---

contrib/nydus-snapshotter/pkg/process/manager.go

When nydus-snapshotter restart, it will break the relationship between nydusd and
nydus-snapshotter, so p.Wait() will return err. This pr fix the err by judge the err type
Signed-off-by: luodaowen.backend <luodaowen.backend@bytedance.com>

fix(nydus-snapshotter): fix p.Wait() return err when destroy nydusd

---

Cargo.lock
Cargo.toml
app/build.rs

App version has a part of git commit id. But it only changes when `nydus-app` crate has to be re-compiled. So when perform `nydusd --version`, the output git commit id might not be the HEAD commit id.

Fix app version

---

rafs/src/fs.rs

We need to set it for lookup and readdir as well so that it is
consistent with getattr.

rafs: fix root inode permission for lookup and readdir

---

contrib/nydus-snapshotter/.golangci.yml
contrib/nydus-snapshotter/Makefile
contrib/nydus-snapshotter/cmd/containerd-nydus-grpc/pkg/logging/setup.go

1. Use `golangci-lint` tool to perform static check to get code neater
2. Don't use json format log for snapshotter anymore since it is not friendly for human read and debug

Small improvement for snapshotter

---

api/src/http_endpoint.rs
src/bin/nydusctl/client.rs
src/bin/nydusctl/commands.rs
src/bin/nydusctl/main.rs
src/bin/nydusd/api_server_glue.rs

nydusctl as a nydusd client send HTTP API to nydusd to command it attach one or more rafs banckends.
It can also detach the rafs backend it just attached.

nydusctl can command nydusd to attach a rafs backend

---

Cargo.toml
rafs/Cargo.toml
rafs/src/fs.rs
rafs/src/metadata/cached_v5.rs
rafs/src/metadata/layout/mod.rs
rafs/src/metadata/mod.rs
rafs/src/mock/mock_inode.rs
src/bin/nydusd/daemon.rs
src/bin/nydusd/fusedev.rs
src/bin/nydusd/main.rs
src/bin/nydusd/virtiofs.rs
storage/Cargo.toml
storage/src/device.rs
utils/Cargo.toml
utils/src/fuse.rs

fuse-rs crate has changed its package name to fuse-backend-rs,
in order to keep consistent with it and reduce code confliction
when pushing patches from different repositories, we import
dependency by its alias.

nydus: depend on an alias of fuse_rs - fuse_backend_rs

---

contrib/nydus-snapshotter/config/daemonconfig.go
contrib/nydus-snapshotter/pkg/auth/keychain.go
contrib/nydus-snapshotter/pkg/auth/keychain_test.go

Nydusd must pull data from registry with auth if the repo is private.
Snapshotter only fetches auth from labels and if no auth in the labels,
it will use empty string to replace the original auth.
This causes nydusd lossing auth to access registry.

snapshotter: don't touch original nydusd auth if no auth in labels

---

Cargo.lock
Cargo.toml

Instead of getting it from github.

cargo: use event-manger from crate.io

---

.github/workflows/release.yml
misc/configs/nydusd-config.json

So that user can just use it in normal use cases.

release: include an example nydusd config in the release tarball

---

.github/workflows/ci.yml

So we can perform smoke test against PRs for stable-1.x updates.

action/ci: add stable-1.x branch to CI target branches list

---

Cargo.lock
Cargo.toml

Let's dump the version of nydus and prepare for releasing v1.1.1

cargo: dump package version to 1.1.1

---

rafs/src/fs.rs
src/bin/nydusd/daemon.rs
src/bin/nydusd/main.rs
src/lib.rs

When running passthrougfs together with rafs in the same vfs instance, we need to make sure that necessary passthroughfs options are enabled rather than using the default vfs options.

improve passthroughfs when running together with rafs

---

docs/nydus-design.md
docs/nydus-image.md
docs/nydus-overlayfs.md
docs/prefetch.md

Fix some minor typos and grammatical problem.
Signed-off-by: bin liu <liubin0329@gmail.com>

docs: fix some typos and grammatical problem

---

app/README.md

The crate name should be nydus-app.

app: fix incorrect crate name in README.md

---

blobfs/src/sync_io.rs
rafs/src/metadata/layout/v6.rs
src/bin/nydus-image/builder/stargz.rs
src/bin/nydus-image/core/bootstrap.rs
src/bin/nydus-image/core/node.rs
src/bin/nydus-image/core/tree.rs
src/bin/nydus-image/main.rs
storage/src/device.rs
storage/src/meta/mod.rs

A patchset addresses v6 implementation regression.

RAFS V6 update

---

contrib/nydus-snapshotter/pkg/filesystem/nydus/fs.go

when create multiple containers with same image, nydus-snapshotter will
create daemon config/socket dir per container, most of them can not be
deleted even though the image is deleted.
Signed-off-by: luodaowen.backend <luodaowen.backend@bytedance.com>

nydus-snapshotter: fix recreate daemon config/socket dir

---

storage/src/cache/filecache/cache_entry.rs
storage/src/cache/filecache/mod.rs

It previously uses the default runtime builder which creates
a thread for each cpu core. Nydusd on a server equipped many
cpu sockets and cores will start many threads most of which are
idle.
In addition, use `spawn_blocking` instead which is more reasonable
within blobcache scenario

cache: set the number of worker threads of tokio threads pool

---

Cargo.lock
src/bin/nydusd/main.rs

```
thread 'main' panicked at 'Non-unique argument name: hybrid-mode is already in use'.
```
The argument `hybrid-mode` is defined twice, which is not legal for clap.

Nydusd: fix panic on cli boot

---

contrib/nydusify/pkg/checker/checker.go
contrib/nydusify/pkg/checker/rule/bootstrap.go
contrib/nydusify/pkg/checker/rule/manifest.go
rafs/src/lib.rs
rafs/src/metadata/cached_v5.rs
rafs/src/metadata/direct_v5.rs
rafs/src/metadata/layout/v5.rs
rafs/src/metadata/layout/v6.rs
rafs/src/metadata/md_v5.rs
rafs/src/metadata/md_v6.rs
rafs/src/metadata/mod.rs
src/bin/nydus-image/builder/diff.rs
src/bin/nydus-image/builder/directory.rs
src/bin/nydus-image/builder/mod.rs
src/bin/nydus-image/builder/stargz.rs
src/bin/nydus-image/core/blob.rs
src/bin/nydus-image/core/bootstrap.rs
src/bin/nydus-image/core/context.rs
src/bin/nydus-image/core/node.rs
src/bin/nydus-image/main.rs

In buildkit/harbor-acceld scenario, nydus-image need to dump blobs and bootstraps for every layer, the last bootstrap file of layer will be used as final metadata of a Nydus image, and other bootstraps of lower layer will be used as cache files in buildkit to speed up image build on next.
Commits:
Builder: fix blob race in diff build
Nydusify: relax blob list check in checker
Builder: fix invalid blob reference in diff build
Builder: some fixups for diff build cache
Builder: implement diff build cache
Builder: introduce artifact storage

A series of changes for supporting diff build cache

---

contrib/nydus-snapshotter/config/daemonconfig.go
contrib/nydus-snapshotter/go.mod
contrib/nydus-snapshotter/pkg/auth/docker.go
contrib/nydus-snapshotter/pkg/auth/docker_test.go
contrib/nydus-snapshotter/pkg/auth/keychain.go

So that if there is a docker config.json setup, we can reuse it.

snapshotter: pass auth from docker config

---

contrib/nydus-overlayfs/.golangci.yml
contrib/nydus-overlayfs/Makefile

Add a `golangci-lint` rule definition file into and trigger corresponding static check in its Makefile.
This PR partly addressed #252

Utilize golangci-lint to perform static check for nydus-overlayfs

---

contrib/ctr-remote/.golangci.yml
contrib/ctr-remote/Makefile

Add a `golangci-lint` rule definition file together with adding a static check step into its Makefile.
This PR partly addresses #252

add golangci-lint tool for ctr-remote tool

---

contrib/nydusify/.golangci.yml
contrib/nydusify/Makefile
contrib/nydusify/cmd/nydusify.go
contrib/nydusify/pkg/backend/backend.go
contrib/nydusify/pkg/backend/oss.go
contrib/nydusify/pkg/backend/registry.go
contrib/nydusify/pkg/cache/cache.go
contrib/nydusify/pkg/cache/cache_test.go
contrib/nydusify/pkg/cache/spec.go
contrib/nydusify/pkg/checker/tool/builder.go
contrib/nydusify/pkg/checker/tool/nydusd.go
contrib/nydusify/pkg/converter/cache.go
contrib/nydusify/pkg/converter/layer.go
contrib/nydusify/pkg/metrics/fileexporter/fileexporter.go
contrib/nydusify/pkg/parser/parser.go
contrib/nydusify/tests/e2e_test.go
contrib/nydusify/tests/image_test.go
contrib/nydusify/tests/registry.go

Add golangci-lint rules definition into
This also partly addresses #255

nydusify: utilize golangci-lint to perform static check

---

README.md

An introduction to `nydus-overlyfs` helper was lacked.
In addition, let's move harbor acceleration service introduction to a separated section. Keep the table only to tools belonging to this project repo.

readme: add brief introduction for nydus-overlayfs

---

misc/top_images/image_list.txt

some images do not have `latest` label. Let's drop them.

misc: update top image list

---

contrib/nydus-snapshotter/go.mod
contrib/nydus-snapshotter/go.sum

Please refer to:
https://github.com/dragonflyoss/image-service/security/dependabot/contrib/nydus-snapshotter/go.sum/github.com%2Fopencontainers%2Fimage-spec/open
Signed-off-by: Changwei Ge <changweige@gmail.com>

snapshotter: bump version of github.com/opencontainers/image-spec to v1.0.2

---

src/bin/nydus-image/inspect.rs

Let nydus-image inspect tool print more information when debug the nydus image
Fix command parsing panic when more than one whitespaces input

Slightly improve nydus-image inspect 

---

storage/src/cache/blobcache.rs

Building nydus image with --chunk-aligned option set, decompressed_offset +
decompressed_size = next_decompressed_offset can't be ruled.
So we use compressed part now.

blobcache: check chunks continuity by their compressed size

---

Cargo.lock
Cargo.toml

Release `v2.0.0-rc.0` for building release binaries.

Bump version to 2.0.0-rc.0

---

src/bin/nydusd/main.rs

The acceptable range for thread-num should be [1-2024], but now
this option can be set larger than 1024.

nydusd: fix thread-num validation

---

rafs/src/metadata/direct_v6.rs
rafs/src/metadata/layout/v6.rs
rafs/src/metadata/md_v6.rs
storage/src/meta/mod.rs

This adds more sanity checks for metadata read from bootstrap in order
to prevent malicious images.

Rafs: validate metadata stored in bootstrap

---

src/bin/nydusctl/commands.rs
src/bin/nydusd/daemon.rs
src/bin/nydusd/virtiofs.rs
src/lib.rs

Implement set_state/get_state to avoid panicking when `nydusctl  info` is called.
Fixes: #294 
With this PR:
```bash
$ ~/nydusctl --sock $sock info
Version:                "2.0.0-rc.0"
Status:                 "RUNNING"
Profile:                "debug"
Backend list:
/containers
type:                   PassthroughFs
mountpoint:             /containers
mounted_time:           2022-01-30 13:46:49.241122388 +08:00
```
```bash
$ ~/nydusctl --sock $sock info
Version:                "1.0.0"
Status:                 "RUNNING"
Profile:                "release"
Backend list:
/134/fs
type:                   Rafs
mountpoint:             /134/fs
mounted_time:           2022-01-30 12:53:36.566015398 +08:00
Mode:                   direct
Prefetch:               true
Prefetch Merging Size:  0
```

nydusd-virtiofs: Implement set_state/get_state to avoid panicking

---

rafs/src/metadata/direct_v5.rs
rafs/src/metadata/mod.rs
src/bin/nydus-image/core/chunk_dict.rs

err info: invalid chunk count
cause: in chunk-dict, inode.size != chunk_size * child_count
Signed-off-by: henry.hj <henry.hj@antgroup.com>

chunk-dict: fix load chunk-dict err

---

api/src/http.rs
src/bin/nydusd/daemon.rs
src/bin/nydusd/main.rs

In test cases, we can use is_ok or is_err against to Result type,
instead of using a match.

test: use is_ok/is_err replace match for Result return type

---

storage/src/cache/filecache/cache_entry.rs

Skip committing to region for internal IO is causing
discontinuous region commision since an intermediate chunk
is skipped from merged requet with many continuous chunks.

cache: also commit current region for internal IO

---

storage/src/cache/filecache/cache_entry.rs
storage/src/cache/state/blob_state_map.rs
storage/src/cache/state/mod.rs
storage/src/lib.rs

It is hard to say the waiting IO can't succeed after a previous
io timeouts.
So give the second io a chance to perform its own backend IO.

cache: return Ok(false) when io inflight tracer timeouts

---

storage/src/cache/filecache/cache_entry.rs

Internal IO can't be loaded from compressed cache file.
Just skip this region.

cache: commit region for internal IO if hits gzip format

---

rafs/src/fs.rs
rafs/src/metadata/layout/v5.rs
rafs/src/metadata/md_v5.rs

Amplified IO chunks should be appended to the last Desc rather
than creating a new desc comprising several chunks.
Other wise it will consume IO buffers provided by upper layer.
Moreover, two descs can't be merged before issuing to backend storage.

rafs: only append more chunks to last bio when amplify io

---

rafs/src/fs.rs
rafs/src/lib.rs
rafs/src/metadata/direct_v6.rs
rafs/src/metadata/layout/v6.rs
rafs/src/metadata/md_v6.rs
rafs/src/metadata/mod.rs
src/bin/nydus-image/core/bootstrap.rs
src/bin/nydus-image/core/prefetch.rs
storage/src/cache/filecache/cache_entry.rs

Rafs v6 now has the capability of prefetch with this patch set merged if it would.
By design, it places a prefetch table very closely to blob devices table on v6 extended block when creating v6 nydus image.
The `nydus-image` command line user interface is exactly the same with v5 style. Each file that needs to be prefetched will have its `nid` persisted into the prefetch table.
When nydusd starts, the prefetching files will be found from the prefetch table and the files' contents will be downloaded in ahead of time.

Add capability of prefetch for rafs v6 format

---

rafs/src/metadata/layout/v6.rs
src/bin/nydus-image/core/bootstrap.rs

Nid in prefetch table is of u32, so prefetch table should be
files_count * size_of::<u32>()

nydus-image: fix wrongly calculated prefetch table size

---

Makefile

The sencond pameter of build_golang should include make
command.

Makefile: add missed make command for build_golang

---

docs/nydusd.md

Show how nydus integrate with Dragonfly P2P service.

Doc: add p2p proxy field in nydusd config

---

src/bin/nydusd/fusedev.rs

`is_mount` can only take a canonicalized path which is shown in
/proc/self/mounts.

nydusd: fix is_mount failure

---

Cargo.lock
Cargo.toml

To bring in fix for RUSTSEC-2022-0014.

cargo: update openssl-src dependency

---

Cargo.lock
Cargo.toml
src/bin/nydusd/daemon.rs
src/bin/nydusd/main.rs

Nydusd responds to SYS_TERM and SYS_INT based on event poll. In fact, it needs a way to communicate between threads. Event poll is platform-coherent. 
This PR replace raw eventfd with MIO, which is a I/O library for focusing on non-blocking APIs.

refact: use mio for daemon exit signal monitoring

---

README.md
contrib/nydus-backend-proxy/Cargo.toml
contrib/nydus-backend-proxy/Makefile
contrib/nydus-backend-proxy/README.md
contrib/nydus-backend-proxy/src/main.rs

A simple HTTP server to serve a local directory as blob backend for nydusd.
In some scenarios such as [sealer](https://github.com/alibaba/sealer), it uses nydus to boost up cluster image distribution. There is no registry (OCI distribution) or OSS service available for blob storage, so we need a simple HTTP server to serve a local directory as blob backend for nydusd. This server exposes OCI distribution like API to handle HTTP HEAD and range GET requests from nydusd for checking and fetching blob.

contrib: add nydusd-http-server

---

contrib/nydusify/go.mod
contrib/nydusify/go.sum

Update docker/distribution version to v2.8.1.
Fix the following error when `make nydusify`:
```
echo "Building target nydusify by invoking: make"
if [ "true" = "true" ]; then
docker run --rm -v "/root/go":/go -v /home/image-service:/nydus-rs --workdir /nydus-rs/contrib/nydusify golang:1.17 make
else
make -C contrib/nydusify
fi
Building target nydusify by invoking: make
go: downloading github.com/containerd/containerd v1.4.13
go: downloading github.com/pkg/errors v0.9.1
go: downloading github.com/sirupsen/logrus v1.7.0
go: downloading github.com/urfave/cli/v2 v2.3.0
go: downloading github.com/urfave/cli v1.22.2
go: downloading github.com/dustin/go-humanize v1.0.0
go: downloading github.com/opencontainers/go-digest v1.0.0
go: downloading github.com/opencontainers/image-spec v1.0.2
go: …
```

nydusify: update docker/distribution dependency

---

src/bin/nydus-image/builder/diff.rs
src/bin/nydus-image/main.rs

commit 0c0fa920b09dd6e2e592d8ee67cd712974fd2379 (HEAD -> gh-master-nydus-image, gh/nydus-image)
Author: gexuyang <gexuyang@linux.alibaba.com>
Date:   Wed Mar 9 16:16:46 2022 +0800
nydus-image: add log info in diff build
Signed-off-by: gexuyang <gexuyang@linux.alibaba.com>
commit ab9cce788bdd335300e8eee0b7846ee351231e97
Author: gexuyang <gexuyang@linux.alibaba.com>
Date:   Wed Mar 9 15:47:49 2022 +0800
nydus-image: add log-file to set log output
Signed-off-by: gexuyang <gexuyang@linux.alibaba.com>
commit 804dc4a95fbbef41d42363e1f10acbbf040630f3
Author: gexuyang <gexuyang@linux.alibaba.com>
Date:   Wed Mar 9 15:16:34 2022 +0800
refactor: nydus-image: prepare ArgMatches in a new function
The main function is too long to understand its logic. Refactor its
ArgMatches logic by extracting it …

Nydus image

---

blobfs/src/lib.rs
blobfs/src/sync_io.rs
rafs/src/fs.rs
storage/src/backend/localfs.rs
storage/src/backend/mod.rs
storage/src/backend/oss.rs
storage/src/backend/registry.rs
storage/src/cache/worker.rs
storage/src/device.rs
storage/src/meta/mod.rs
storage/src/test.rs

Blobfs relies on the BlobPrefetchRequest structure that field of "offset"
and "len" are both u32, the maximum support is 4G. But the maximum blob file
will exceed 4G, so change the define of "offset" and "len" to u64.

storage: update BlobPrefetchRequest fields type from u32 to u64

---

Makefile

Per https://github.com/rust-lang/rust-clippy/#travis-ci, we should
use -Dwarnings to fail CI upon both clippy warnings and rustc warnings.
Right now rustc warnings are silently ignored.

makefile: correct cargo clippy

---

blobfs/src/lib.rs

When blob_cache_dir does not exist, create it instead of return error.
Signed-off-by: gexuyang <gexuyang@linux.alibaba.com>

blobfs: ensure blob cache dir exist

---

Makefile

Should not use ONESHELL otherwise we'll ignore all shell errors except
the last one.

makefile: fix error handling and always run virtiofs ut

---

api/src/http.rs
api/src/http_endpoint_v2.rs
docs/samples/boostrap_blob_cache_entry.json
rafs/src/metadata/mod.rs
src/bin/nydusd/api_server_glue.rs
src/bin/nydusd/blob_cache.rs
src/bin/nydusd/fs_cache.rs
src/bin/nydusd/main.rs
src/bin/nydusd/service_controller.rs
storage/src/backend/localfs.rs
storage/src/backend/mod.rs
storage/src/cache/filecache/mod.rs
storage/src/cache/fscache/mod.rs
storage/src/cache/mod.rs
storage/src/factory.rs

The PR enhance the nydusd main to load cached blob object configuration information from configuration file, so those
blob objects may be used to support fscache.

Load blob cache object information from command line

---

api/src/http.rs
docs/samples/boostrap_blob_cache_entry.json
src/bin/nydusd/api_server_glue.rs
src/bin/nydusd/blob_cache.rs
src/bin/nydusd/service_controller.rs
storage/src/backend/mod.rs
storage/src/backend/oss.rs
storage/src/backend/registry.rs

The blob manager needs a path to manage metadata blobs, so add one.

api: add path for metadata blob

---

api/src/http.rs
src/bin/nydusd/api_server_glue.rs

We should exit the api server thread when poll fails on non EINTR errors.
Otherwise we may enter a busy loop.

nydusd: handle api server mio poll error

---

rafs/src/fs.rs
src/bin/nydus-image/core/node.rs

Usually the root directory is created by the build tool (nydusify/buildkit/acceld)
and the mtime of the root directory is different for each build, which makes it
completely impossible to achieve repeatable builds, especially in a tar build scenario
(blob + bootstrap in one tar layer), which causes the layer hash to change and wastes
registry storage space, so the mtime of the root directory is forced to be ignored.

Builder: make repeatable for root directory

---

contrib/nydusify/cmd/nydusify.go
contrib/nydusify/pkg/parser/parser.go

For a single manifest image, we just ignore the arch, so that allowing
to do a default conversion on a different arch's host, for example
converting an arm64 image on an amd64 host.

Nydusify: ignore arch for single manifest

---

contrib/nydusify/pkg/checker/rule/bootstrap.go
rafs/src/metadata/mod.rs
src/bin/nydus-image/builder/diff.rs
src/bin/nydus-image/builder/directory.rs
src/bin/nydus-image/builder/stargz.rs
src/bin/nydus-image/core/blob_compact.rs
src/bin/nydus-image/core/bootstrap.rs
src/bin/nydus-image/core/chunk_dict.rs
src/bin/nydus-image/core/context.rs
src/bin/nydus-image/core/node.rs
src/bin/nydus-image/core/tree.rs
src/bin/nydus-image/main.rs
src/bin/nydus-image/merge.rs
src/bin/nydus-image/stat.rs
src/bin/nydus-image/validator.rs
tests/diff.rs

Introduce a new build mode named tar build in nydusify and builder (nydus-image).
In order to correspond to the OCI image layer, we need a new build mode, that is
to convert the OCI-formatted tar stream directly into a nydus-formatted tar stream.
The nydus tar stream contains blob and bootstrap files, and the workflow is divided
into two steps, Convert and Merge.
Convert: converts each layer of the OCI tar stream to a nydus tar stream.
Merge: reads the bootstrap files from each layer of the nydus tar stream and merges
them into a final bootstrap.
Support merge sub-command in builder, it will be used in [converter](https://github.com/containerd/nydus-snapshotter/pull/34) package, and this
package will be imported by acceleration-service and buildkit to support the conversion
or build of …

Builder: support tar build

---

storage/src/cache/cachedfile.rs
storage/src/cache/filecache/mod.rs
storage/src/cache/fscache/mod.rs
storage/src/utils.rs

Enhance cachefiles to support direct IO for fscahce, but direct IO is
not supported for filecache yet. We may enhance it to support filecache
on demand.

storage: support direct IO for fscache

---

storage/src/remote/server.rs

I suspect it's just that 4-sec timeout is not enough for the corner cases.

test remote::server::tests::test_reconnect: Give 10 secs more to try

---

contrib/docker-nydus-graphdriver/Dockerfile
contrib/docker-nydus-graphdriver/config.json
contrib/docker-nydus-graphdriver/plugin/nydus/glue.go
contrib/docker-nydus-graphdriver/plugin/nydus/nydus.go
src/bin/nydusd/blob_cache.rs
src/bin/nydusd/fs_cache.rs

Step I. prepare a json file:
{
"type": "bootstrap",
"id": "aa229b3a8eeeacf0bfbb17a6415fa6a817583d99c4b590fc6b56a50f49e8957c",
"domain_id": "aa229b3a8eeeacf0bfbb17a6415fa6a817583d99c4b590fc6b56a50f49e8957c",
"config": {
"id": "factory1",
"backend_type": "registry",
"backend_config": {
"scheme": "https",
"host": "index.docker.io",
"repo": "hsiangkao/ubuntu"
},
"cache_type": "fscache",
"cache_config": {
"work_dir": "/var/lib/containerd-nydus-grpc/cachedir"
},
"metadata_path": "/root/ubuntu-20.04.image.boot"
}
}
Step II.
docker poll docker.io/hsiangkao/ubuntu:20.04-rafs-v6-docker
and copy image.boot as /root/ubuntu-20.04.img.boot
Step III.
cargo build --target x86_64-unknown-linux-gnu --features=fusedev --release --target-dir target-fusedev --bin nydusd
mkdir /root/fscache …

Finalize single worker fscache support

---

.github/workflows/ci.yml
.github/workflows/release.yml

So that we don't rely on the HUB_UPLOAD_TOKEN secret.
See https://github.com/bergwolf/image-service/actions/runs/2108725442 for a successful run.

action: use softprops/action-gh-release to do release

---

contrib/docker-nydus-graphdriver/plugin/nydus/nydus.go

For more details, see: https://lore.kernel.org/r/20190418144208.21832-1-amir73il@gmail.com

docker-nydus-graphdriver: avoid `overlayfs: overlapping path'

---

docs/containerd-env-setup.md
docs/nydusd.md
storage/src/backend/connection.rs
storage/src/backend/mod.rs

Add `skip_verify: true` option to enable skipping SSL certificate validation
for HTTPS scheme, and add some comments for other options.

Backend: support skip_verify option

---

src/bin/nydus-image/merge.rs

The `has_xattr` flag is not a user-specified by builder (nydus-image),
the flag value is calculated by checking whether if have any files have
xattr, so for bootstrap merge scenario, we can't assume this value is
same between different bootstraps.

Builder: remove has_xattr flag check for merge

---

api/src/http.rs
src/bin/nydusd/api_server_glue.rs
src/bin/nydusd/main.rs

The mio waker must be alive to get the notification delivered,
otherwise the inflight notification may get dropped silently.
Also fix a bug in the way to detect daemon working state.

nydusd: fix a race window when shutdown http server

---

api/src/http.rs

The mio waker must be alive to get the notification delivered,
otherwise the inflight notification may get dropped silently.
Signed-off-by: Liu Jiang \<gerry@linux.alibaba.com\>

http: fix waker dead improperly due to lifetime mismatch

---

storage/src/cache/filecache/mod.rs
storage/src/cache/fscache/mod.rs
storage/src/cache/state/blob_state_map.rs
storage/src/cache/state/indexed_chunk_map.rs
storage/src/cache/state/persist_map.rs
storage/src/cache/state/range_map.rs

The fscache driver maintains its own data ready state. On startup stale
chunkmap may cause data corrupt for fscache, so clean stale chunkmap
on startup.

stroage: avoid stale chunkmap state for fscache

---

api/src/http.rs
api/src/http_endpoint_v2.rs
src/bin/nydusd/api_server_glue.rs
src/bin/nydusd/blob_cache.rs

```
fscache: implement blob unregister api
Add `DELETE /api/v2/blobs?domain_id=?` api to support remove (unregister)
fscache blob cache config, including bootstrap and its blob items.
fscache: refactor blob cache state
Simplify BlobCacheState methods to make code cleaner.
```

fscache: implement blob unregister api

---

api/src/http.rs
src/bin/nydusd/api_server_glue.rs
src/bin/nydusd/daemon.rs
src/bin/nydusd/fusedev.rs
src/bin/nydusd/main.rs

When exiting, make sure we wait for the state machine thread to quit.
A few changes were applied:
1. exit_daemon() should call daemon.stop() so that it can result in
different daemon action depending on the current state. Then in a normal
workflow, nydusd would just umount and quit. But when in Interrupted,
nydusd just dies directly without doing any umount etc.
2. Quit the state machine thread upon EXIT (TerminateFuseService) event.
3. Wait for the state machine thread together when waiting for the fuse
service threads.
4. Nydusd should just die when getting EXIT message in INIT state.
5. Only send Stop event if state is not INTERRUPTED or STOPPED.
Otherwise there is no state machine thread to handle it.
6. Init and Interrupted should always be able to stop as well.

nydusd: graceful state machine thread shutdown

---

Cargo.toml
api/Cargo.toml
app/Cargo.toml
blobfs/Cargo.toml
error/Cargo.toml
rafs/Cargo.toml
storage/Cargo.toml

When compiling dragonball-sandbox, an error is reported:                                                        
```                                                                                                             
Error:   --> /home/runner/.cargo/git/checkouts/image-service-7b544e3856b79dd7/cba6aa9/storage/src/utils.rs:27:26
|                                                                                                            
27 |         match preadv(fd, iovec, offset as off64_t).map_err(|_| last_error!()) {                            
|                          ^^^^^ types differ in mutability                                                  
|                                                                                                            
= note: expected …
```

Use Caret to specify dependency versions.

---

contrib/nydusify/cmd/nydusify.go
contrib/nydusify/pkg/packer/packer.go
contrib/nydusify/pkg/packer/packer_test.go
docs/nydusify.md

Add --log-level option and -D as global options for
pack/convert/check subcommands.
The -D is the shortcut for --log-level debug,
and will have the highest priority.

add global log level option for nydusify

---

rafs/src/metadata/md_v5.rs

BlobDevice only allow read in same blob, so if next ino
in different blob should not amplify io.
Refs:
- https://github.com/dragonflyoss/image-service/issues/404
Signed-off-by: killagu <killa123@126.com>

fix: not amplify io if next file in different blob

---

.github/workflows/ci.yml
.github/workflows/convert.yml
.github/workflows/release.yml
Cargo.lock
Cargo.toml
Makefile
contrib/ctr-remote/Makefile
contrib/docker-nydus-graphdriver/Makefile
contrib/nydus-overlayfs/Makefile
contrib/nydusify/Makefile
misc/musl-static/Dockerfile

Add $ARCH to all cargo/go build commands for supporting multiple
arch compilation.
Use rust cross tool instead of clux/muslrust docker image to
resolve cross compiling issue for arm64 arch.
All the amd64 and arm64 binaries have been tested on separate
machines and basically work well.
A successful action can be found here: https://github.com/imeoer/image-service/actions/runs/2230520032
The macOS binary release support and removing clux/muslrust docker
image will as TODO next.
Close #401

action: support multiple arch releases

---

src/bin/nydus-image/core/bootstrap.rs
src/bin/nydus-image/core/node.rs

Avoid the root inode use 0 as nid, which may cause the `..` directory disappear in root dir 's subdirs; What's more, change the dirname's length from in character to in byte.
Signed-off-by: Qi Wang <mpiglet@outlook.com>

Bug fix: the `..` disappear.

---

src/bin/nydus-image/builder/stargz.rs
src/bin/nydus-image/core/context.rs
src/bin/nydus-image/core/node.rs
src/bin/nydus-image/core/tree.rs

Firstly, we add a `dirents_offset` field in `struct Node`, which is used by directory files.
Previously, the dirents have to be placed the next block where its dir inode was placed, by
introducing this field, we allow the dirents to be seperated from its dir inode.
Secondly, we add an `available_blocks` field in `struct BootstrapCtx`,
to record blocks that are used but still contain unused space.
feature #348
Signed-off-by: Qi Wang <mpiglet@outlook.com>

nydus-image: Feature, add a block allocator for reducing bootstrap size by reusing used blocks

---

Cargo.lock
Cargo.toml
rafs/src/lib.rs
src/bin/nydus-image/builder/diff.rs
src/bin/nydus-image/builder/directory.rs
src/bin/nydus-image/builder/stargz.rs
src/bin/nydus-image/core/blob.rs
src/bin/nydus-image/core/blob_compact.rs
src/bin/nydus-image/core/bootstrap.rs
src/bin/nydus-image/core/context.rs
src/bin/nydus-image/core/node.rs
src/bin/nydus-image/main.rs
src/bin/nydus-image/merge.rs

Enable `inline-bootstrap` option to merge the blob and bootstrap into one
file. We need some header to index the location of the blob and bootstrap,
this patch uses a tar header structure that arranges the data as follows:
`blob_data | blob_tar_header | bootstrap_data | boostrap_tar_header`
This is a tar-like structure, except that we put the tar header after the
data. The advantage is that we do not need to determine the size of the data
first, so that we can write the blob data by stream without seek to improve
the performance of the blob dump by using fifo, if we need to read the bootstrap
data quickly, first need to read the 512 bytes tar header from the end of blob
file first, and then seek offset to read bootstrap data.
Related PR: …

builder: implement tar like build

---

storage/src/meta/mod.rs

It should use ``compressed size`` instead of ``uncompressed size``
in get_chunks_compressed() so that prefetch can work properly.

storage: fix batched comprssed blob read

---

rafs/src/metadata/mod.rs
src/bin/nydus-image/builder/diff.rs
src/bin/nydus-image/merge.rs
tests/diff.rs

The merge operation in builder (nydus-image) use `RafsSuper::walk_inodes`
method to walkthrough the whole filesystem inodes by DFS order, but it
does not call the callback for the hardlink pair, which causes some hardlink
files to be lost in the final bootstrap after merge.
The root cause is that the `RafsSuper::get_inode` method always gets only
the RafsInode of a particular file name in the hardlink pair because the ino
number of the hardlink pair are the same.
Fix by passing `RafsInode` trait object in `RafsSuper::walk_inodes` directly.

builder: fix lost hardlink

---

api/src/http.rs
rafs/src/fs.rs
src/bin/nydusd/blob_cache.rs
src/bin/nydusd/fs_cache.rs
storage/src/cache/mod.rs

If prefetch_config.enable = true, prefetch all data after open data blob.
tested with a configuration json like below:
```
{
"type": "bootstrap",
"config": {
"backend_type": "registry",
"backend_config": {
"scheme": "https"
},
"cache_type": "fscache"
},
"fs_prefetch": {
"enable": true,
"threads_count": 2,
"merging_size": 131072,
"bandwidth_rate": 0
}
}
```

fscache: add prefetch_all

---

contrib/nydusify/pkg/build/builder.go
contrib/nydusify/pkg/converter/manifest.go

Move root path to the last, let all command line options
before root path.
before:
nydus-image create
--bootstrap tmp/bootstraps/...
--whiteout-spec oci
--output-json tmp/bootstraps/...-output.json
--blob tmp/blobs/a9151a84-9bb4-4f85-90c1-9a0630270143
tmp/source/...
--prefetch-policy fs
after:
nydus-image create
--bootstrap tmp/bootstraps/...
--whiteout-spec oci
--output-json tmp/bootstraps/...-output.json
--blob tmp/blobs/a9151a84-9bb4-4f85-90c1-9a0630270143
--prefetch-policy fs
tmp/source/...

nydusify: change args order when calling nydus-image

---

docs/containerd-env-setup.md

`sudo cat > SOMEPATH <<EOF` won't work when user has no permission to write to SOMEPATH.
Using `sudo tee SOMEPATH` instead.

cat heredoc will not work with sudo

---

Cargo.toml

Other projects should enable the blobfs/virtiofs feature directly instead of
rely on the virtiofs feature.

cargo: virtiofs does not depend on blobfs

---

.github/workflows/release.yml
Makefile

Right now, only nydusctl and nydusd compile on macos. So just include
them in the release tarball. Other binaries can be included later.
Example run can be found here: https://github.com/bergwolf/image-service/runs/6420841588

action: release macos bianries as well

---

rafs/src/fs.rs
rafs/src/metadata/cached_v5.rs
rafs/src/metadata/direct_v5.rs
rafs/src/metadata/direct_v6.rs
rafs/src/metadata/mod.rs
rafs/src/metadata/noop.rs
rafs/src/mock/mock_super.rs

method get_blobs of RafsSuperBlobs has the same signature as
get_blob_infos of RafsSuperBlock,
and RafsSuperBlock is inheritance of RafsSuperBlobs.
But the only one use of the get_blobs is based on type of
RafsSuperBlock, so RafsSuperBlobs is no meanings, it can
be deleted and replaced by get_blob_infos method.

rafs: delete RafsSuperBlobs trait

---

rafs/src/metadata/direct_v6.rs

The dir file's dirents may occupy multiple blocks, and only the last
block may not be fully used. Previously, the last dirent of each block
is treated as the last dirent of the last block, which causes the
nydusd-fusedev to panic when using rafs v6 format.
To fix this bug, we process the last dirent of the last block different
from the last dirent of the other blocks.
fix #428 

rafs v6: bug fix for the incorrect dirents process

---

.github/workflows/release.yml

User can use this shasum file to verify the validity of
the downloaded nydus release tarball files.
A successful action can be found here:
https://github.com/imeoer/image-service/actions/runs/2318463434
https://github.com/imeoer/image-service/releases/tag/v2.0.5

action: add shasum file for released assets

---

src/bin/nydus-image/builder/diff.rs

Use `ls -R` instead, to avoid using `tree`.
fix #432

test(nydus-image): remove unneeded `tree` dependency in unit test

---

contrib/nydusify/pkg/converter/layer.go
docs/nydus-design.md
docs/nydus-image.md
docs/nydusify.md
docs/prefetch.md
docs/tutorial.md
src/bin/nydus-image/core/blob_compact.rs
src/bin/nydus-image/core/context.rs
src/bin/nydus-image/core/node.rs

Fix some typo in docs, and other files use `boostrap` instead of
`bootstrap`.

docs: fix some typo

---

tests/builder.rs
tests/smoke.rs

Let's make smoke testing to build rafs v6 layer, then mount using nydusd,
and verify filesystem consistency basically.
Since nydusd does not support cached mode and dummycache for rafs v6, the
part of test cases are not enabled.
Also no load is implemented for rafs v6 parent bootstrap, the layered build
test case is temporarily disabled.

smoke: add basic testing for rafs v6

---

storage/src/remote/server.rs

There might be some issue in the test themselves. Let's ignore them for
now.

storage: ignore two unstable tests

---

docs/tutorial.md

`containerd-nydus-grpc` has been removed from 2.x.x, so we should update tutorial.md for getting `containerd-nydus-grpc` from [nydus-snapshotter release](https://github.com/containerd/nydus-snapshotter/releases)

chore: update tutorial.md

---

Cargo.lock
api/Cargo.toml
storage/Cargo.toml

Nydus snapshotter throws this error if HTTP payload exceeds 1k
when calling nydusd's mount API:
```
Post "http://unix/api/v1/mount?mountpoint=/2/fs": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```
The root cause is that the HTTP server hangs, see https://github.com/openanolis/dbs-uhttp/pull/14
Update dbs-uhttp v0.3.0 to fix.

cargo: upgrade dbs-uhttp to v0.3.0

---

src/bin/nydusd/main.rs

The same reason as commit 0647229305cc ("nydusd: recover option
--shared-dir with feature fusedev").

nydusd: recover --shared-dir for fuse backend again

---

rafs/src/metadata/md_v6.rs

When specifying v6 prefetching files by --prefetch-polich=fs,
"/" indicates that all files should be prefetched in this nydus image.
The prefetch table size is defined as u32, but the count of prefetching
entries is wrongly calculated since the divisor is the size of u64 resulting
in no files being prefetch.
Moreover,  we should consider picking this patch into stable branches.

rafs/v6: fix wrongly calculated prefetch table size

---

api/src/http.rs
api/src/http_endpoint_v1.rs
src/bin/nydusd/api_server_glue.rs
src/bin/nydusd/daemon.rs
src/bin/nydusd/fusedev.rs

`UPGRADING` and `INTERRUPTED` are designed for hot-upgrading, which is a use case instead of daemon's state. As a result, they are weird in lack of upgrading function.
Merge `UPGRADING` and `INTERRUPTED` to `READY`. `READY` means service is well-configured, but waiting for trigger. For fuse-based daemon, it means fuse device is mounted, while fuse mountpoint may be not attached. The daemon lives in `INIT` -> `READY` -> `RUNNING` -> `READY` -> `DIE`.
1. Daemon context with new status.
2. Async `TerminateFuseService`, `Umount` actions.
3. `Start` endpoint, which is usually used after `takeover` endpoint.
4. Async exit after fuse device unmounted abnormally.

refact: nydusd's state machine

---

src/bin/nydusd/main.rs
src/bin/nydusd/service_controller.rs

Frankly speaking, `--shared-dir` is useless when nydusd works on FUSE mode. But we can still use this option to demonstrate that nydusd can work as FUSE passthroughfs and test the corresponding logics belong to `fuse-backend-rs`.
Add a more detailed help message telling why it is reserved.
In addition, fix a type name.

Tiny typo fix and improve nydusd help message

---

src/bin/nydusd/service_controller.rs
src/bin/nydusd/virtiofs.rs

State machine is turned on arriving 'RUNNING' via 'READY', instead from 'INIT' to 'RUNNING' directly. The virtio and fscache miss the trigger from 'INIT' to 'READY', still trying to transfer from 'INIT' to 'RUNNING' which is old fashion. So this patch add additional transformation.

fix: fscache and virtio fail to start

---

storage/src/cache/cachedfile.rs
storage/src/utils.rs

The fscache requires that data is 4K-aligned and and size is multiple of
4K. There's a mistake when merging code into the master branch, which
breaks fscache constraints.

storage: fix a bug related caused by merging code

---

Cargo.toml
api/src/http.rs
api/src/http_endpoint_v2.rs
src/bin/nydusd/api_server_glue.rs
src/bin/nydusd/blob_cache.rs
src/bin/nydusd/fs_cache.rs

Several improvements to the nydusd blob cache manager.

Improvements to the blob cache manager

---

src/bin/nydus-image/core/node.rs
src/bin/nydus-image/core/prefetch.rs

Some comments are wrong or not accurate enough, fix them.
Signed-off-by: zhaoshang <zhaoshangsjtu@linux.alibaba.com>

nydus-image: fix some comments

---

contrib/nydusify/cmd/nydusify.go
contrib/nydusify/pkg/build/builder.go
contrib/nydusify/pkg/build/workflow.go
contrib/nydusify/pkg/checker/checker.go
contrib/nydusify/pkg/checker/tool/nydusd.go
contrib/nydusify/pkg/converter/converter.go
contrib/nydusify/tests/e2e_test.go
contrib/nydusify/tests/image_test.go
contrib/nydusify/tests/nydusify.go
contrib/nydusify/tests/registry.go
rafs/src/metadata/direct_v6.rs
rafs/src/metadata/layout/v6.rs
src/bin/nydus-image/builder/directory.rs
src/bin/nydus-image/core/bootstrap.rs
src/bin/nydus-image/core/node.rs
src/bin/nydus-image/core/tree.rs
src/bin/nydus-image/inspect.rs
tests/builder.rs
tests/smoke.rs

We have adapted the nydusify and nydus-image to support using nydusify directly to build v6 image, to accomplish this purpose, we have introduce several features and fix several bugs.
Features:
1. Previously, the load_parent_bootstrap is unusable for v6 image, we have adapted it for both V5 and V6.
2. We have implemented all methods for v6's OndiskInodeWrapper.
Bug fixes:
1. The dirents_offset will only be used by dir and symlink files, for other files, calculating it may leads to overflow.
2. Correct chunk info implementation for v6.
3. Previous, we assume the . and .. are the first and second dirents, which is wrong.
4. Under some circumstances, the xattr size is wrong.
FYI, we have tested converting all top images in the image_list.txt and checked their bootstraps with fsck.erofs.
#425

nydusify & nydus-image: v6 image conversion support

---

docs/nydus-fscache.md

update compile command and copy the binary into $PATH in docs/nydus-fscache.md

Doc: Correct fscache distribution steps

---

Cargo.lock
Cargo.toml
api/Cargo.toml
api/src/http.rs
rafs/Cargo.toml
storage/Cargo.toml
storage/src/backend/mod.rs
storage/src/cache/worker.rs
utils/CHANGELOG.md
utils/Cargo.toml
utils/src/lib.rs
utils/src/mpmc.rs

Prepare for releasing nydus-utils-v0.3 and update tokio to fix a bug.

Prepare for releasing nydus-utils-v0.3

---

src/bin/nydus-image/core/context.rs
src/bin/nydus-image/merge.rs

Let the merge subcommand support multiple versions of image merging

nydus-image: supports multiple versions of merge

---

contrib/nydusify/pkg/checker/checker.go
contrib/nydusify/tests/nydusify.go

The cache mode is used to speed up. However, when checking, especially the RAFS v6 haven't support the cache mode,
we should directly use direct mode. 
What's more, the `--fs-version` hasn't been add to nydusify check's arg.

nydusify: bug fix, `check` subcommand uses direct mode

---

storage/src/cache/dummycache.rs
storage/src/cache/filecache/mod.rs
storage/src/cache/fscache/mod.rs
storage/src/cache/mod.rs
storage/src/factory.rs

If a blob cache mgr has no associated blobs, it should be reclaimed.

stroage: garbage collect unused blob cache mgr

---

contrib/nydusify/pkg/cache/cache.go
contrib/nydusify/pkg/cache/cache_test.go
contrib/nydusify/pkg/converter/cache.go
contrib/nydusify/pkg/converter/converter.go
contrib/nydusify/pkg/converter/layer.go
contrib/nydusify/pkg/converter/manifest.go
contrib/nydusify/pkg/utils/constant.go

Add an annotation to the image manifest for detecting the bootstrap fs
version without reading the magic number from bootstrap.
fix #496

nydusify: add fs-version annotation

---

contrib/nydusify/cmd/nydusify.go

Add fs-version value check, should be either "5" or "6".

nydusify: add command line arg fs-version check

---

Cargo.lock
app/Cargo.toml
storage/Cargo.toml
storage/src/cache/worker.rs
utils/CHANGELOG.md
utils/Cargo.toml
utils/README.md
utils/src/async_helper.rs
utils/src/lib.rs

Prepare for enabling async io for nydus-storage

utils: introduce per-thread tokio current thread Runtime

---

contrib/nydusify/cmd/nydusify.go
contrib/nydusify/pkg/checker/checker.go
contrib/nydusify/pkg/checker/tool/nydusd.go
contrib/nydusify/pkg/parser/parser.go
contrib/nydusify/pkg/utils/utils.go
rafs/src/metadata/direct_v6.rs
rafs/src/metadata/mod.rs
src/bin/nydus-image/core/bootstrap.rs
src/bin/nydus-image/core/chunk_dict.rs
src/bin/nydus-image/core/node.rs

1. nydus-image: fixed the incomplete chunk info caused by HashChunkDict
2. nydus-image: Fixed that the loop did not jump out because of the nested loop, causing the loop to continue running.
3. Nydusify: support check subcommand for nydus v6

Fixed several correctness issues with Nydus v6 at runtime.

---

src/bin/nydusd/fs_cache.rs

Nydusd will read with amplification data when handling fscache read
request, so we don't need to give a warning if the requested data size
does not match with the read size by actually.

fscache: remove warning when handle fscache read request

---

src/bin/nydus-image/core/prefetch.rs
tests/builder.rs
tests/smoke.rs
tests/texture/directory/emptydir.result

At present, the prefetch table of v6 is stored in Node.index, which starts from 1,
and when we get the prefetch table, we mistakenly treat it as an array index

nydus-image: fix the prefetch table was out of bounds due to use the wrong index

---

docs/nydus-design.md
rafs/src/metadata/layout/v5.rs
src/bin/nydus-image/core/node.rs

Signed-off-by: zhaoshang <zhaoshangsjtu@linux.alibaba.com>

comments: modify comments of src_ino and i_ino

---

src/bin/nydus-image/builder/directory.rs
tests/builder.rs
tests/smoke.rs

Inline-nydus-file consists of blob data, blob header, bootstrap data, bootstrap header. However the part of blob header is missed now.
``` shell
export source=${SOURCE_DIR}
export output=${OUTPUT}
sudo nydus-image create --log-level info  --blob ${output}--source-type directory --whiteout-spec none --fs-version 5 --inline-bootstrap ${source}
sudo hexdump -C ${output}
```
Inline File consist of blob data, blob header, bootstrap data, bootstrap header in order.
1. Fix a condition.
2. Add smoke for inline file in V5 & V6

FIX: miss blob header in inline-nydus-file

---

.github/workflows/release.yml

The cross release version 0.2.2, may contain bug,
leads to the ci gets cancelled, downgrade it to 0.2.1.

github actions: bug fix, the build nydus-rs always gets cancelled

---

src/bin/nydusd/fs_cache.rs
src/bin/nydusd/main.rs
src/bin/nydusd/service_controller.rs

Add command line option "fscache-threads" to nydusd to support
multi-threading for fscache service. There's one thread to receive
fscache request from cachefile fd, and dispatch `READ` requests to
multiple working threads through a multi-producer, multi-consumer
channel.
We have observed about 40% performance boost when serving some multi
threading container workloads.

fscache: enable multi-threading to process fscache requests

---

src/bin/nydusd/main.rs
src/bin/nydusd/service_controller.rs
src/lib.rs

So that can reuse the threads validator code.

nydusd: wrap thread validator as func

---

contrib/ctr-remote/cmd/main.go
contrib/ctr-remote/commands/rpull.go

Other containerd snapshotter could also be named as "ctr-remote",
e.g. stargz. So we'd better give users a conspicuous note that
this is nydus ctr-remote tool.
In addition, correct spelling mistakes.

ctr-remote: note user this ctr is only enhanced for nydus

---

Makefile

We don't provide software package yet. In order to
let users easily install nydus tool chain onto machine.
We'd better provide `make install` to automatically
copy necessary binaris to run nydus-snapshotter, thus to
pull and run nydus image.
Moreover, nydus-snapshotter had already provide `make install`
helper.
Signed-off-by: Changewei Ge <gechangwei@bytedance.com>

makefile: add target `install`

---

rafs/src/metadata/direct_v6.rs
src/bin/nydus-image/builder/stargz.rs
src/bin/nydusd/fs_cache.rs
storage/src/cache/cachedfile.rs
storage/src/cache/dummycache.rs
storage/src/cache/filecache/mod.rs
storage/src/cache/fscache/mod.rs
storage/src/cache/mod.rs
storage/src/meta/mod.rs

builder: sort stargz chunks by uncompressed_offset
```
Ensure that the stargz chunks in the blob meta are sorted by
uncompressed_offset and ordered by chunk index so that they
can be found quickly at runtime with a binary search.
```
fscache: some fixups for large stargz chunk
```
1. use blob_compressed_size to compute stargz's compressed gzip_size;
2. use binary search to find stargz chunk (sorted by uncompressed_offset in blob meta);
```

fscache: fix large stargz chunks processing

---

src/bin/nydus-image/main.rs

Subcommand 'unpack' introduced short option "-o" which is
redundant with global option log-level ending up with a panic
Unfortunately, github CI action didn't catch such regression :-(
INFO [utils - 93:run] - /data00/home/gechangwei/git_repo/nydus-rs/target-fusedev/debug/nydus-image create --bootstrap bootstrap_scratched  --blob /data00/home/gechangwei/nydus-test-yard/blobihdgyw05 --log-level info --fs-version 6 --output-json /tmp/tmp46yv4v3_output.json /data00/home/gechangwei/nydus-test-yard/gen_rootfs_scratch
thread 'main' panicked at 'Argument short must be unique
-o is already in use', /home/gechangwei/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-4f7dbcce21e258a2/clap-2.34.0/src/app/parser.rs:190:13
stack backtrace:
0: rust_begin_unwind
at …

nydus-image: remove redundant -o short option

---

rafs/src/fs.rs

Rafs v6 must store its chunks' info into local
blobcache. So we must configure blobcache in the
rafs conf file.
Check it strictly.
Otherwise, rafs can be mounted, but IO causes panic
```
thread 'fuse_server' panicked at 'explicit panic', storage/src/device.rs:418:18
stack backtrace:
0: std::panicking::begin_panic
at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:616:12
1: nydus_storage::device::BlobIoChunk::as_base
at /data00/home/gechangwei/git_repo/nydus-rs/storage/src/device.rs:418:18
2: <nydus_storage::device::BlobIoChunk as nydus_storage::device::BlobChunkInfo>::uncompress_size
at /data00/home/gechangwei/git_repo/nydus-rs/storage/src/device.rs:471:9
3: <nydus_storage::cache::dummycache::DummyCache as nydus_storage::cache::BlobCache>::read
at …
```

rafs: v6 must have local blobcache configured

---

src/bin/nydusd/fs_cache.rs

This is only a tiny improvement that we don't have
to clone string each time. It will cause memory footprint.

fscache: no need to clone string

---

contrib/nydus-test/framework/nydusify.py
contrib/nydus-test/functional-test/test_nydusify.py
contrib/nydus-test/functional-test/test_stargz.py
contrib/nydus-test/functional-test/test_stress.py
src/bin/nydus-image/core/node.rs

The newly added case can measure conversion time and trim unnecessary cases with private testing image reference

add basic nydusify conversion case

---

contrib/nydus-test/framework/nydus_anchor.py

backend_proxy_url is not mandatory.
This fix nightly integration test action

nydus-test: ignore missing backend_proxy_url

---

.github/workflows/convert.yml

There is no need to run this job all repos, I recently received some emails about this job failure.
Signed-off-by: liubin <liubin0329@gmail.com>

ci: don't run Convert Top Docker Hub Images job on forked repos

---

rafs/src/metadata/direct_v6.rs
rafs/src/metadata/layout/v6.rs

The blob index on the disk where erofs exists starts at 1, but the blob index in BlobInfo starts at 0,
and the blob index on the disk is mistakenly used here instead of blobInfo's index
this will eventually result in the wrong file contents being obtained.

nydusd: fixed getting the wrong chunk due to using the wrong blob index

---

.github/workflows/it.yml
contrib/nydus-test/conftest.py
contrib/nydus-test/framework/nydus_anchor.py
contrib/nydus-test/functional-test/test_api.py

test_api is the only case suite being tested. Let's also replace its storage backend type.
In addition, fill backend proxy configurations into github action.

nydus-test: Replace storage backend with BACKEND_PROXY and adapts github action

---

contrib/nydusify/pkg/checker/rule/filesystem.go
contrib/nydusify/pkg/utils/utils.go
contrib/nydusify/tests/e2e_test.go
contrib/nydusify/tests/nydusify.go
src/bin/nydus-image/core/bootstrap.rs
src/bin/nydus-image/core/chunk_dict.rs
src/bin/nydus-image/core/node.rs
utils/src/digest.rs

Because chunkinfo uses HashMap for storage, the writing to bootstrap is out of order,
so repeated builds may cause the bootstrap content to change.

nydus-image: use BtreeMap replace HashMap to guarante order of chunkinfo

---

src/bin/nydus-image/unpack/mod.rs

Working with multiple layers, snapshotter produces trivial logs.
This patch changes two logs from INFO to DEBUG.

chore: change trivial logs from INFO to DEBUG

---

contrib/nydus-backend-proxy/src/main.rs

Don't panic. Just exit with error and print error message.

backend-proxy: don't panic if address already binded

---

contrib/nydusify/pkg/checker/rule/filesystem.go

#435 Part 1
Signed-off-by: wraymo <raywangv@gmail.com>

add metadata fields for nydusify filesystem check

---

docs/nydus-fscache.md

For the very 1st run, snapshotter's root dir may not exist, leading to errors such as,
"
sudo ctr run --rm -t --snapshotter=nydus docker.io/hsiangkao/ubuntu:20.04-rafs-v6 ubuntu /bin/bash
ctr: failed to mount daemon wMZ3kd7hRWCtE1M_5bnfVA: failed to shared mount: failed to share mount: failed to create new nydus client: failed to build transport for nydus client: stat /var/lib/containerd/io.containerd.snapshotter.v1.nydus/socket/shared_daemon/api.sock: no such file or directory: unknown
"
Reported-by: Benjamin Huang <benjaminhuanghuang@gmail.com>

Doc: make sure snapshotter's root dir exist

---

src/bin/nydusd/main.rs

At present, nydusd says nothing before exit. It's
better to give users and developers a message about
what's going on.

fscache: print error message when nydusd can't start

---

.github/workflows/ci.yml
.github/workflows/release.yml

use macos-11 to run ci/release

ci: ci/release support macos arm

---

src/bin/nydusd/fs_cache.rs

Display detailed error when construct FsCacheHandler with a nonexistent path
Files: fs_cache.rs
Signed-off-by: Benjamin Huang <benjaminhuanghuang@gmail.com>

Display detailed error in FsCacheHandler constructor when cachefiles device not ready

---

.github/workflows/convert.yml

This action also creates pre-built nydus image, so lets convert it
twice, one for pre-built image, the other for integrity check.

Add pre built nydus v6 image

---

storage/src/cache/cachedfile.rs

For now , when we get an io error in do_fetch_chunks, we just return
without clearing the chunk map pending bit. This may cause the following
io always wait for the pending bits.

storage: fix io error may let the chunk map bit always pending

---

contrib/nydusify/cmd/nydusify.go
contrib/nydusify/pkg/checker/rule/filesystem.go
contrib/nydusify/pkg/checker/tool/nydusd.go
contrib/nydusify/pkg/viewer/viewer.go

Nydusify provides a fsViewer to view the file system in the Nydus image.
The fsViewer will pull image's bootstrap according to its url, and it
will mount the file system to pointed path.
Users can view the file system then. For example, they can ran
`$ trivy fs mount-path`
to scan the whole image.
Signed-off-by: YushuoEdge <y-shuo@sjtu.edu.cn>

Nydusify: support "view" subcommand to view Nydus image

---

storage/src/cache/cachedfile.rs
storage/src/cache/worker.rs
storage/src/meta/mod.rs

Reduce backend network IOs by enabling amplification of v6 prefetch requests. For a java image, it could reduce 50% network requests by average.

Reduce network IOs by amplifying prefetch requests

---

rafs/src/fs.rs
rafs/src/metadata/direct_v6.rs
rafs/src/metadata/layout/v5.rs
rafs/src/metadata/mod.rs
storage/src/cache/cachedfile.rs
storage/src/cache/dummycache.rs
storage/src/cache/worker.rs
storage/src/device.rs

The buffer size could be much larger than the real user io request.
For example, fuse-backend-rs will allocate 1MB buffer for each IO
regardless of its read request size ending up with eat up all
prefetch bandwidth when starting the container.

Prefetch limit

---

.github/workflows/convert.yml

We can hardly get useful information from github action

action: avoid print tons of logs

---

Cargo.lock
Cargo.toml
app/Cargo.toml
app/src/lib.rs
src/bin/nydusctl/commands.rs
src/bin/nydusd/main.rs

This RR helps debug and develop nydusd.
1. Nydusd is sometimes forked by nydus-snapshotter and has no stdout and stderr to print panic info. So dumping the panic info into logger is a good choice.
2. print nydusd git commit version by nydusctl CLI tool
This can address https://github.com/containerd/nydus-snapshotter/issues/104

Dump nydusd panic info and backtrace into logger and show nydusd git commit version

---

storage/src/cache/cachedfile.rs
storage/src/cache/filecache/mod.rs
storage/src/cache/fscache/mod.rs

Fetch blob.meta in asynchronous mode, to reduce container startup time.

storage: fetch blob.meta in asynchronous mode

---

.github/workflows/it.yml

So that we get to know the integration status.

action: enable nydus integration tests

---

src/bin/nydusd/fs_service.rs

After umounting a filesystem, try to gc unused blob files, otherwise
it may break the gc logic in nydus-snapshotter.

nydusd: gc unused blob files after umounting

---

storage/src/device.rs

`self.offset + self.len != _offset` is legal when merge more regions.
So the debug_assert is wrong
Upper layer should ensure its validation.

storage: remove unnecessary debug_assert

---

src/bin/nydusd/fs_cache.rs

we should make sure blob cache init thread get wlock before user daemon
get first ondemand req.
Fixes: 82f67123192c ("nydusd: make copen always return right file size")
Suggested-by: Jiang Liu <gerry@linux.alibaba.com>

nydusd: fix race window in copen handler

---

storage/src/backend/connection.rs
storage/src/cache/cachedfile.rs
storage/src/cache/mod.rs
storage/src/cache/state/blob_state_map.rs
storage/src/cache/state/mod.rs
storage/src/cache/worker.rs
storage/src/device.rs
storage/src/remote/client.rs

Optimize performance by fix a bug in prefetch. With these patches applied, it performs as better as v5, but reduce half of network IO requests to backend storage system.

Optimize performance by fix a bug in prefetch 

---

src/bin/nydus-image/unpack/pax/test.rs
storage/src/backend/localfs.rs
storage/src/backend/mod.rs
storage/src/backend/oss.rs
storage/src/backend/registry.rs
storage/src/cache/cachedfile.rs
storage/src/cache/dummycache.rs
storage/src/cache/worker.rs
storage/src/factory.rs
storage/src/meta/mod.rs
storage/src/test.rs

The special prefetch in localfs is not actually used, but causes
much complexity, so remove it.

storage: remove localfs based prefetch

---

src/bin/nydus-image/unpack/pax.rs

When a symlink file in nydus with an absolute path like `/usr/bin/touch -> /bin/touch`,
unpack will output the tar with symlink file like `/usr/bin/touch -> bin/touch`,
this behavior causes that the symlink is broken.

builder: fix broken symlink in unpack

---

rafs/src/fs.rs
rafs/src/metadata/cached_v5.rs
rafs/src/metadata/direct_v5.rs
rafs/src/metadata/direct_v6.rs
rafs/src/metadata/md_v5.rs
rafs/src/metadata/md_v6.rs
rafs/src/metadata/mod.rs
storage/src/device.rs

Improve prefetch performance further, now v5 image performs as better as 1.1.2.

Improve prefetch performance further

---

.github/workflows/it.yml
.github/workflows/release.yml
Makefile

The nydus-cached functionality was moved to nydusd daemon mode,
so we don't need to compile this binary in CI anymore.

ci: remove nydus-cached binary build

---

storage/src/cache/filecache/mod.rs

indexed_chunk_map
Rafs v6 chunks' info from filesystem only has blob_id and chunk_index.
So storage layer has to convert it. But current code only load blob
meta with disable_indexed_map=false, which only affets v5 image
It cause nydusd panic when do prefetch or fs io
---
[2022-08-02 14:52:45.103790 +08:00] INFO [api/src/http.rs:778] <--- Get Uri { string: "/api/v1/metrics/blobcache" }
1: nydus_storage::cache::BlobIoMergeState<F>::merge_and_issue
2: <nydus_storage::cache::cachedfile::FileCacheEntry as nydus_storage::cache::BlobCache[2022-08-02 14:52:45.103943 +08:00] INFO [api/src/http.rs:783] ---> Get Status Code: OK, Elapse: Ok(157.427µs), Body Size: 365
>::prefetch
3: nydus_storage::device::BlobDevice::prefetch
4: nydus_rafs::fs::Rafs::do_prefetch::{{closure}}
5: …

storage: convert chunk info per as blob meta regardless of

---

storage/src/cache/cachedfile.rs

The original algorithm uses end as the last data chunk index
caused panic since` end` can be equal to pending.len().
Moreover, `end` chunk's pending flag is not cleared after the chunk
is fetched from remote storage

storage: fix range prefetch algorithm from panic and io hang

---

storage/src/device.rs

Only copy strings when necessary

rafs: try best to reduce memory overhead

---

src/bin/nydus-image/builder/directory.rs
src/bin/nydus-image/core/node.rs

Since different filesystems may calculate different directory sizes,
for RAFS v5, nydus needs to implement the directory size calculation
itself to achieve reproducible builds on different hosts or filesystems.
For RAFS v6, the directory size is calculated by actual entries.

builder: fix rafs v5 dir size for reproducible build

---

src/bin/nydus-image/builder/directory.rs
src/bin/nydus-image/builder/mod.rs
src/bin/nydus-image/builder/stargz.rs
src/bin/nydus-image/core/blob.rs
src/bin/nydus-image/core/blob_compact.rs
src/bin/nydus-image/core/bootstrap.rs
src/bin/nydus-image/core/context.rs
src/bin/nydus-image/core/node.rs
src/bin/nydus-image/core/prefetch.rs
src/bin/nydus-image/core/tree.rs
storage/src/cache/cachedfile.rs

Code style and comment related changes, should be no functional changes:
1) refine comments
2) rename Node::set_v5_inode_blocks() to set_inode_block()
3) make DirectoryBuilder::set_v5_dir_size() take values
4) rename decompress_xxx to uncompress_xxx.
5) replace compress/uncompress with compressed/uncompressed
6) add common prefix for v6 related methods of Node.
7) add "v6" prefex for v6 dedicated fields in Tree

Clean up code for v2.1

---

storage/src/backend/connection.rs
storage/src/backend/registry.rs

Avoid allocating memory and fill it within IO path.

registry: avoid unnecessary memory allocation

---

contrib/nydus-test/framework/nydus_anchor.py
contrib/nydus-test/framework/rafs.py
contrib/nydus-test/functional-test/test_nydus.py

OSS related artifacts are not necessary and make suitable nydusd config for rafs v6

Adapt further to rafs v6 format test

---

src/bin/nydus-image/builder/directory.rs
src/bin/nydus-image/core/node.rs

Method set_v5_dir_size() should be generic and may be used by other
builder too, so move it to Node.

nydus-image: move set_v5_dir_size() to Node

---

src/bin/nydus-image/core/bootstrap.rs
src/bin/nydus-image/core/node.rs

Hardlinks in RAFS v6 have different inode numbers. To fix it, we need to set correct offset for hardlinks.
Signed-off-by: yixiaojie <yixiaojie@bytedance.com>

nydus-image: fix incorrect node offset in rafs v6 for hardlinks

---

src/bin/nydus-image/core/node.rs

There are some cases missing the has_attr flag, it should be set
when there are extended attributes.

nydus-image: ensure has_attr flag is set correctly

---

contrib/nydusify/cmd/nydusify.go
contrib/nydusify/examples/converter/main.go
contrib/nydusify/pkg/checker/checker.go
contrib/nydusify/pkg/converter/converter.go
contrib/nydusify/pkg/converter/provider/remote.go
contrib/nydusify/pkg/remote/remote.go
contrib/nydusify/pkg/utils/utils.go
contrib/nydusify/tests/nydusify.go

An error is thrown when converting image to https registry with
self-signed TLS cert:
```
failed to do request: x509: certificte signed by unknown authority
```
1. Fixed it by retrying with `InsecureSkipVerify` option, if users specify
`--source-insecure` or `--target-insecure` option, then skips verifying
HTTPS certs.
2. Allows falling back to plain HTTP for registry if https request failed.
Tested to enable `--source-insecure` and `--target-insecure`:
- Tested with http registry with domain name like `registry.com`;
- Tested with https registry with self-signed TLS cert;
Tested to disable `--source-insecure` and `--target-insecure`:
- Tested with https registry with CA-signed TLS cert;
- Tested with http registry with localhost/127.0.0.1 address;
Signed-off-by: Yan Song …

nydusify: skip tls verification

---

storage/src/cache/cachedfile.rs
storage/src/cache/dummycache.rs
storage/src/cache/mod.rs
storage/src/cache/worker.rs

The blob cache manager is associated with prefetch state, so we don't
have to clone it and pass it everywhere.
Thus simplifying code.

storage: reflect prefetch state from each blob cache object

---

storage/src/cache/cachedfile.rs
storage/src/cache/dummycache.rs
storage/src/cache/mod.rs
storage/src/cache/worker.rs

Simplify BlobCache::is_prefetch_active() related code and remove
BlobCache::get_prefetch_state().

storage: simplify BlobCache::is_prefetch_active()

---

rafs/src/metadata/cached_v5.rs
rafs/src/metadata/layout/v5.rs
rafs/src/metadata/md_v5.rs
src/bin/nydus-image/core/node.rs
storage/src/device.rs

Methods like file_offset() are not required in the storage layer. So we early fill the io vec with BlobChunkInfo directly to
get rid of the chunk conversion. User IO file offset and in-chunk offset mapping is provided in io vec control block. This is the first step in trying to reduce storage layer complications by simplify essential IO structures and remove everywhere `as_base`

Get rid of BlobIoChunk::V5

---

contrib/nydus-test/functional-test/test_api.py
contrib/nydus-test/functional-test/test_image_compatibility.py
contrib/nydus-test/functional-test/test_layered_image.py
contrib/nydus-test/functional-test/test_nydus.py

Somehow, prefetch is not started very fast ending up with zero
prefetch metrics retained.
**This is fixing broken nightly CI**

nydus-test: delay for some time before verifying prefetch metrics

---

src/bin/nydus-image/core/node.rs

Panic when the size of a regular file exceeds 4GB:
```
thread 'main' panicked at 'attempt to multiply with overflow': src/bin/nydus-image/core/node.rs:371
```
Fix it by changing `(chunk_size * i) as u64` to `chunk_size as u64 * i as u64`.
Fix https://github.com/dragonflyoss/image-service/issues/662

builder: fix panic on building big file

---

Makefile
src/bin/nydusctl/commands.rs
src/bin/nydusctl/main.rs

Now nydusd can work as a cachefilesd. So the cache is a moregeneric name.

Rename nydusctl subcommand

---

api/src/http.rs
storage/src/backend/connection.rs

Stop printinging a warning message for each fallback IO.

storage/backend: use rate log to prevent tons of logs

---

.github/workflows/convert.yml
contrib/nydusify/pkg/checker/checker.go
contrib/nydusify/pkg/checker/rule/filesystem.go
contrib/nydusify/tests/e2e_test.go
contrib/nydusify/tests/nydusify.go
contrib/nydusify/tests/registry.go

For registry backend, we can infer the type and the config automatically
so that users don't need to specify these two options.
Signed-off-by: wraymo <raywangv@gmail.com>

nydusify: infer BackendType and BackendConfig

---

storage/src/backend/connection.rs
storage/src/backend/oss.rs
storage/src/backend/registry.rs

Try the best to reduce overhead in the IO path in the core registry connection code.

storage: avoid allocating memory when requesting registry

---

src/bin/nydusctl/commands.rs

Make it more human readable
Then it looks like:
```
Backend Type:       "registry"
Read Amount:        327600892 Bytes (312.42455673217773 MB)
Read Count:         407
Read Errors:        0
Block Sizes:             <1K     1K~     4K~     16K~    64K~    128K~   512K~   1M~
Average Latency(millis): 19      34      13      4       8       7       11      17
Block Sizes:             <1K     1K~     4K~     16K~    64K~    128K~   512K~   1M~
Request Count:           5       1       3       11      16      53      222     96
```

nydusctl: beautify backend metrics display

---

src/bin/nydusctl/commands.rs

It helps to analyze rafs performance
Then it shows rafs layer read latency distribution which shows that most read ops' latency is located at range [0, 1ms]. It means storage layer prefetch helps a lot.
```
Read Latency:   <1ms    ~20ms   ~50ms   ~100ms  ~500ms  ~1s     ~2s     2s~
Reads Count:    1066    4       8       0       0       0       0       0
FOP Counters:
Getattr(148) Readlink(24) Open(0) Release(0) Read(1078) Statfs(0) Getxattr(115) Listxattr(2)
Opendir(0) Lookup(215) Readdir(2) Readdirplus(2) Access(0) Forget(0) BatchForget(0)
```

nydusctl: print rafs read op latency distribution

---

src/bin/nydus-image/builder/directory.rs
src/bin/nydus-image/builder/stargz.rs
src/bin/nydus-image/core/blob.rs
src/bin/nydus-image/core/blob_compact.rs
src/bin/nydus-image/core/bootstrap.rs
src/bin/nydus-image/core/chunk_dict.rs
src/bin/nydus-image/core/context.rs
src/bin/nydus-image/core/layout.rs
src/bin/nydus-image/core/node.rs

During the build process, if a blob in the chunk dict is never used
for de-duplication, the blob is still referenced in the blob table
of final bootstrap.
This causes that the image will reference to some redundant blobs,
and these blobs will not be GC-ed properly.
This fixup is to add only the blobs actually used in the chunk dict
to blob table during the build process.

builder: only reference the blob actually used in the chunk dict

---

rafs/src/metadata/direct_v6.rs

Implement binary search in rafs/src/metadata/direct_v6.rs
get_child_by_name() to accelerate entry search.
Signed-off-by: yixiaojie <yixiaojie@bytedance.com>

rafs: optimize entry search in rafs v6

---

Cargo.lock
app/Cargo.toml
app/src/lib.rs
blobfs/src/lib.rs
src/bin/nydus-image/main.rs
src/bin/nydusd/main.rs
tests/smoke.rs

add log rotation to nydusd and nydus-image,
default set to 0 (disable log rotation).
This PR is addressing #668 

add log rotation

---

Cargo.lock
rafs/Cargo.toml
utils/Cargo.toml

Upgrade to `lz4-sys 1.9.4` to fix security vulnerability detected by
`cargo deny check`:
```
error[A001]: Memory corruption in liblz4
┌─ /github/workspace/Cargo.lock:98:1
│
98 │ lz4-sys 1.9.3 registry+https://github.com/rust-lang/crates.io-index
│ ------------------------------------------------------------------- security vulnerability detected
│
= ID: RUSTSEC-2022-0051
= Advisory: https://rustsec.org/advisories/RUSTSEC-2022-0051
= lz4-sys up to v1.9.3 bundles a version of liblz4 that is vulnerable to
[CVE-2021-3520](https://nvd.nist.gov/vuln/detail/CVE-2021-3520).
Attackers could craft a payload that triggers an integer overflow upon
decompression, causing an out-of-bounds write.
The flaw has been corrected in version v1.9.4 of liblz4, which is included
in lz4-sys 1.9.4.
= Announcement: …
```

deps: fix security vulnerability for lz4-sys

---

contrib/nydus-test/conftest.py
contrib/nydus-test/framework/nydus_anchor.py

When teardown, anchor decides whether to clean environment
by if nydusd is ever assigned.

nydus-test: don't assign nydusd to anchor

---

contrib/nydusify/pkg/checker/checker.go
contrib/nydusify/pkg/checker/rule/filesystem.go
contrib/nydusify/pkg/remote/remote.go

Based on the patch https://github.com/dragonflyoss/image-service/pull/616, for nydusify check subcommand, its option 
`--target-insecure` only enable `skip_verify` field of nydusd backend
config, it no longer affects `scheme` field to use `http` or `https`.
So we should populate the `scheme` field based on whether or not we
retried HTTP in parser.

nydusify: fix incorrect http scheme for checker

---

contrib/nydus-test/nydusd_client.py

Other wise, it generates wrong api endpoint
[2022-08-29 17:09:30,125] INFO [nydusd_client - 208:get_wait_daemon] - {'code': 'UNDEFINED', 'message': 'NoRoute'}
[2022-08-29 17:09:30,125] ERROR [nydusd_client - 219:get_wait_daemon] - Fail to request to nydus, will  retry. 'state'
[2022-08-29 17:09:30.227280 +08:00] INFO [api/src/http.rs:778] <--- Get Uri { string: "/apidaemon" }

nydus-test: use url builder to query

---

contrib/nydus-test/README.md

Add the missing parameter 'artifacts' for anchor_conf.json in README.md,
which will cause an error when generating rootfs. KeyError: 'artifacts'

nydus-test: add the missing parameter 'artifacts'

---

src/bin/nydus-image/builder/directory.rs
src/bin/nydus-image/builder/stargz.rs
src/bin/nydus-image/core/blob_compact.rs
src/bin/nydus-image/core/context.rs
src/bin/nydus-image/main.rs
src/bin/nydus-image/merge.rs

So that we can inspect real blob list referenced by final
bootstrap after the merge is complete.
For these blobs, when chunk dict is enabled, part of them
are from original layers, part from chunk dict bootstrap.

builder: output blob list for merge subcommand

---

src/bin/nydusd/api_server_glue.rs

remove unix socket before exiting,
it also works when getting SIGINT & SIGTERM signals.
This PR addressing #704 

nydusd: remove unix socket before exiting

---

.github/workflows/it.yml
.github/workflows/release.yml
Makefile
contrib/nydus-backend-proxy/Makefile
misc/musl-static/Dockerfile
misc/nydus-smoke/Dockerfile

Release binaries for linux/ppc64le and linux/riscv64 arch.
A successful release: https://github.com/imeoer/image-service/actions/runs/2954225904

misc: add more release archs

---

rafs/src/fs.rs
src/bin/nydusd/main.rs

The 2nd commit relies on the fuse-backend-rs PR https://github.com/cloud-hypervisor/fuse-backend-rs/pull/91 .

Fix opendir cache issue for rafs, passthroughfs, and the hybrid mode

---

src/bin/nydus-image/core/node.rs
storage/src/meta/mod.rs

The `uncompressed_offset` is the next position to write chunks to the uncompressed blob cache. It is already increased before adding blob size.
fixes https://github.com/dragonflyoss/image-service/issues/693

Fix blob uncompressed size

---

storage/Cargo.toml

Compiling storage alone will fail.
```
error[E0432]: unresolved import `tokio::time`
--> storage/src/cache/worker.rs:12:12
|
12 | use tokio::time::interval;
|            ^^^^ could not find `time` in `tokio`
error[E0432]: unresolved import `tokio::time`
--> storage/src/factory.rs:24:5
|
24 |     time,
|     ^^^^ no `time` in the root
```
Signed-off-by: wanglei01 <wllenyj@linux.alibaba.com>

storage: fix compile error

---

Cargo.lock

Update dbs-uhttp to v0.3.1, which solves some mio related bugs.

dep: update dbs-uhttp to v0.3.1

---

src/bin/nydusd/main.rs

So that it is clear that the subcommand means to run nydusd in a global single instance mode.

nydusd: rename daemon subcommand to singleton

---

Makefile
contrib/nydusify/cmd/nydusify.go
contrib/nydusify/pkg/backend/backend.go
contrib/nydusify/pkg/backend/oss.go
contrib/nydusify/pkg/cache/cache.go
contrib/nydusify/pkg/compactor/compactor.go
contrib/nydusify/pkg/converter/cache.go
contrib/nydusify/pkg/packer/artifact.go
contrib/nydusify/pkg/packer/artifact_test.go
contrib/nydusify/pkg/packer/packer.go
contrib/nydusify/pkg/packer/packer_test.go
contrib/nydusify/pkg/packer/pusher.go
contrib/nydusify/pkg/packer/pusher_test.go

Improve nydusify build subcommand and fix some resource leakages.

Improve nydusify build subcommand

---

api/src/http.rs
src/bin/nydus-image/unpack/mod.rs
storage/src/backend/localfs.rs

The readehead functionality in localfs backend has been removed, so clean up the configuration.

storage: remove readahead configuration from LocalFsConfig

---

rafs/src/lib.rs
src/bin/nydus-image/unpack/mod.rs

Introduce iterator to walk inode of a rafs filesystem.

rafs: introduce iterator to walk inode of a rafs filesystem

---

api/src/http.rs
src/bin/nydusd/blob_cache.rs

In fact, it is configuring how a single blob is being prefetched.

api: rename blob cache entry config's fs_prefetch

---

src/bin/nydusd/main.rs

Let the singleton daemon exits when received SIGINT.

nydusd: fix a bug in handling singleton subcommand

---

contrib/nydusify/pkg/backend/backend.go
contrib/nydusify/pkg/backend/oss.go
contrib/nydusify/pkg/backend/registry.go
contrib/nydusify/pkg/converter/converter.go
contrib/nydusify/pkg/packer/pusher_test.go

We have used `PutObject` to upload oss before, so if there is any failure during
conversion process, it will cause the uploaded blob to be left on oss, and these
blobs are hard to be GC-ed, so we need always to use the multipart upload, and should
call the `AbortMultipartUpload` method to prevent blob residue as much as possible
once any error happens during conversion process.

nydusify: abort oss blob upload if conversion failed

---

src/bin/nydusd/main.rs

We have already rename subcommand from daemon to singleton We'd better to rename the related functions and log messages.

nydusd: make thier names consistent in singleton mode

---

Cargo.lock
Cargo.toml
api/src/http.rs
blobfs/Cargo.toml
rafs/Cargo.toml
rafs/src/metadata/mod.rs
src/lib.rs
storage/Cargo.toml

Remov dependency on serde-with by open-coding, which gets rid of:
Removing darling v0.13.4
Removing darling_core v0.13.4
Removing darling_macro v0.13.4
Removing ident_case v1.0.1
Removing serde_with v1.14.0
Removing serde_with_macros v1.5.2
Removing strsim v0.10.0

dependency: remove dependency on serde-with

---

Cargo.toml
Makefile
blobfs/src/lib.rs
contrib/nydusify/pkg/checker/tool/nydusd.go
misc/nydus-smoke/Dockerfile
misc/nydusify-smoke/Dockerfile
src/bin/nydusd/main.rs
src/bin/nydusd/upgrade.rs
storage/src/backend/registry.rs
storage/src/lib.rs
storage/src/meta/mod.rs
tests/nydusd.rs

Add fuse and virtiofs to daemon subcommand.
Signed-off-by: uran0sH <huangwenyuu@outlook.com>

Unify fusedev and virtiofs frontend

---

.github/workflows/ci.yml
Makefile
contrib/nydus-test/README.md
contrib/nydus-test/framework/nydus_anchor.py
docs/containerd-env-setup.md
docs/nydus-fscache.md
docs/nydus_with_macos.md
rafs/src/metadata/layout/v5.rs
tests/builder.rs
tests/inspect.rs
tests/nydusd.rs

Clean up fusedev and enhance makefile targets for macos

Clean up fusedev and enhance makefile targets for macos

---

api/src/http.rs
storage/src/backend/connection.rs
storage/src/backend/registry.rs

Add mirror support for nydusd, 
corresponding configurations: device.backend.config.mirrors
```json
[ {
"host": "http://dragonfly.io",
"headers": {
"X-Dragonfly-Registry": "https://docker.io",
}
},
]
```
this PR is addressing #716

storage: add mirror support

---

contrib/nydusify/tests/image_test.go
misc/top_images/image_list.txt

To fix the broken test: https://github.com/dragonflyoss/image-service/actions/runs/3124279728
```
Failed to convert: Parse source image: Parse source image:
resolve image: docker.io/library/java:latest: not found
```
The java/openjdk image is officially deprecated and all users
are recommended to use suitable replacements, related info:
https://hub.docker.com/_/openjdk
https://github.com/docker-library/openjdk/issues/505

test: replace java image with amazoncorretto

---

.github/workflows/ci.yml
.github/workflows/release.yml
Makefile
contrib/ctr-remote/Makefile
contrib/docker-nydus-graphdriver/Makefile
contrib/nydus-overlayfs/Makefile
contrib/nydusify/Makefile

Unify the makefiles for contrib components by use the same template. Also refine the global makefile targets to make them symmetric.

makefile: unify the makefiles for contrib components

---

contrib/nydusify/pkg/checker/output.go

In order to debug oci and nydus image more friendly when use `nydusify check` command, we'd better output `oci_index.json` and `nydus_index.json` file.

nydusify: output nydus & oci manifest index for check

---

.github/workflows/release.yml

Refine release workflow for macos by relying on the makefile to do the actual work.

workflow: refine release workflow for macos

---

contrib/nydus-test/conftest.py
contrib/nydus-test/framework/rafs.py
contrib/nydus-test/functional-test/test_erofs.py

Adapts to recent mainline changes:
1. nydusify makefile target has renamed to `make release`
2. nydusd subcommand daemon has renamed to singleton

Adapt nydus test

---

Makefile

The macos version of install command doesn't support option `-D`, so emulate it by "mkdir -p".

makefile: fix invalid "install -D" option on macos

---

Makefile

Fix a typo in of INSTALL_DIR_PREFIC, it should be INSTALL_DIR_PREFIX.

makefile: fix a typo in of INSTALL_DIR_PREFIC

---

api/src/http.rs
storage/src/backend/connection.rs

Dragonfly supports configuration `useHTTPS` while
work as a http proxy. In this mode, nydusd can access dfdaemon via http while dfdaemon is accessing registry using https. So CA is not needed to be passed to dfdaemon.
The limit is that registry scheme must be set to http ending up with reading the original registry failure when fallback.
With configuring proxy with use_http, it will replace the scheme when sending requests to dfdaemon.
Addressing https://github.com/dragonflyoss/image-service/issues/723

storage: support configure proxy use_http

---

.github/workflows/release.yml

For example:
```
Nydus Image Service v2.1.0-rc.3.1
Mirror (update in 10 min): https://registry.npmmirror.com/binary.html?path=nydus/v2.1.0-rc.3.1/
...
```
A successful release can be found here: https://github.com/imeoer/image-service/releases/tag/v2.1.0-rc.3.6

release: add npm mirror url into release note

---

contrib/nydus-test/framework/rafs.py
rafs/src/metadata/direct_v6.rs
rafs/src/metadata/layout/v6.rs
rafs/src/metadata/md_v6.rs
rafs/src/metadata/mod.rs
src/bin/nydus-image/core/bootstrap.rs
src/bin/nydus-image/core/prefetch.rs
src/bin/nydus-image/inspect.rs

1. rafs v5 and v6 has different root inode numbers. So use the real root inode number when getting path from inode number.
2. rafs v6's inode number can't be decided until the end of dumping bootstrap. So don't record inode number in readadhead patterns anymore, use node index instead.
3. enrich print nydus-image inspect 
fixes https://github.com/dragonflyoss/image-service/issues/760

Enrich nydus-image print, fix prefetch table layout and other couple of fixes

---

Cargo.lock
deny.toml
rafs/Cargo.toml
storage/Cargo.toml
storage/src/backend/oss.rs
storage/src/cache/worker.rs
storage/src/lib.rs

Reduce dependence of nydus-storage crate

storage: reduce dependence crates

---

utils/src/filemap.rs
utils/src/lib.rs
utils/src/mpmc.rs

Add FileMapState to map a file region into current process, so we could access the memory mapped region in safe way.

util: add FileMapState to map a file region into current process

---

rafs/src/fs.rs
rafs/src/lib.rs
rafs/src/metadata/cached_v5.rs
rafs/src/metadata/direct_v5.rs
rafs/src/metadata/direct_v6.rs
rafs/src/metadata/layout/mod.rs
rafs/src/metadata/layout/v5.rs
rafs/src/metadata/md_v5.rs
rafs/src/metadata/mod.rs
rafs/src/metadata/noop.rs
rafs/src/mock/mock_chunk.rs
rafs/src/mock/mock_inode.rs
rafs/src/mock/mock_super.rs
src/bin/nydus-image/core/bootstrap.rs
src/bin/nydus-image/core/node.rs
src/bin/nydus-image/core/tree.rs
src/bin/nydus-image/inspect.rs
src/bin/nydus-image/merge.rs
src/bin/nydus-image/unpack/mod.rs
src/bin/nydus-image/unpack/pax.rs
src/bin/nydus-image/unpack/pax/test.rs
src/bin/nydusd/fusedev.rs
storage/src/cache/state/blob_state_map.rs
storage/src/device.rs
storage/src/meta/mod.rs
storage/src/test.rs
tests/builder.rs
utils/src/compress/mod.rs
utils/src/digest.rs

The `RafsInode` is designed according to Rafs v5, which causes some problems when enabling Rafs v6.
So split it into `RafsInode` and `RafsInodeExt. Among those, `RafsInode` is used to provide methods which are generic to v5/v6 and runtime/builder, `RafsInodeExt` provides version specific methods or methods for builder.
Along the way also do:
1) clean up some unused code
2) rename RAFS_ROOT_INODE to RAFS_V5_ROOT_INODE
3) add more unit test cases
4) add some helpers function related to v5 to simplify implementation

Split `RafsInode` into `RafsInode` and `RafsInodeExt`

---

contrib/nydusify/pkg/packer/packer.go

1. Prepare configuration file used for pack command. {
"bucket_name": "XXX",
"endpoint": "XXX",
"access_key_id": "XXX",
"access_key_secret": "XXX",
"meta_prefix": "nydus_rund_sidecar_meta",
"blob_prefix": "blobs"
}
2. Pack by nydusify sudo contrib/nydusify/cmd/nydusify pack \
--source-dir test \
--output-dir tmp \
--name ccx-test \
--backend-push \
--backend-config-file backend-config.json \
--backend-type oss \
--nydus-image target/debug/nydus-image
3. Got error FATA[2022-10-08T18:06:46+08:00] failed to push pack result to remote: failed to put metafile to remote: split file by part size: open tmp/tmp/ccx-test.meta: no such file or directory
The path of bootstrap file, which is to upload, is wrong.
Use imageName as req.Meta, which is bootstrap file to upload.
Signed-off-by: 泰友 …

fix: nydusify pack fail

---

rafs/src/metadata/cached_v5.rs
rafs/src/metadata/layout/mod.rs
rafs/src/metadata/layout/v5.rs
rafs/src/metadata/layout/v6.rs
src/bin/nydus-image/builder/stargz.rs

Extended attribute's key/name may not be UTF-8 encoded, so don't assume that.

rafs: fix bug in handling extended attributes

---

src/bin/nydusd/main.rs

Now the default value is only 1, it affects performance.

nydusd: enlarge default fuse server threads

---

Cargo.lock
Cargo.toml
app/README.md
app/build.rs
app/src/lib.rs
src/bin/nydus-image/main.rs
src/bin/nydusctl/main.rs
src/bin/nydusd/main.rs

We only need to git tag to release a version without modifying
the version field in Cargo.toml and Cargo.lock.

release: update version on build automatically

---

storage/src/cache/cachedfile.rs

for fscache ondemand path, if some requested chunks are set to pending by prefetch threads, and wait them timeout, will casue EIO to container side.
retry the timeout chunks on ondemand path, minimize EIOs.

storage: retry timeout chunks for fscache ondemand path

---

contrib/nydusify/pkg/checker/rule/filesystem.go
contrib/nydusify/pkg/checker/tool/image.go

```
Nydusify check subcommand will check the consistency of
OCI image and nydus image by mounting (overlayfs or nydusd).
For the OCI image with a single layer, we should use bind
mount instead of overlay to mount rootfs, otherwise an error
will be thrown like:
wrong fs type, bad option, bad superblock on overlay, missing
codepage or helper program, or other error.
This commit also refine the codes for image.Mount/image.Umount.
```

nydusify: fix overlay error for image with single layer

---

src/bin/nydus-image/core/bootstrap.rs
src/bin/nydus-image/core/prefetch.rs

Nydusd is performing prefetch by finding all inodes matching their inode numbers.

nydus-image/v5: prefetch table should contain inode numbers rather its index

---

rafs/src/lib.rs
src/bin/nydus-image/builder/directory.rs
src/bin/nydus-image/builder/stargz.rs
src/bin/nydus-image/core/blob.rs
src/bin/nydus-image/core/blob_compact.rs
src/bin/nydus-image/core/bootstrap.rs
src/bin/nydus-image/core/context.rs
src/bin/nydus-image/core/prefetch.rs
src/bin/nydus-image/main.rs
src/bin/nydus-image/merge.rs
src/bin/nydus-image/stat.rs
src/bin/nydus-image/validator.rs
storage/src/cache/worker.rs
utils/src/digest.rs

Second part to refine nydus-image

Second part to refine nydus-image

---

rafs/src/metadata/inode.rs
rafs/src/metadata/layout/v5.rs
src/bin/nydus-image/builder/stargz.rs
src/bin/nydus-image/core/node.rs
src/bin/nydus-image/main.rs
src/bin/nydus-image/unpack/pax/test.rs
storage/src/lib.rs
storage/src/meta/mod.rs
tests/builder.rs

Improve implementation to convert stargz TOC into RAFS fs.

Improve implementation to convert stargz TOC into RAFS fs

---

api/src/http.rs
docs/nydusd.md
storage/src/backend/connection.rs
storage/src/backend/oss.rs
storage/src/backend/registry.rs

In some scenarios(e.g. P2P/Dragonfly), sending an authorization request to the mirror will cause performance loss. We add parameter auth_through. When auth_through is false, nydusd will directly send non-authorization request to original registry.
Fixes https://github.com/dragonflyoss/Dragonfly2/issues/1678

fix mirror's performance issue

---

src/bin/nydusd/main.rs
storage/src/cache/filecache/mod.rs

Add command line option "--localfs-dir" to "nydusd fuse", so we could mount an RAFS filesystem by
nydusd -M ./mnt -D ./localfs-dir -B meta-blob-id

nydusd: simplify the way to use localfs for fuse subcommand

---

.github/workflows/it.yml

By default, pytest will continue executing test even current test fails. It's hard to tell what to happen on such a environment. And it makes it hard to investigate the first failed case.

action/nydus-test: stop on the first test failure

---

.github/workflows/ci.yml

Signed-off-by: Gaius <gaius.qi@gmail.com>

chore: ci action adds paths-ignore

---

Cargo.lock
Cargo.toml
rafs/src/metadata/layout/v5.rs
rafs/src/metadata/layout/v6.rs
src/bin/nydus-image/core/prefetch.rs

Now, nydus prefetch files with the order of index. This method is not accurate. We already get accessed files list for workload. Hence, we can prefetch files based on the order they are accessed.
Prefetch table for rafs v5 image (`nydus-image inspect` for rafs v6 is not work, repairing...):
Accessed files:
Now, we avoid sorting prefetch table, maybe add a parameter for this option.
This PR is addressing the step 1 of #807 
Related to https://github.com/containerd/nydus-snapshotter/pull/228

optimize prefetch table for workload

---

src/bin/nydus-image/core/bootstrap.rs

Now, the prefetch table size in rafs v6 SuperBlock is the number of prefetch files list. It is incorrect when the prefetch files list contains a path that does not exist.
This PR is addressing #817 

nydus-image: fix prefetch table size for rafs v6

---

src/bin/nydusd/main.rs

Change ArgMatches::get_many::<&str> to
ArgMatches::get_many::<String> in values_of to fix "Could not downcast to &str, need to downcast to alloc::string::String"
issue: https://github.com/dragonflyoss/image-service/pull/822#issuecomment-1296546892
Signed-off-by: Wenyu Huang <huangwenyuu@outlook.com>

fixup! Upgrade clap to 4.0

---

contrib/nydusify/pkg/backend/oss.go
contrib/nydusify/pkg/packer/packer.go
contrib/nydusify/pkg/packer/pusher.go
contrib/nydusify/pkg/packer/pusher_test.go

泰友 (3):
fix: nydusify pack fail
refact: use specified object prefix and meta prefix directly
fix: miss oss file of nydusify packer

Backport 3 patches for stable/v2.1

---

contrib/nydus-test/framework/distributor.py
contrib/nydus-test/framework/utils.py
contrib/nydus-test/functional-test/test_nydus.py
contrib/nydus-test/functional-test/test_nydusify.py

enable a skipped test and fix that nydusify tests are broken

improve nydus-test cases

---

contrib/nydusify/examples/manifest/manifest.json
contrib/nydusify/pkg/cache/cache.go
contrib/nydusify/pkg/converter/manifest.go
contrib/nydusify/pkg/utils/constant.go

Image with layers more than 64 can't be pulled by containerd since the label is exceeding the label size limitation 4096bytes.
We should figure out another way to do GC in nydus-snapshotter

nydusify: drop label "nydus-blob-ids" from meta layer

---

api/src/http.rs
docs/nydusd.md
storage/src/backend/connection.rs
storage/src/backend/registry.rs

Currently, the mirror is set to unavailable if the failed times reach failure_limit. We added mirror health checking, which will recover unavailable mirror server. The failure_limit indicates the failed time at which the mirror is set to unavailable, The health_check_interval indicates the time interval to recover the unavailable mirror and the ping_url is the endpoint for checking mirror server health.
This PR is addressing #765 

storage: add mirror health checking support

---

README.md
docs/containerd-env-setup.md
docs/nydusd.md

docs: add d7y doc link

---

api/src/http.rs
docs/nydusd.md
storage/src/backend/connection.rs
storage/src/backend/registry.rs

https://github.com/dragonflyoss/image-service/pull/800

[backport to stable/v2.1] storage: add mirror health checking support 

---

app/src/lib.rs
contrib/nydusify/pkg/checker/tool/builder.go
contrib/nydusify/pkg/checker/tool/inspector.go
rafs/src/metadata/layout/v5.rs
rafs/src/metadata/layout/v6.rs
rafs/src/metadata/mod.rs
src/bin/nydus-image/core/context.rs
src/bin/nydus-image/main.rs
tests/builder.rs
tests/inspect.rs

Change default configuration for `nydus-image create` by
1) change default compressor from lz4_block to zstd
2) change default hash algorithm from blake3 to sha256
3) change default fs-version from 5 to 6
4) limit aligned-chunk to RAFS v5
Also tune output of `nydus-image create`  and now it becomes readable:
```
root@5ad838c8bf7b:/nydus# target/debug/nydus-image create -t directory -D images/ -J output.json src/
[2022-10-17 16:04:52.787992 +00:00] INFO rafs superblock features: HASH_SHA256 | EXPLICIT_UID_GID | COMPRESSION_ZSTD
[2022-10-17 16:04:52.824325 +00:00] INFO successfully build RAFS filesystem: 
meta blob path: images/6fb4d603307df0e8c523a14825181cc0c9c3de4c2797b5e341c7c489b40ab13c
data blob size: 0x22de7
data blobs: ["c508580ee90cbd543713067cb22c28b7bf444c457de5e4a53b797e5575307b7 …
```

Change default value of nydus-image and optimize output

---

rafs/src/fs.rs
rafs/src/metadata/direct_v6.rs
rafs/src/metadata/md_v5.rs
rafs/src/metadata/md_v6.rs
rafs/src/metadata/mod.rs
src/bin/nydus-image/builder/stargz.rs
src/bin/nydus-image/builder/tarball.rs
src/bin/nydus-image/core/context.rs
src/bin/nydus-image/core/node.rs
src/bin/nydus-image/main.rs
storage/src/cache/cachedfile.rs
storage/src/cache/dummycache.rs
storage/src/cache/filecache/mod.rs
storage/src/cache/fscache/mod.rs
storage/src/cache/mod.rs
storage/src/cache/state/blob_state_map.rs
storage/src/device.rs
storage/src/lib.rs
storage/src/meta/chunk_info_v1.rs
storage/src/meta/chunk_info_v2.rs
storage/src/meta/mod.rs
storage/src/meta/zran.rs
tests/smoke.rs

By adopting zlib random access algorithm, nydus can build a RAFS metadata from a targz file and use the targz file as RAFS data blob. By this way, we could associate a small RAFS metadata blob to existing OCIv1 images, which provides lazy loading and data deduplication capabilities with minimal resource overhead.
Now we have a flexible architecture to support all of OCIv1/eStargz/Nydus images as below:

Adopt zlib random access algorithm to support OCIv1 compatible nydus image

---

rafs/src/lib.rs
rafs/src/metadata/direct_v5.rs
rafs/src/metadata/direct_v6.rs
rafs/src/metadata/md_v6.rs
storage/src/cache/state/indexed_chunk_map.rs
storage/src/cache/state/persist_map.rs
utils/src/filemap.rs

Use the generic filemap from nydus-utils crate to avoid duplicated code.
Also reduce unsafe code, now there's only two unsafe left in direct v5.
Fix a lifetime related by xattr related code.

Reduce duplicated code by using utils/filemap

---

rafs/README.md
src/bin/nydusd/fs_service.rs
src/bin/nydusd/main.rs

Includes 3 minor fixes:
- nydusd: use BackFileSystem in fuse_backend_rs crate
- nydusd: fix log message
- rafs: fix crate name in readme

Some minor fixes

---

storage/src/cache/filecache/mod.rs
storage/src/cache/fscache/mod.rs

When cache file is compressed, file size is incorrectly set to uncompressed file size.

storage: correctly setup size for compressed cache file

---

src/bin/nydus-image/builder/directory.rs
src/bin/nydus-image/builder/mod.rs

The previous code generates a new empty blob for inline bootstrap mode:
```
if ctx.inline_bootstrap {
let (_, _) = blob_mgr.get_or_create_current_blob(ctx)?;
}
```
And then the empty blob will be appended to blob table although
no chunk data be generated in the current build.
This patch avoids generating this kind of redundant blob.

builder: fix redundant blob for inline bootstrap

---

rafs/src/metadata/direct_v6.rs
rafs/src/metadata/layout/v6.rs
src/bin/nydus-image/core/node.rs
storage/src/cache/filecache/mod.rs

Refine the way to build chunk map for v6, avoid RefCell and thread local variables.

rafs: refine the way to build chunk map for v6

---

src/bin/nydus-image/core/bootstrap.rs

For empty RAFS v6 filesystem, it has incorrectly non-zero prefetch table size.

rafs: fix a bug in set prefetch table size of empty filesysetem

---

storage/src/cache/filecache/mod.rs

When the compression algorithm is None, treat cache file as uncompressed even if user configures it as compressed.

storage: treat cache files as uncompressed when the algorithm is None

---

contrib/nydusify/pkg/checker/tool/builder.go
src/bin/nydus-image/main.rs

Tween the "nydus-image check" subcommand to keep compatibility with "nydus-image check --bootstrap".

nydus-image: keep compatibility with "nydus-image check --bootstrap"

---

storage/src/backend/registry.rs

This is a bug, we should backport it to `stable/v2.1` as well.

storage: fix registry to avoid print bearer auth

---

contrib/nydusify/Makefile
contrib/nydusify/cmd/nydusify.go

Print more information on git version, reversion and golang version
In addition, we rely on go arch to decide the default value of ARCH
```
./cmd/nydusify --version
Nydusify version
Version		: v2.1.0-rc.3.1-307-g522c8aac.m
Reversion	: 522c8aacef448ed9edc3c66c68250269811de7ea.m
Go version	: go1.18.7
Build time	: 2022-11-17T15:11:49
```

nydusify: beautify version print message of nydusify

---

rafs/src/metadata/mod.rs
src/bin/nydus-image/core/blob_compact.rs
src/bin/nydus-image/core/bootstrap.rs
src/bin/nydus-image/core/chunk_dict.rs
src/bin/nydus-image/main.rs
src/bin/nydus-image/merge.rs

When specifying parent bootstrap or chunk dict, we need to make sure its rafs version, compressor and digester is consistent with current configuration.
Signed-off-by: Qi Wang <mpiglet@outlook.com>

nydus-image: prevent inconsistent RAFS version/compressor/digester of parent bootstrap/chunk dict

---

Cargo.lock

dbs-uhttp has fixed the problem that http client
get EBUSY error when fetching body data from API server.

cargo: update version of dbs-uhttp

---

contrib/nydusify/cmd/nydusify.go

Nydus-image has changed its default fs version,
let nydusify adapt it.

nydusify: change default fs version to 6

---

storage/src/cache/cachedfile.rs
storage/src/cache/worker.rs

tick() will complete when the next instant reaches which is a very short time rather than 1 second.
In addition, limit the total retry times

fix too frequent retry

---

storage/src/cache/cachedfile.rs

We can bear with non-ordered equal elements when sorting.

storage: user unstable sort to reduce memory allocation

---

src/bin/nydusd/blob_cache.rs
src/bin/nydusd/fs_cache.rs
storage/src/cache/fscache/mod.rs
storage/src/device.rs
storage/src/factory.rs

We check if all blobs were created before stop prefetch threads for fscache, but FsCacheMgr is a pre-image struct, in shared domain mode, we don't know how many blobs will be created. So do not check the number of blobs.

nydusd: fix fscache prefetch threads can't exit in shared domain mode

---

storage/src/cache/cachedfile.rs
storage/src/cache/worker.rs

tick() will complete when the next instant reaches which is a very very very short time rather than 1 second.
In addition, limit the total retry times

Fix frequent retry

---

.github/workflows/release.yml

If .github/workflows/release.yml the cnt is not used.

actions: remove unused var

---

rafs/src/fs.rs
rafs/src/metadata/md_v6.rs
rafs/src/metadata/mod.rs

Perform different policy for v5 format and v6 format as rafs v6's blobs are capable to download chunks and decompress them all by themselves. For rafs v6, directly perform chunk based full prefetch to reduce requests to container registry and P2P cluster.
From benchmark test results, we can see that this PR has the same performance as the master code with significantly decreased registry requests (440->219)
--- master code
```
{"repo": "golang", "bench": "golang:latestnydusv6zstd", "pull_time": " 1.675706", "create_time": " 0.857444", "run_time": " 5.065474", "elapsed": " 7.598624"}
Backend Type:       "registry"
Read Amount:        358525072 Bytes (341.91615295410156 MB)
Read Count:         440
Read Errors:        0
Block Sizes:             <1K     1K~     4K~     16K~    64K~    128K~ …
```

rafs: prefetch based on blob chunks rather than files

---

src/bin/nydus-image/main.rs

Keep backward compatibility for old nydusd, otherwise the old nydusd will throw a panic like:
```
ERROR [error/src/error.rs:21] Error:
"blob metadata size is too big!"
at storage/src/meta/mod.rs:344
note: enable `RUST_BACKTRACE=1` env to display a backtrace
```
Try to fix: https://github.com/dragonflyoss/image-service/issues/903

builder: use chunk v1 for native directory build

---

storage/src/cache/cachedfile.rs

The refactor introduced a regression which tries to decompress an uncompressed data chunk, thus generating a warning about decompression failure. Fix it by check whether the chunk data is compressed or not.

utils: fix a warning generated when decoding chunk data

---

misc/nydus-smoke/Dockerfile

The smoke test requires a non-overlayfs-upperlayer /tmp directory, otherwise it fails at mknod char device (0,0). Let's create a volume for it.

misc: add a volume in nydus-smoke test

---

storage/src/cache/worker.rs
utils/src/metrics.rs

Record prefetch request average latency.
Calculate prefetch average bandwidth.
```json
{
"buffered_backend_size": 0,
"data_all_ready": false,
"entries_count": 0,
"partial_hits": 2657,
"prefetch_begin_time_millis": 892,
"prefetch_begin_time_secs": 1669262928,
"prefetch_cumulative_time_millis": 391525,
"prefetch_data_amount": 350224384,
"prefetch_end_time_millis": 601,
"prefetch_end_time_secs": 1669262933,
"prefetch_mr_count": 167,
"prefetch_unmerged_chunks": 0,
"prefetch_workers": 8,
"store_path": "/var/lib/containerd-nydus/cache",
"total": 2682,
"underlying_files": [
"18798c2c51ee3c0cb84f4e8dbfa3ac5b9116cfac315e3af08405363ea97a2ef7",
"d6a08dd25b46d4701c0f3221f20160563fb4b5866b6f4c915a982914adfc00de",
"3355a6911228a3502a61b1a53ce9265be17fb07934e6511fbcfdb83438e42de9", …
```

2.1 prefetch metrics

---

src/bin/nydusctl/commands.rs
storage/src/cache/worker.rs

We already add more metrics for the prefetch procedure. Make nydusctl calculate the metrics and show them in a human-readable way
Example:
```
Partial Hits:               2626
Whole Hits:                 0
Total Read:                 2684
Directory:                  "/var/lib/containerd-nydus/cache"
Files:                      ["948f80e95f4ab83ae5a202f987fee81f0c860f2e42d82689a758b57887678601","18798c2c51ee3c0cb84f4e8dbfa3ac5b9116cfac315e3af08405363ea97a2ef7","d6a08dd25b46d4701c0f3221f20160563fb4b5866b6f4c915a982914adfc00de","3355a6911228a3502a61b1a53ce9265be17fb07934e6511fbcfdb83438e42de9","004656def9b233af509fc65aa91b824071a2ed3c2ee7b1361866b9c06a403949","9957fc0906f7b4b2b1e1fc4a7a6049380bb06d72ac6919e0c06e4134ae70941e"]
Persister Buffer:           0
Prefetch Workers:           8 …
```

 Let nydusd show prefetch bandwidth and latency

---

docs/containerd-env-setup.md
storage/src/backend/registry.rs

Check the tls connection error with `wrong version number` keywords,
it's more reliable than the specific error code.

storage: enhance retryable registry http scheme

---

src/bin/nydus-image/main.rs

Blake3 is much faster than sha256, so use it as default.

nydus-image: use blake3 as default digester

---

rafs/src/metadata/cached_v5.rs
rafs/src/metadata/layout/v5.rs
rafs/src/metadata/layout/v6.rs
src/bin/nydus-image/builder/stargz.rs
src/bin/nydus-image/core/blob.rs
src/bin/nydus-image/core/blob_compact.rs
src/bin/nydus-image/core/context.rs
src/bin/nydus-image/core/node.rs
src/bin/nydus-image/main.rs
storage/src/cache/dummycache.rs
storage/src/cache/filecache/mod.rs
storage/src/cache/fscache/mod.rs
storage/src/cache/mod.rs
storage/src/device.rs
storage/src/meta/chunk_info_v1.rs
storage/src/meta/chunk_info_v2.rs
storage/src/meta/mod.rs

There are two sets of flags to control blob features: meta-flag and blob-features. Unify them into one blob-features.

rafs: unify meta-flags and blob-features

---

storage/src/cache/cachedfile.rs
storage/src/cache/dummycache.rs
storage/src/cache/filecache/mod.rs
storage/src/cache/fscache/mod.rs
storage/src/cache/mod.rs

Simplify implementation of cachefile by:
1) remove compressor and digester and directly get those info from
blob info object.
2) rename is_compressed to is_raw_data, the cache data may be
uncompressed and encrypted in future.

storage: simplify implementation of cachefile

---

storage/src/cache/cachedfile.rs
storage/src/cache/dummycache.rs

Get blob size from blob info object instead of returning invalid value.

storage: get blob size from blob info object

---

Cargo.lock
Cargo.toml
clib/Cargo.toml
clib/LICENSE-APACHE
clib/examples/nydus_rafs.c
clib/include/nydus.h
clib/src/file.rs
clib/src/fs.rs
clib/src/lib.rs

Introduce nydus-clib framework, which provides static/dynamic to integrate nydus functionality into C programs.

clib: introduce nydus-clib framework

---

src/bin/nydusctl/commands.rs
storage/src/backend/mod.rs
storage/src/cache/cachedfile.rs
utils/src/lib.rs

Introduce BackOff delayer to mitigate backend pressure
Don't retry immediately since the registry can return "too many requests" error. We'd better to be slow to retry.

Backoff retry

---

contrib/nydusify/cmd/nydusify.go
contrib/nydusify/pkg/build/workflow.go
contrib/nydusify/pkg/cache/cache.go
contrib/nydusify/pkg/checker/output.go
contrib/nydusify/pkg/checker/rule/bootstrap.go
contrib/nydusify/pkg/checker/tool/nydusd.go
contrib/nydusify/pkg/converter/manifest.go
contrib/nydusify/pkg/packer/packer.go
contrib/nydusify/pkg/packer/pusher_test.go
contrib/nydusify/pkg/parser/parser.go
contrib/nydusify/pkg/utils/archive_test.go
contrib/nydusify/pkg/viewer/viewer.go
contrib/nydusify/tests/registry.go

Interfaces in the io/ioutil package may not be available in future go versions, use new interfaces to avoid future build failures.
Signed-off-by: Qinqi Qu <quqinqi@linux.alibaba.com>

nydusify: replaces the io/ioutil API which was deprecated in go 1.16

---

api/openapi/nydus-api-v2.yaml
api/src/http.rs
api/src/http_endpoint_v2.rs
src/bin/nydusd/api_server_glue.rs
src/bin/nydusd/daemon.rs
src/bin/nydusd/fs_cache.rs
src/bin/nydusd/service_controller.rs

If only set blob_id parameter in DELETE /api/v2/blobs, will try to cull fscache blob. Then snapshotter can use this to delete fscache blob files.
https://github.com/containerd/nydus-snapshotter/pull/262

nydusd: make DELETE /api/v2/blobs API support cull fscache blob

---

Cargo.lock
misc/musl-static/Dockerfile
misc/nydus-smoke/Dockerfile
utils/Cargo.toml
utils/src/compress/zlib_random.rs

zlib-ng may have better performance than zlib, and it's api compatible with zlib.

utils: replace libz-sys with libz-ng-sys

---

api/src/config.rs
rafs/src/fs.rs

The storage manager executes data prefetch according to blob prefetch configuration, so merge fs-prefetch configuration into blob prefetch configuration.
The blob configuration has high priority.

api: merge fs-prefetch and blob-prefetch configuration

---

rafs/src/fs.rs

There's a bug which skips data chunks at blob tail.

rafs: fix a bug in fs prefetch

---

src/bin/nydusd/main.rs

Otherwise, it loses a window to gracefully exit
by umounting FUSE

nydusd: register signal handler earlier

---

storage/src/cache/cachedfile.rs
utils/src/compress/zlib_random.rs

Now the storage already supports fetching discrete chunks, so remove the incorrect assert.

storage: remove incorrect assert

---

contrib/nydus-test/functional-test/test_nydusify.py

We don't have any blocker to testing it.

nydus-test: enable test_upload_oss test

---

rafs/src/metadata/layout/v6.rs
src/bin/nydus-image/builder/mod.rs
src/bin/nydus-image/builder/tarball.rs
src/bin/nydus-image/core/blob.rs
src/bin/nydus-image/core/context.rs
src/bin/nydus-image/core/node.rs
src/bin/nydus-image/main.rs
storage/src/device.rs
storage/src/meta/zran.rs
utils/src/compress/zlib_random.rs
utils/src/lib.rs
utils/src/reader.rs

Enable generating ZRan image from tar files and also fix several bugs related to `rafs_blob_digest`.

Enable generating ZRan image from tar files

---

docs/containerd-env-setup.md
docs/nydus-fscache.md

1. --config-path "/etc/nydus/nydusd-config.fusedev.json" or "/etc/nydus/nydusd-config.fscache.json"
2. --root "/var/lib/containerd-nydus"
3. --address "/run/containerd-nydus/containerd-nydus-grpc.sock"

treewide: tidy up several paths

---

contrib/nydusify/pkg/parser/parser.go
storage/src/backend/registry.rs

When the user encounters the error x509: certificate signed by unknown authority:
* try to enable "skip_verify: true" option for nydusd;
* try to enable "--source-insecure" / "--target-insecure" option for nydusify convert/check;
Signed-off-by: Wenyu Huang <huangwenyuu@outlook.com>

nydusify & nydusd: give a briefer suggestion for insecure cert

---

rafs/src/metadata/mod.rs
src/bin/nydus-image/builder/stargz.rs
src/bin/nydus-image/core/blob_compact.rs
src/bin/nydus-image/core/bootstrap.rs
src/bin/nydus-image/core/context.rs
src/bin/nydus-image/main.rs

Currently there's a constraint that all data blobs referenced by a RAFS filesystem must use the same compression and digest algorithms. The constraint is unnecessary, so relax it.

rafs: support blobs with differrent compression/digest algorithm

---

rafs/src/metadata/direct_v6.rs

The directory for v6 is stored in the following way： ...name1name2
The first subdirectory has always been ".".
When looking for some file whose ascii value is less than "." like "*", we need to move forward to the block index -1. This caused uszie's index "pirvot" to attempt to subtract with overflow and then panic.
Signed-off-by: Huang Jianan <jnhuang@linux.alibaba.com>

rafs: fix overflow panic of rafs v6 lookup

---

storage/src/cache/cachedfile.rs
storage/src/cache/mod.rs
storage/src/meta/mod.rs

Fix the panic when run a zran image in fscache driver:
```
thread '<unnamed>' panicked at 'index out of bounds: the len
is 14 but the index is 14': storage/src/cache/cachedfile.rs:707
```

storage: minor fixups for zran in fscache

---

src/bin/nydus-image/main.rs
tests/smoke.rs

Compressor gzip are used for Zran and stargz images, it's not configurable by users. So hide it from commandline options.
Fixes: https://github.com/dragonflyoss/image-service/issues/951

nydus-image: do not expose gzip to commandline

---

contrib/nydusify/cmd/nydusify.go
contrib/nydusify/examples/converter/main.go
contrib/nydusify/go.mod
contrib/nydusify/go.sum
contrib/nydusify/pkg/converter/config.go
contrib/nydusify/pkg/converter/converter.go
contrib/nydusify/tests/nydusify.go

After nydusify was refactored, some options functionality was lost, since
the acceld converter package is currently supported, we now add them back.
- Recover `--backend-force-push` option;
- Recover `--oci` (alias `--docker-v2-format`) option;
- Recover `--platform` option, and support multiple platforms;
- Recover `--fs-align-chunk` option;
- Recover `--fs-chunk-size` (alias `--chunk-size`) option;
- Recover `--prefetch-patterns` option;
- Add `--oci-ref` option;
- Add `--all-platforms` option;

nydusify: recover more options

---

rafs/src/metadata/direct_v6.rs
storage/src/device.rs

Fix the panic when merge bootstraps for zran image:
```
level=info msg="no chunk information object for blob 0 chunk 0" module=builder
level=info msg="at rafs/src/metadata/direct_v6.rs:1163" module=builder
level=error msg="fail to run nydus-image merge..."
```

builder: fix zran bootstrap merge

---

.github/workflows/convert.yml

Prepare for refactoring build cache for nydusify, and make the test pass first:
https://github.com/dragonflyoss/image-service/actions/runs/3825905057/jobs/6509249708

ci: disable build cache for top images test

---

rafs/src/fs.rs
src/bin/nydus-image/core/context.rs
src/bin/nydus-image/inspect.rs
src/bin/nydus-image/main.rs
src/bin/nydusd/fs_cache.rs
storage/src/cache/filecache/mod.rs
storage/src/device.rs
storage/src/meta/mod.rs

There are different definitions about blob.compressed_size():
- size of all data chunks
- size of the data blob, including data chunks, digests, fs meta, toc
So introduce blob.compressed_data_size() to get size of all data chunks, and blob.compressed_size() to get blob size.

Fix warning message related to data prefetch

---

Makefile
docs/containerd-env-setup.md
docs/nydus-fscache.md
docs/nydus-zran.md

This PR fixes an issue where nydus snapshotter cannot find nydusd on some Linux versions, example:
Signed-off-by: Qinqi Qu <quqinqi@linux.alibaba.com>

docs: update nydus path to /usr/bin for better compatibility

---

Cross.toml

Building nydusd failed on linux-riscv64 with:
thread 'main' panicked at '
failed to execute command: No such file or directory (os error 2)
is `cmake` not installed?
We need to install cmake to allow cross-rs to build.

cross: install cmake

---

rafs/src/metadata/layout/v6.rs
src/bin/nydus-image/builder/mod.rs
src/bin/nydus-image/builder/tarball.rs
src/bin/nydus-image/core/blob.rs
src/bin/nydus-image/core/context.rs
src/bin/nydus-image/core/node.rs
src/bin/nydus-image/inspect.rs
src/bin/nydus-image/main.rs
src/bin/nydus-image/merge.rs
storage/src/cache/filecache/mod.rs
storage/src/cache/fscache/mod.rs
storage/src/device.rs
storage/src/meta/chunk_info_v2.rs
storage/src/meta/mod.rs

Introduce BlobFeatures::SEPARATE to support tar-ref, in addition to BlobFeatures::ZRAN.
SEPARATE means that blob.data is separated from blob.meta. ZRAN means that it contains ZRAN context information and should be decoded by ZRAN.
Fixes: https://github.com/dragonflyoss/image-service/issues/990

storage: introduce BlobFeatures::SEPARATE to support tar-ref

---

src/bin/nydus-image/builder/tarball.rs
storage/src/cache/filecache/mod.rs
storage/src/cache/fscache/mod.rs

There's a bug in xattr handling for tarball which causing losing of xattrs.
Fixes: https://github.com/dragonflyoss/image-service/issues/990

nydus-image: fix a bug in handle xattr for tarballs

---

rafs/src/metadata/layout/v6.rs
src/bin/nydus-image/core/node.rs

If all chunks of an inode are continuous in uncompressed cache file, set inode's chunk to `inode.size().next_power_of_two()`, so EROFS can optimize page cache sharing such a case.

nydus-image: refine image to enable page cache sharing for EROFS

---

api/openapi/nydus-api-v1.yaml
contrib/nydus-test/framework/rafs.py
contrib/nydus-test/functional-test/test_nydus.py
contrib/nydus-test/functional-test/test_nydusify.py
contrib/nydus-test/functional-test/test_stress.py
src/bin/nydusd/main.rs

change the nydusd  arg --prefetch as a file path, we can read the prefetch list from the file. For example:
we can use `--prefetch-files /tmp/test` and the `/tmp/test` is like 
```
/etc
/bin
/src/test.py
```
When nydusd is mounted, this file is read by line to form a prefetch list

read prefetch list(runtime) from file

---

Cargo.lock
utils/Cargo.toml
utils/src/compress/zlib_random.rs

libz-ng-sys fails to compile on ppc64le, so fallback to libz-ng.

utils: fix a compilation error for libz-ng-sys on ppc64le

---

Cargo.lock
Cargo.toml
utils/Cargo.toml

Use `powerpc64` instead of `ppc64le`.

utils: use `powerpc64` instead of `ppc64le`

---

Cargo.lock
Cargo.toml

Update fuse-backend to fix a bug in lookup().

dep: update fuse-backend to fix a bug in lookup()

---

src/bin/nydus-image/main.rs
storage/src/device.rs

Correctly calculate compressed blob size for RAFS v5 blobs with BlobFeatures::INLINED_META_FS.
And disable `--feature blob-toc` for RAFS v5.

storage: correctly calculate compressed blob size for RAFS v5

---

src/bin/nydus-image/core/context.rs
storage/src/device.rs
storage/src/meta/mod.rs

Add BlobFeature::HAS_TAR_HEADER to calcalute compressed blob size for merged bootstrap. When merging data blobs with inlined bootstrap, the BlobFeature::INLINED_FS_META flag will get lost, so we need a new flag to indicate there's tar header in these data blobs.

storage: add BlobFeature::HAS_TAR_HEADER to calcalute

---

rafs/src/metadata/direct_v6.rs

Fix a underflow bug in find_target_block() of RAFS v6. `last` is usize instead of isize so it may underflow.

rafs: fix a underflow bug in rafs v6 implementation

---

tests/bats/Makefile
tests/bats/build_docker_image.bats
tests/bats/common_tests.sh
tests/bats/compile_ctr_remote.bats
tests/bats/compile_nydus_snapshotter.bats
tests/bats/compile_nydusd.bats
tests/bats/install_bats.sh
tests/bats/run_container_with_rafs.bats
tests/bats/run_container_with_zran.bats

These cases have been merged into master branch and the difference is excluding zran format case since stable branch doesn't support zran for now.
Signed-off-by: Yiqun Leng <yqleng@linux.alibaba.com>

add e2e testcases for ci for stable branch

---

rafs/src/metadata/mod.rs

Reserve bits in RafsSuperFlags so images generated by nydus 2.2 can be mounted by v2.1.4 and later.

rafs: reserve bits in RafsSuperFlags to be compatible with v2.2

---

rafs/src/metadata/direct_v6.rs

There's a bug in calculate offset and size for RAFS v6 Dirent name, it will be treat as 0 instead of 4096 if the last block is 4096 bytes.
Fixes: https://github.com/dragonflyoss/image-service/issues/1098

rafs: fix a bug in calculate offset for dirent name

---

contrib/nydusify/cmd/nydusify.go

We should use pigz for supporting parallel gzip decompression, so that improve the conversion speed when unpack gzip layer for source image.
We still allow users to specify the env `CONTAINERD_DISABLE_PIGZ=1` to disable the feature when encounter any decompression error.
See https://github.com/containerd/containerd/blob/33c0eafb17dff6de43f4a530fcf05b02ed24330b/archive/compression/compression.go#L261

nydusify: enable pigz by default

---

src/bin/nydus-image/main.rs
src/bin/nydus-image/merge.rs

```
This option allows merging multiple bootstraps of upper layer with
the bootstrap of a parent image, so that we can implement container
commit operation for nydus image.
```

[backport stable/v2.1] builder: support `--parent-bootstrap` for merge

---

rafs/src/metadata/direct_v6.rs
src/bin/nydus-image/core/node.rs
tests/bats/compile_nydus_snapshotter.bats
tests/bats/install_bats.sh

Backports two bugfixes from master into stable/v2.1.

Backports two bugfixes from master into stable/v2.1

---

.github/workflows/ci.yml

The `pull_request_target` trigger will checkout the master branch
codes strictly, but we must use the PR codes for the smoke test.

action: fix checkout on pull_request_target

---

Cargo.lock
Cargo.toml
contrib/nydusify/pkg/checker/rule/filesystem.go
contrib/nydusify/pkg/checker/tool/image.go
contrib/nydusify/tests/e2e_test.go
contrib/nydusify/tests/nydusify.go
contrib/nydusify/tests/registry.go
misc/nydusify-smoke/entrypoint.sh

To fix the error when mount OCI v1 image in check subcommand:
```
error: mount options is too long
```
The mount options has 4k buffer size limitation, we will encounter the issue in a huge images with mass layers.
We need to shorten the length of lowerdir paths in overlayfs option, change `sha256:xxx` to `layer-N` to alleviate the issue.

[backport] nydusify: fix overlayfs mount options for check

---

storage/src/cache/cachedfile.rs
storage/src/cache/mod.rs
storage/src/device.rs
storage/src/lib.rs
storage/src/meta/mod.rs

1. Amplify I/O to reduce small requests to the backend.
2. Amplify prefetch IO to reduce the number of requests.
3. Read the blob meta header when reading the meta information.
Related PRs: https://github.com/dragonflyoss/image-service/pull/833/commits/d550dfd7bd1da4d703ba0b202b31e88e88915557, https://github.com/dragonflyoss/image-service/pull/833/commits/198746a9b599474494f10565a88c773c4a7a109e.

backport(storage): add support for non-continuous chunks to amplify IO

---

contrib/ctr-remote/Makefile
contrib/nydus-overlayfs/Makefile

Otherwise, the binary we compiled cannot run on other platforms such as arm.

contrib: support nydus-overlayfs and ctr-remote on different platforms

---

contrib/nydusify/cmd/nydusify.go
contrib/nydusify/pkg/checker/rule/filesystem.go
contrib/nydusify/pkg/viewer/viewer.go

this is the solution of issue https://github.com/dragonflyoss/image-service/issues/1306.(#1306) 
we fix the bug, the nydusify `mount` subcommand will not need the `--backend-type`  and  `--backend-config` options when  the blobs of target image are all stored in the registry,

Nydusify-fix(stable/v2.1): fix some bug about the subcommand mount of nydusify

---

rafs/src/fs.rs
rafs/src/metadata/direct_v6.rs
rafs/src/metadata/layout/v5.rs
storage/src/cache/worker.rs
storage/src/device.rs

fix: amplify io is too large to hold in fuse buffer https://github.com/dragonflyoss/image-service/pull/1311
fix: large files broke prefetch https://github.com/dragonflyoss/image-service/pull/1348

backport  #1311 # 1348

---

Cargo.lock
Cargo.toml

#1387 #1391
Update tar-rs to support read large uid/gid from PAX extensions to
fix very large UIDs/GIDs (>=2097151, limit of USTAR tar) lost in
PAX style tar during unpack.
Update tar-rs dependency xattr to 1.0.1 as well.
_What types of changes does your PullRequest introduce? Put an `x` in all the boxes that apply:_
_Go over all the following points, and put an `x` in all the boxes that apply._

[backport v2.1] deps: update tar-rs to handle very large uid/gid in image unpack 

---

APPROVERS.md
MAINTAINERS.md

This pull request updates project documentation by adding a new list of approvers and refreshing the list of maintainers. The changes ensure that contributor and reviewer information is accurate and up-to-date.
Documentation updates:
* Added a new `APPROVERS.md` file listing project approvers, including their GitHub IDs, names, emails, and affiliations.
* Updated `MAINTAINERS.md` to correct and standardize names, emails, and company affiliations, and to add several new maintainers to the list.
To follow the community governance rules for subproject: https://github.com/dragonflyoss/community/issues/90

update MAINTAINERS and APPROVERS list

---

README.md

This pull request includes minor updates to the `README.md` file to improve formatting and clarity in the documentation.
Documentation improvements:
* Fixed the alignment of the Nydus tools table for better readability.
* Updated the Dingtalk contact section to display the group number as text instead of an QR link.

docs: remove expired dingtalk group invitation QR code and url
